### ISSUE TITLE
NumberInput: Marked as invalid if the value supplied is ''

### ISSUE THREAD

**Issue by AndySeymour2904** [IBM/carbon-components-react#1001]
https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/NumberInput/NumberInput.js#L156

What happens in the situation where you have an optional NumberInput field?

It seems there is no way to do this, my suggestion is to remove the check and let the consumer make all the decisions about validity with the invalid flag provided

**Comment by asudoh** [comment]
Thanks @AndySeymour2904 for reporting! Sounds that it makes sense - Let’s see what others in the team think.

**Comment by enniel** [comment]
@asudoh Maybe better add property "strict" for this.
