### ISSUE TITLE
Usability of ComboBox component, plus overall guidance of Storybook

### ISSUE THREAD

**Issue by garciaam** [IBM/carbon-components-react#1020]
Usability of ComboBox component plus Overall guidance of Storybook is unhelpful

I need some help figuring out how to use the ComboBox component. I don't see an example of what the 'itemToString' method should do. I am not able to see my items in the dropdown. Also, the example items in Storybook don't help, the items have double brackets and three dots at the end, it's not a usable example.

Overall, it would be very helpful to have simple, live demos for each component. Or at least details of what each prop is and what each method should do. A few of the components don't have the full list of props and prop types in the Storybook documentation. I can't stress enough how unhelpful this tool is in its current state.

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a general issue.

> Is this issue related to a specific component?

Sort of. Need an answer ASAP regarding ComboBox. And really need to see better support for all components in Storybook.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected to see examples that work. If I copy/paste the example, it breaks, which could be acceptable if there was a detailed description of each prop/method to be used along with the component.

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ICP for Data. July 12.

**Comment by joshblack** [comment]
Hi @garciaam! 👋 Totally understand the frustration around storybook, we are frustrated by it as well! A lot of the information you're asking for is properly documented in the source code, but unfortunately isn't parsed out correctly by storybook.

It might help, in this case, to visit the source of the component directly [here](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/ComboBox/ComboBox.js), where you can view the Prop Types for the components and get descriptions about what each one does.

For examples for how to use it, you can also check out the story source in the same folder, [here](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/ComboBox/ComboBox-story.js).

Definitely would recommend this if you run into hiccups in the future, you can always reach out on our #carbon-react channel as well for help!

**Comment by Luc-Olsthoorn** [comment]
I think @garciaam has a point. There should be a disclaimer about its incompleteness and have a possible links to the examples you just listed! That would be helpful for beginners :)

**Comment by joshblack** [comment]
> There should be a disclaimer about its incompleteness

Just wanted to clarify, is this for storybook or for the component itself?

And definitely agreed! We also would love it if members from the community could help out here to fill in the gaps to help others in the future!

**Comment by Luc-Olsthoorn** [comment]
The storybook in general. As we speak I am currently trying to implement the Datatable component, and couldn't do the classic copy and paste (didn't work). And the links you posted lead me to the source code where I could see more information (specifically the story-datatable.js), and helped me debug some of the issues!

**Comment by joshblack** [comment]
For DataTable in particular, there should be a link in the info panel to this README which should help out as well! https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/DataTable/README.md

**Comment by Luc-Olsthoorn** [comment]
Yes thank you! Some of the best documentation of the components! I was getting errors with the imports and versioning (I was using an old carbon-react), but didn't realize that until I read your blog post on medium :p. The story-datatable.js led me to the missing consts.

I have been lost after having some of the missing information, such as http://react.carbondesignsystem.com/?selectedKind=Table&selectedStory=Nested%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
Where I can assume that I could figure it out, but how? Where are the proptypes? Knowing the repo had the story and sample code would have been sufficient for me

**Comment by joshblack** [comment]
Going to close this issue for now. Our takeaway here is that documentation can be vastly improved, and we'll make sure to add this into our roadmap over the next couple of sprints!
