### ISSUE TITLE
DataTable: Adding class to <TableHeader> assigns it to child element.

### ISSUE THREAD

**Issue by tw15egan** [IBM/carbon-components-react#1026]
@rob-richards commented on [Mon Jun 25 2018](https://github.com/carbon-design-system/carbon-components/issues/929)

## Detailed description

> Is this issue related to a specific component? 

`DataTable`

> What did you expect to happen? What happened instead? What would you like to see changed?

When adding a class to TableHeader, I expected it to add the class to `<th>`, not the child element.

## Additional information

![screen shot 2018-06-25 at 10 31 34 am](https://user-images.githubusercontent.com/7707326/41856745-d7281372-7863-11e8-90b8-2910cf558868.png)

<img width="545" alt="screen shot 2018-06-25 at 10 38 49 am" src="https://user-images.githubusercontent.com/7707326/41856921-3d8fba66-7864-11e8-9e73-7b65a2512e72.png">

<img width="379" alt="screen shot 2018-06-25 at 10 39 42 am" src="https://user-images.githubusercontent.com/7707326/41856925-40656fc4-7864-11e8-90db-739d3d84ddc5.png">

**Comment by joshblack** [comment]
Hi @rob-richards! 👋 What version of `carbon-components-react` are you using? I believe this is supported in latest after viewing this line:

https://github.com/IBM/carbon-components-react/blob/339ed32e9dbb7ebc00e0dcfab0f28d7c67bd94fc/src/components/TableHeader/TableHeader.js#L35

**Comment by joshblack** [comment]
Going to close this due to inactivity. Feel free to re-open!

**Comment by joshblack** [comment]
Re-opening since we need to add this to the data table as well 🙂
