### ISSUE TITLE
Tabs in mobile mode is opened

### ISSUE THREAD

**Issue by gracelo** [IBM/carbon-components-react#1054]
## Detailed description

 Describe in detail the issue you're having.
Same as https://github.com/carbon-design-system/carbon-components/issues/867
 Is this a feature request (new component, new icon), a bug, or a general issue?
bug
 Is this issue related to a specific component?
https://github.com/carbon-design-system/carbon-components/issues/867
 What did you expect to happen? What happened instead? What would you like to see changed?
Tabs / dropdown not opened when switched to mobile mode.
 What browser are you working in?
Chrome
 What version of the Carbon Design System are you using?
6.4.2
 What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Console already in production
## Steps to reproduce the issue
https://github.com/carbon-design-system/carbon-components/issues/867

## Additional information

* Screenshots or code
* Notes

FYI @asudoh

**Comment by gracelo** [comment]
Which release this is in?  @asudoh  still to be updated?

**Comment by asudoh** [comment]
@gracelo Not sure why `semantic-release` bot didn’t catch the fix, but should be in: https://github.com/IBM/carbon-components-react/releases/tag/v6.12.1
