### ISSUE TITLE
DatePicker for Sep 2018 doesn't show all the days of the month

### ISSUE THREAD

**Issue by adrianriddle** [IBM/carbon-components-react#1055]
## Detailed description

> Describe in detail the issue you're having.
The DatePicker component does not show all the days in the month of September 2018. It only goes to the 29th in the last row.
> Is this a feature request (new component, new icon), a bug, or a general issue?
bug
> Is this issue related to a specific component?
DatePicker
> What did you expect to happen? What happened instead? What would you like to see changed?
I would think it should show the full month and not have the user have to move to October and then select the 30th of September.
> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
The Demo Site: http://www.carbondesignsystem.com/components/date-picker/code
Vanilla Components version 9.0.15
React Components version 6.5.2
Website last updated on June 20, 2018 at 12:00 AM
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Not using it in a project at present, just found the issue while taking a look around.
## Steps to reproduce the issue
1. Go to http://www.carbondesignsystem.com/components/date-picker/code
2. Go to the "Single date picker" section
3. Click on the DatePicker component
4. Navigate to September 2018

## Additional information
![screen shot 2018-07-06 at 9 16 56 am](https://user-images.githubusercontent.com/17589003/42365203-1c06fe2a-80fe-11e8-85d0-3d6e8c256b5b.png)

**Comment by adrianriddle** [comment]
Same thing happens on March 2019 too.

**Comment by germanattanasio** [comment]
We are one month away 😱

**Comment by echarpibm** [comment]
I have submitted a pull request that resolves the issue in the original carbon-components.

But the local fix is quite easy as well.

Modify your local CSS with the following changes to the *height* properties:

```
.flatpickr-innerContainer,
.flatpickr-rContainer {
  width: 14.0625rem;
  height: 12.5rem; } /* orig 10.5rem = 168px */ /* New 200px = 12.5rem */

.bx--date-picker__days,
.dayContainer {
  width: 14.0625rem;
  min-width: 14.0625rem;
  max-width: 14.0625rem;
  height: 10.25rem; } /* orig 8.25rem = 132px */  /* New 164px = 10.25rem*/

  .bx--date-picker__calendar,
.flatpickr-calendar.open {
  -webkit-box-shadow: 0 12px 24px 0 rgba(0, 0, 0, 0.1);
          box-shadow: 0 12px 24px 0 rgba(0, 0, 0, 0.1);
  background-color: #fff;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
      flex-direction: column;
  -ms-flex-align: center;
      align-items: center;
  -ms-flex-pack: center;
      justify-content: center;
  padding: 0.875rem 1rem 0.25rem;
  width: 17.8125rem;
  height: 16.375rem; /* orig 14.375rem = 230px */ /* New 16.375rem = 262px*/
  border-radius: 0;
  border: none;
  overflow: hidden;
  margin-top: -1px; }
```

**Comment by tw15egan** [comment]
I would also recommend adding some extra styles to obscure the previous and next month's days that will appear

```css
.bx--date-picker__day.nextMonthDay,
.bx--date-picker__day.prevMonthDay {
    opacity: 0.5;
    color: #5a6872
}
```

**Comment by echarpibm** [comment]
Actually that CSS portion should probably be as follows:

```
  .nextMonthDay,
  .prevMonthDay {
    opacity: 0.5;
    color: #5a6872;
  }
```

The color was missing a semi-colon and the CSS needs to match on items without that prefix otherwise it only works partially.

**Comment by tw15egan** [comment]
Just curious, when will a `.nextMonthDay` not exist alongside `.bx--date-picker__day`?

**Comment by tw15egan** [comment]
It seems @echarpibm has discovered a difference between the React and Vanilla DatePicker. The React version does not apply a `.bx--date-picker__day` class. So instead: 

```css
.bx--date-picker__days .nextMonthDay,
.bx--date-picker__days .prevMonthDay {
    opacity: 0.5;
    color: #5a6872;
}
```

This is currently being added in upstream.
