### ISSUE TITLE
Buttons that support icons should be able to customize its position

### ISSUE THREAD

**Issue by iamgollum** [IBM/carbon-components-react#1072]
# Buttons

Any button that supports icons via properties:

``` 
icon="search"
 iconDescription="Search"
```

should be able to adjust its position. By default it is positioned on the right side of the text.

**Comment by tw15egan** [comment]
Based on the [usage guidelines](http://carbondesignsystem.com/components/button/usage), the icon should always appear to the right of the text. @aagonzales, is this still correct?

**Comment by aagonzales** [comment]
Correct, at the moment icons can only go on the right. This is a good touchpoint to make theme-able however in the future.

**Comment by tw15egan** [comment]
Going to close this then, and something we can keep in mind as we move to become more themeable. 

@iamgollum, in the meantime, you can override our CSS pretty easily on a global level to achieve this effect. Here is an example: 

https://codepen.io/team/carbon/pen/JBdMmQ
