### ISSUE TITLE
Tooltip and OverflowMenuItem breaking entire js page, saying FloatingMenu TypeError

### ISSUE THREAD

**Issue by nicoxxie** [IBM/carbon-components-react#1079]
## Detailed description
Breaks the entire javascript

![screen shot 2018-07-11 at 3 49 07 pm](https://user-images.githubusercontent.com/17915105/42599071-c015fc5e-8523-11e8-94fc-7de4f6a25b4c.png)
<img width="508" alt="screen shot 2018-07-11 at 3 06 05 pm" src="https://user-images.githubusercontent.com/17915105/42599242-3b4653ba-8524-11e8-996f-48ab40064b7a.png">

was working on v6.4.2

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
Tooltip and OverflowMenuItem

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v6.10.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud

## Steps to reproduce the issue

[![Edit carbon-components-react](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ooz189w5n6)
try hover over it

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Hi @nicoxxie any chance you are using React 15-? I'm asking because [`carbon-components-react` `9.x` supports React 16.4+ only](https://github.com/IBM/carbon-components-react/releases/v6.0.0). Thanks!

**Comment by nicoxxie** [comment]
Hi @asudoh we are using v16.2.0, that might be reason why, I'm going to try upgrade node and give it a try, thanks!

**Comment by nicoxxie** [comment]
Verified issue is fixed in node v16.4.1
