### ISSUE TITLE
Tabbing inside Modal component does not comply with accessibility.

### ISSUE THREAD

**Issue by zeusorion** [IBM/carbon-components-react#1090]
Problem: Currently when tabbing and the focus is on the last element of the Modal, focus goes outside of the modal.

According to the w3c org:
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

> When focus is on the last focusable element in the dialog, moves focus to the first focusable element in the dialog.

**Comment by asudoh** [comment]
Thanks @zeusorion for reporting! Great to see [vanilla’s focus-wrap behavior](https://github.com/IBM/carbon-components/pull/17) ported here.

**Comment by asudoh** [comment]
Found that it’s a duplicate of: https://github.com/IBM/carbon-components-react/issues/874
