### ISSUE TITLE
Tooltip text overflowing 

### ISSUE THREAD

**Issue by nicoxxie** [IBM/carbon-components-react#1094]
## Detailed description

> Describe in detail the issue you're having.
The tooltip width is not wide enough 

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?
Tooltip width same as text length

> What browser are you working in?
Safari

> What version of the Carbon Design System are you using?
"carbon-addons-cloud": "2.1.0",
    "carbon-addons-cloud-react": "1.2.0",
    "carbon-components": "9.1.20",
    "carbon-components-react": "6.12.2",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud 
## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

Tooltip: (safari)
![screen shot 2018-07-17 at 11 01 09 am](https://user-images.githubusercontent.com/17915105/42830774-010e6574-89b2-11e8-9653-3984804212b8.png)

**Comment by aledavila** [comment]
Hi tooltip icon is only used to clarify the action or name of an interactive icon button. Please consider using an interactive tooltip.

**Comment by nicoxxie** [comment]
@aledavila I was told tooltip icon is to replace tooltip simple, I'll switch it back, thanks...

**Comment by nicoxxie** [comment]
I removed TooltipIcon from the issue, can someone take a look at Tooltip?

**Comment by alisonjoseph** [comment]
Hi @nicoxxie is it possible to create a[ code sandbox](https://codesandbox.io/s/m32mqpk769) example showing your issue?

**Comment by nicoxxie** [comment]
@alisonjoseph I found that we had extra css on top of the .bx--tooltip
```
  width: max-content;
  white-space: nowrap;
```
and these broke only in safari.  Closing it since I don't think it's the component iself.  thanks!
