### ISSUE TITLE
Nested Accordion does not close

### ISSUE THREAD

**Issue by cjm27** [IBM/carbon-components-react#1104]
I tried to have nested accordion, formatted as follow:

```
                    <Accordion>
                        <AccordionItem title="Accordion 1">
                            <Accordion>
                                <AccordionItem title="Item 1">
                                    Item 1
                                </AccordionItem>
                                <AccordionItem title='Item 2'>
                                    Item 2
                                </AccordionItem>
                            </Accordion>
                        </AccordionItem>
                        <AccordionItem title="Accordion 2">
                            <Accordion>
                                <AccordionItem>
                                    Item 1
                                </AccordionItem>
                                <AccordionItem>
                                    Item 2
                                </AccordionItem>
                            </Accordion>
                        </AccordionItem>
                    </Accordion>
```
The outer accordion opens and closes as usual, but the nested ones stays open. There is no warning or error in the console.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Seems the same as #814 and unfortunately nesting accordion isn't a UX pattern that is supported by this library currently. As #814 says, feel free to reopen if you think there is a valid UX case for this. Thanks!

**Comment by hongcbjch** [comment]
I met the same problem. I think the nested Accordion is very common UX case, I hope this issue can be fixed. Thanks!

**Comment by unidevel** [comment]
It seem a css issue, this patch could solve this issue
```
.bx--accordion .bx--accordion__item--active .bx--accordion__content {
  visibility: hidden;
  height: 0;
  opacity: 0;
  padding-top: 0;
  padding-bottom: 0;
}

.bx--accordion .bx--accordion__item--active > .bx--accordion__content {
  padding-top: 1rem;
  padding-bottom: 1.5rem;
  height: auto;
  visibility: visible;
  opacity: 1;
}

.bx--accordion .bx--accordion__item--active .bx--accordion__arrow {
  transform: rotate(0);
}

.bx--accordion .bx--accordion__item--active > .bx--accordion__heading > .bx--accordion__arrow {
  transform: rotate(90deg);
}
```

**Comment by asudoh** [comment]
@hongcbjch Do you want to share a screenshot showing what you want to achieve, so our designers can see if it should be a valid use case for Carbon? Thanks!

**Comment by hongcbjch** [comment]
@unidevel,  thanks, adding the css you pasted to my css, it works well.

**Comment by hongcbjch** [comment]
@asudoh , please refer the screenshot.
![image](https://user-images.githubusercontent.com/42921827/44974847-6edf9580-af93-11e8-9774-3571257a7e5b.png)

**Comment by asudoh** [comment]
Thanks @hongcbjch! Above screenshot gives me an impression that you are using our accordion as a general-purpose tree view (e.g. Windows Explorer), which our accordion never intends to. If that’s not the case, do you want to explain more concrete use case (e.g. 1st level is for showing X, 2nd level is for showing Y). A screenshot or two may help explaining that. Thanks!
