### ISSUE TITLE
DataTable does not support sorting with pagination

### ISSUE THREAD

**Issue by paulbarr** [IBM/carbon-components-react#1107]
DataTable sorting only applies to the data in the DataTable
You can customized how the data is sorted, but it still only sorts the data in the Table

**Example**
I have 100 rows of data
I page my data using the carbon pagination compoenent
I want to display 20 rows in the first page
I give those 20 rows to the DataTable to show
When I sort on any column header the DataTable does not know about 80 of the rows that are not in the current page, so it can't sort on them. Sort results are therefore wrong.

**Solution**
A simple solution to to allow for a prop that is sortExternally
If this is present then the DataTable does not do any default sorting
Instead when you click on the header it gives to the sortExternally method the key of the header being sorted, and the direction.

**Who will do the work?**
I'm happy to make the necessary code changes, if you guys are happy to accept this change (after review etc)

**What am I doing now**
Currently I have an observer that watches when the column headers are clicked (based on class names)
That gives me the key, but not the direction of sort
The observer then look's at the column header, and gets the direction of the sort based on the icon
I also have a dummy custom sort method set in the props to turn off the default sorting
I'm assuming the next time the DataTable is changed this code will break
I would like to get the code change into the DataTable so that I can get rid of all my hacking code and just use the standard DataTable when I next upgrade my Carbon

**Comment by nicoxxie** [comment]
This is already achievable.  Just keep a state on the direction and pass it to the table header.  You can also pass in your own sort function for onClick. 

https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/README.md#custom-sorting
https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/TableHeader.js#L25

**Comment by paulbarr** [comment]
@nicoxxie I don't see how this will achieve what I want.
The customer sort only applies to the data that is in the table
For example I have 100 rows in my data
If I have 20 rows in the table the method is called 20 times to compare all the rows
However I need it to compare across all 100 rows
The DataTable does not know about the other 80 rows so it cant sort on it
The customer sort does not tell me the header that was clicked on - so I cant call back to my data becasue I dont know what column was sorted by the click
In relation to storing the direction of the sort we have the same kind of problem
The sortdirection will be different for each column, so if I dont know the column storing the direction wont help me

**Comment by nicoxxie** [comment]
@paulbarr Yes it's achievable you can do the sorting on your own side and pass in the data yourself.  The table is just a display, you can do you own logic anyway you want.  We've been doing that for a while.

**Comment by joshblack** [comment]
Going to close this issue as there are solutions that exist in user-space (thanks @nicoxxie for the insights here! 🎉)

At a high-level, we're definitely hoping to add in Pagination in a future release, alongside other behavior like inline editing. However, in the meantime this will be something that teams will need to implement, unfortunately.

As always, will also support PRs for adding in this kind of behavior!
