### ISSUE TITLE
DataTable: Does it support nested expanded? How?

### ISSUE THREAD

**Issue by AngelaChenBJ** [IBM/carbon-components-react#1127]
I'm trying to use DataTable with expanded to show nested expanded data like following:
![p1](https://user-images.githubusercontent.com/41713412/43243115-72c836f0-90d7-11e8-9f71-cac4e4433033.jpeg)
While the data shown in DataTable like below which is not as expected
![p2](https://user-images.githubusercontent.com/41713412/43243120-791cadce-90d7-11e8-9b29-9a2bfddb6b3f.jpeg)
I'm wondering does DataTable support nested expanded with the data format in the first screenshot above, how? Need help here. Thanks.

**Comment by joshblack** [comment]
Hi @AngelaChenBJ! 👋 DataTable supports opening up that expansion row as you noted, however the nested styling that is a part of your first screenshot is not something that Carbon provides. You can implement this as a custom component in your project.

Hope this helps! Going to close this for now, feel free to re-open if I didn't answer your question 😄
