### ISSUE TITLE
Filterable MultiSelect loses dropdown label.

### ISSUE THREAD

**Issue by alisonjoseph** [IBM/carbon-components-react#1143]
@lukefirth commented on [Mon Jul 30 2018](https://github.com/IBM/carbon-components/issues/1003)

## Detailed description

> Is this issue related to a specific component? 

Filterable MultiSelect 
 
 
 
> What did you expect to happen? What happened instead? What would you like to see changed?

It's not currently in the designkit (as far as I could see). The multi-select behaviour is problematic and different when filterable, in that it removes the dropdown label.

This is fine when the user is actively typing to filter down results, but leaves it looking confusing once some items have been selected - with the component reading: "(1x) Filter"

What I'd like to see changed: The dropdown label is returned when focus is not applied, making the component semantically readable and consistent with the non-filterable variant. When focus is applied the label could be replaced with the 'filter' message.
 
 
 
> What version of the Carbon Design System are you using? 
9

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/30671949/43408244-b4374a60-9418-11e8-8cee-393aa903b171.png)

* Notes

---

@joshblack commented on [Mon Jul 30 2018](https://github.com/IBM/carbon-components/issues/1003#issuecomment-408947661)

Hi @lukefirth! 👋 Thanks so much for taking the time to make this issue 😄 

Quick question, is this for the React.js implementation of this component?

---

@lukefirth commented on [Tue Jul 31 2018](https://github.com/IBM/carbon-components/issues/1003#issuecomment-409143361)

Hey @joshblack thanks for getting back so soon. 👋 

This is indeed! [Link to the specific component in storybook](http://react.carbondesignsystem.com/?selectedKind=MultiSelect&selectedStory=filterable&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by tw15egan** [comment]
This issue seems to be resolved, but please re-open if I have interpreted the problem incorrectly 

![multiselect](https://user-images.githubusercontent.com/11928039/45177004-51027280-b1d7-11e8-9304-353e5a968586.gif)
