### ISSUE TITLE
Descending & Ascending sort descriptions for TableHeader aren't translatable 

### ISSUE THREAD

**Issue by JoshDKing** [IBM/carbon-components-react#1146]
## Detailed description

We need to support several different languages but whenever they hover over the ascending and descending buttons english is shown and there isn't a way to pass in a description that is in a different language.

**Comment by joshblack** [comment]
Hi @JoshDKing! 👋 We should support this in our newer versions of `TableHeader`, can see the usage:

https://github.com/IBM/carbon-components-react/blob/8f01cfde5bdf9674c02b6cd48e1601f6c0818c1b/src/components/DataTable/TableHeader.js#L56-L65

Going to close this for now, feel free to re-open!
