### ISSUE TITLE
MultiSelect: setState() causes rendering issue with selected 

### ISSUE THREAD

**Issue by alimabean** [IBM/carbon-components-react#1148]
https://codesandbox.io/s/x94xn85p4o

![multiselect_wonky](https://user-images.githubusercontent.com/14437246/43539907-4139d99c-9594-11e8-9b78-2caf41caddc1.gif)

- When MultiSelect's onChange issues a setState, the selected items are reset yet the counter is kept.

EDIT:
- prop changes via redux also cause this issue

**Comment by joshblack** [comment]
Hi @alimabean! 👋 Thanks so much for taking the time to make this issue. Definitely seems like a bug on our end, so will try and get it added to a sprint. Will also accept any PRs that help to fix this!

**Comment by polgas16** [comment]
Had an issue with this awhile back. 
https://codesandbox.io/s/rrj511j4mq

**Comment by trb727** [comment]
@polgas16 I don't see a bug in your example or recreate it locally. Perhaps it has been fixed in an release since you posted?
