### ISSUE TITLE
PaginationV2: show current page number can not refresh

### ISSUE THREAD

**Issue by zhuzmzm** [IBM/carbon-components-react#1156]
## Detailed description

> Describe in detail the issue you're having.

Hi,  i have meet an issue when i use search toolbar in my grid (i do the search in my frontend), If i do some search on the second page or others just not the first page, then the table rows will refresh, and the pagination number also is refreshed when i use PaginationV2, but i found the current page the number is before the pagination selection button ( just like ‘ 1 of 3 pages’, 1 is the current page number) is not refreshed, then i checked the PaginationV2 js code, find in componentWillReceiveProps if i set the page props, it can not refresh the page state, i paste the part of code below, i think we may need to compare page with this.state.page, not the this.prop.page.

![2](https://user-images.githubusercontent.com/42019585/43634351-6c01713e-973e-11e8-854e-fb2d881c538f.png)

For example, i do the search action in my second page, then the filtered items can show in only one page, but the current page number show 2, below is my screenshot. Thanks!!!

![3](https://user-images.githubusercontent.com/42019585/43634498-d900cc6c-973e-11e8-8012-a2ec6a16733c.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Hi @zhuzmzm would you be interested in creating a reduced case based on https://codesandbox.io/s/x2mjypo6pp? Thanks!

**Comment by zhuzmzm** [comment]
Hi @asudoh I have creating a case based on [https://codesandbox.io/s/xm4979x2q](url), looking forward your response, thanks!

**Comment by asudoh** [comment]
Hi @zhuzmzm I saw the problem went away when I added `page={page}` and `pageSize={pageSize}` to the `<PaginationV2>` in your CodePen. (Example: https://codesandbox.io/s/715zkpp7w0)

Hope it helps!
