### ISSUE TITLE
MultiSelect: initialSelectedItems are not highlighted

### ISSUE THREAD

**Issue by alimabean** [IBM/carbon-components-react#1158]
https://codesandbox.io/s/ll51z4vw97

<img width="557" alt="screen shot 2018-08-03 at 12 50 40 pm" src="https://user-images.githubusercontent.com/14437246/43655183-e05d1358-971b-11e8-8b7e-89d5b675e588.png">

The MultiSelect's state reflects the initialSelectedItems yet the display does not.

**Comment by zerostatic** [comment]
@alimabean Here's is a working version here: https://codesandbox.io/s/m7l8m23ww9
Note that `initialSelectedItems` must pass in references to the original data. And you must also upgrade to the latest version of carbon-components-react

@alisonjoseph - Having to pass in the full object reference to `initialSelectedItems` seems a bit messy to handle. I wonder if it would be better/easier to pass in an array of id's? Though this would be a breaking change. Thought?

**Comment by asudoh** [comment]
CC @joshblack

**Comment by joshblack** [comment]
@zerostatic definitely can pass in ids, I think 😄 I think we could support both without having it be a breaking change. Would you mind opening up another issue with this suggestion? Will also 100% accept PRs that help make this happen 🎉 

Going to close this for now, feel free to comment if @zerostatic's recommendation didn't resolve the issue!
