### ISSUE TITLE
range Date Picker- how to select time or add time selection

### ISSUE THREAD

**Issue by ShuangLiLi** [IBM/carbon-components-react#1186]
## Detailed description

> Describe in detail the issue you're having.
User wants select a time duration such as 2018/08/01 12:00:00- 2018/08/14 12:00:00. Now range date picker can select special date. What about the special time? Is there new date picker with time selection or how to add time picker into date picker?
> Is this a feature request (new component, new icon), a bug, or a general issue?
feature request
> Is this issue related to a specific component?
Date Picker
> What did you expect to happen? What happened instead? What would you like to see changed?
We want date picker also supports time selection. Now there is no way. So we want new version date picker with time selection or solution about add time picker into date picker.
> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
68.0.3440.75
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Analytics Unify Console.Currently part of design for the DatePicker.
## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Hi @ShuangLiLi thank you for reporting! Seems very similar topic to https://github.com/IBM/carbon-components-react/issues/1140 - Let's discuss there - Thanks!

**Comment by ShuangLiLi** [comment]
Thanks a lot !
