### ISSUE TITLE
Primary focus in modal views should be available for every text input field

### ISSUE THREAD

**Issue by IOIO72** [IBM/carbon-components-react#1187]
## Detailed description

The ModalWrapper and Modal components offer the possibility to define, which text input field should be focused for user input via `selectorPrimaryFocus` and its data attribute.

For now, it's only possible to use the TextInput component.

It should be possible for every carbon component which offers text input fields like the ComboBox.

This is a feature request (or somehow a bug fix request).

I'm using version 6.20.0 of carbon-components-react.

**Comment by asudoh** [comment]
@joshblack Are you open to mapping misc attributes (props) in `<ComboBox>` to its `<input>`? Thanks!
