### ISSUE TITLE
Stateless custom text input doesn't allow to use refs

### ISSUE THREAD

**Issue by IOIO72** [IBM/carbon-components-react#1191]
## Detailed description

The `TextInput` component is stateless and can't be used in combination with refs.

## Additional information

https://reactjs.org/docs/refs-and-the-dom.html

**Comment by joshblack** [comment]
Hi @IOIO72! 👋 Thanks for taking the time to make this issue.

Could you elaborate a bit more on what you're expecting here? Is the request to convert the form elements to be class-based in order to use `ref`s?

**Comment by IOIO72** [comment]
Hi Josh, yes. Sorry for being too brief.
It would be nice, if the input fields world accept refs and therefore they should be converted to classes.

**Comment by asudoh** [comment]
Hi @IOIO72 wondering this is similar to what you want: https://github.com/IBM/carbon-components-react/blob/be9b7d0/src/components/Button/Button.js#L51

**Comment by joshblack** [comment]
We could probably wrap any of our stateless form components with `React.forwardRef`, I bet, to satisfy this use-case. What do you think @asudoh?

**Comment by asudoh** [comment]
Makes total sense for stateless ones @joshblack! For stateful we may want to do with next major release not to suddenly change what `ref` in our component means.

**Comment by silesky** [comment]
PR here https://github.com/IBM/carbon-components-react/pull/1770
