### ISSUE TITLE
InlineNotification Story Info missing

### ISSUE THREAD

**Issue by IOIO72** [IBM/carbon-components-react#1203]
## Detailed description

The Storybook doesn't show the documentation (button *Show Info*) of the component `InlineNotification` anymore.

## Steps to reproduce the issue

Just look at the storybook page: [Notifications/inline](http://react.carbondesignsystem.com/?knob-Label%20text%20%28labelText%29=Search&knob-Label%20text%20%28labelText%20in%20%3CRadioButton%3E%29=Radio%20button%20label&knob-Label%20in%20the%201st%20item%20%28labelTwo%29=Estimate%20Monthly%20Cost&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B0%5D=10&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B1%5D=20&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B2%5D=30&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B3%5D=40&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B4%5D=50&knob-Step%20of%20up%2Fdown%20arrow%20%28step%29=10&knob-Placeholder%20text%20%28placeHolderText%29=Search&knob-Close%20icon%20description%20%28iconDescription%29=Close%20the%20modal&knob-The%20SVG%20%60height%60%20attribute%20%28height%29=&knob-The%20SVG%20%60fill%60%20attribute%20%28fill%29=grey&knob-The%20number%20of%20lines%20in%20a%20paragraph%20%28lineCount%29=3&knob-Form%20item%20name%20%28name%29=&knob-The%20SVG%20%60fillRule%60%20attribute%20%28fillRule%29=&knob-The%20modal%20heading%20%28modalHeading%29=Modal&knob-The%20description%20for%20the%20backward%20icon%20%28forwardText%29=Forward&knob-UI%20type%20%28Only%20for%20%60%3CMultiSelect%3E%60%29%20%28type%29=default&knob-The%20form%20control%20name%20%28name%20in%20%3CRadioButtonGroup%3E%29=radio-button-group&knob-Maximum%20value%20%28max%29=100&knob-Minimum%20value%20%28min%29=0&knob-Label%20in%20the%201st%20item%20%28labelOne%29=Need%20Help%3F&knob-The%20label%20text%20for%20the%20close%20button%20%28closeButtonLabelText%29=&knob-Total%20number%20of%20items%20%28totalItems%29=103&knob-The%20content%20in%20%3Ctitle%3E%20in%20SVG%20%28description%29=This%20is%20a%20description%20of%20the%20icon%20and%20what%20it%20does%20in%20context&knob-The%20notification%20kind%20%28kind%29=error&knob-The%20title%20%28title%29=Section%201%20title&knob-The%20description%20for%20the%20backward%20icon%20%28backwardText%29=Backward&knob-The%20link%20href%20%28href%29=%23&knob-Form%20requirement%20text%20%28messageText%29=&knob-Label%20for%20%60pageSizes%60%20select%20UI%20%28itemsPerPageText%29=Items%20per%20page%3A&knob-ARIA%20label%20%28modalAriaLabel%29=&knob-Optional%20label%20%28modalLabel%29=Label&knob-The%20duration%20for%20successful%20state%20before%20%60onSuccess%60%20fires%20%28successDelay%29=1500&knob-Text%20in%20%3Clegend%3E%20%28legendText%29=Checkbox%20heading&knob-Modal%20heading%20%28modalHeading%29=Modal%20heading&knob-Label%20in%20the%201st%20item%20%28linkTextTwo%29=Cost%20Calculator&knob-The%20modal%20label%20%28optional%29%20%28modalLabel%29=Label&knob-ARIA%20role%20%28role%29=alert&knob-The%20text%20in%20the%20trigger%20button%20%28buttonTriggerText%29=Launch%20Modal&knob-Link%20href%20in%20the%201st%20item%20%28linkHrefOne%29=www.google.com&knob-CSS%20class%20name%20%28className%29=some-class&knob-Secondary%20button%20text%20%28secondaryButtonText%29=Secondary%20Button&knob-Number%20of%20items%20per%20page%20%28pageSize%29=10&knob-Open%20%28open%29=true&knob-The%20current%20page%20%28page%29=1&knob-Primary%20button%20text%20%28primaryButtonText%29=Primary%20Button&knob-The%20icon%20%28icon%20%28regular%29%2Fname%20%28legacy%29%29=iconAdd&knob-Close%20after%20submit%20%28shouldCloseAfterSubmit%29=true&knob-Link%20href%20in%20the%202nd%20item%20%28linkHrefTwo%29=www.google.com&knob-The%20text%20in%20the%20secondary%20button%20%28secondaryButtonText%29=Cancel&knob-Loading%20progress%20description%20%28description%29=Loading%20data...&knob-Link%20text%20in%20the%201st%20item%20%28linkTextOne%29=Contact%20Bluemix%20Sales&knob-Value%20%28value%29=&knob-Icon%20description%20%28iconDescription%29=describes%20the%20close%20button&knob-Label%20%28label%29=Number%20Input%20label&knob-Caption%20%28caption%29=Time%20stamp%20%5B00%3A00%3A00%5D&knob-Title%20%28title%29=Notification%20title&knob-ARIA%20label%20%28ariaLabel%29=&knob-Subtitle%20%28subtitle%29=Subtitle%20text%20goes%20here.&knob-Width%20%28in%20px%20or%20%25%29%20of%20single%20line%20of%20text%20or%20max-width%20of%20paragraph%20lines%20%28width%29=100%25&knob-Form%20validation%20UI%20content%20%28invalidText%20in%20%3CSelect%3E%29=A%20valid%20value%20is%20required&knob-Footer%20text=&knob-Form%20validation%20UI%20content%20%28invalidText%29=Number%20is%20not%20valid&knob-The%20text%20in%20the%20primary%20button%20%28primaryButtonText%29=Save&knob-Menu%20direction%20%28Only%20with%20%60floatingMenu%60%29%20%28direction%29=bottom&knob-Current%20progress%20%28currentIndex%29=3&knob-Button%20text%20%28buttonText%29=Create&knob-Active%20%28active%29=true&knob-The%20SVG%20%60width%60%20attribute%20%28width%29=&knob-Value%20of%20the%20selected%20button%20%28valueSelected%20in%20%3CRadioButtonGroup%3E%29=default-selected&selectedKind=Notifications&selectedStory=inline&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by asudoh** [comment]
Hi @IOIO72 thank you for reporting! here's the direct link to what you are looking for: http://react.carbondesignsystem.com/?selectedKind=Notifications&selectedStory=inline&knob-The%20notification%20kind%20%28kind%29=info - Also you can get there manually by clicking on the "Knobs" tab at the bottom and choose "Info (info)" as the "The notification kind (kind)". Feel free to speak up if you have any further questions - Thanks!
