### ISSUE TITLE
Feature request: toggle on / off Data Table zebra striping

### ISSUE THREAD

**Issue by holmansze** [IBM/carbon-components-react#1205]
## Detailed description
Feature request: toggle on / off Data Table zebra striping

Could you add support to [Data Table](http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&selectedKind=DataTable&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) to enable toggle on / off zebra striping (alternating row colors)?

The current table always has the `bx--data-table-v2--zebra` css class and it cannot be turned off via Data Table React props.

**Comment by asudoh** [comment]
@aagonzales @designertyler Does a data table (v2) without zebra stripe make sense? Thanks!

**Comment by aagonzales** [comment]
Zebra stripes should be a toggle-able visual style. Teams can choose to have zebra stripes or not. It is not a requirement. I believe the Vanilla version has it toggle-able already.
