### ISSUE TITLE
TableToolBarSearch: the close_button_icon's position should be in the center of the close_button

### ISSUE THREAD

**Issue by xiaolixu** [IBM/carbon-components-react#1208]
In the TableToolBarSearch component , the close_button_icon is not in the right position and it should be in the center of the close_button .
<img width="290" alt="screen shot 2018-08-21 at 1 51 47 pm" src="https://user-images.githubusercontent.com/24239504/44382990-adb02d00-a549-11e8-8089-bd9ab9edd7f5.png">

**Comment by joshblack** [comment]
Hi @xiaolixu! 👋 Thanks for taking the time to make this issue.

Could you share a link to a codesandbox or something with steps to reproduce? There should be a link available in the issue template that popped up when you were making the issue 👍

**Comment by xiaolixu** [comment]
steps to reproduce ：
    In our project, just use TableToolbarSearch component as in the blow screenshot, then the issue can be seen, I think the issue should be related the version of carbon-components-react , the issue can not be seen in the previous version, now we use 5.52.4 .
`{ search &&
            <TableToolbarSearch
              translateWithId={translateWithId}
              aria-label={`${title}-search`}
              onChange={searchChange || onInputChange}
            />
          }`

**Comment by xiaolixu** [comment]
the cause should be that the versions of carbon-icons and carbon-component is unmatched, the issue is seen with `"carbon-components": "8.18.18",
    "carbon-components-react": "5.52.4",
    "carbon-icons": "5.1.2",` , the issue will disappear with the `"carbon-icons": "6.3.2",`

**Comment by xiaolixu** [comment]
overview , close the issue.
