### ISSUE TITLE
Dropdown - missing widthBasedOnContent functionality from ap-components-react

### ISSUE THREAD

**Issue by tomkdgun** [IBM/carbon-components-react#1209]
Dropdown - missing **widthBasedOnContent** functionality from ap-components-react

## Detailed description

We currently using ap-components-react, and we need to migrate to carbon-components-react.
We have around 250 Dropdowns across 150 files.

Without this **widthBasedOnContent** it will be very difficult to perform migration, without layout changes on each migrated screen.

**Comment by joshblack** [comment]
Hi @tomkdgun! 👋 Thanks for taking the time to make this suggestion to improve the codebase.

Could you provide more information about what you're expecting this prop to do in the component? An example would be great. Thanks!

**Comment by tomkdgun** [comment]
@joshblack The width of Dropdown is automatically adjusted based on length of items text.
E.g. If options are "Option1", "Option123, "Option123456", width of Dropdown will be sufficient to display "Option123456", without specifying static width on parent or on element itself.

**Comment by joshblack** [comment]
Is this not present in the library already @tomkdgun?

**Comment by tomkdgun** [comment]
It seems Dropdown uses 100% width of parent element.
http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-Dropdown%20type%20%28type%29=default&knob-Label%20%28label%29=Label&selectedKind=DropdownV2&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by asudoh** [comment]
Not sure what the library @tomkdgun brought up does, but in case it’s changing style based on the content - I’d suggest just opening up an interface that consumers can do it by themselves. Inspecting how browser did the layout and making UI changes based on causes [forced synchronous layout](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid_forced_synchronous_layouts) and tends to require lots of tweaks to get it fully right.

**Comment by tomkdgun** [comment]
@asudoh Probably inline-flex/block with width: auto, and required paddings/margins will be sufficient.
We are requesting this feature, to be able to migrate to Carbon Dropdown, without requirement to modify views layout.

**Comment by asudoh** [comment]
Thanks @tomkdgun for giving this a thought! `<DropdownV2>` as well as `<Dropdown>` have `className` prop where you can add your custom class, and thus you can change styles of any DOM nodes inside the dropdown in app-land. Hope this helps!

**Comment by tomkdgun** [comment]
@asudoh In this way, each product which will try to do it, will finish with different DropdownV2, e.g. space between selected option text and "triangle", so basically different width for same options.

**Comment by asudoh** [comment]
AFAIK different design flavors of Carbon components would go one of below three buckets:

1. One that makes sense to core Carbon - Change made in Carbon side in this case
2. One that Carbon would allow different (often slight) UX choices - Change made in `carbon-addons-*` or in app-land in this case
3. One that Carbon would not allow different UX choices - App has to align to Carbon design in this case

That said, I naïvely assumed it’s 2. but let’s see what our designer thinks. Thanks!

**Comment by aagonzales** [comment]
Akira's 3 flavors are correct.

I think we need some more design context here though. Why is adjusting the dropdown to content the correct ux solution in this usecase? Why does a fix width with truncated content or a text wrapping pattern not work?

**Comment by tomkdgun** [comment]
@aagonzales 
1. In some cases we would like to have Dropdown as narrow as possible e.g. filtering options
![image](https://user-images.githubusercontent.com/17591704/44573695-978fb000-a787-11e8-91a6-f384d795f3c0.png)
It's strange, when you have fixed, known list of values, and for some languages (Polish, Spanish) the option is always truncated.
2. We would like to have a possibility to migrate to Carbon from ap-components-react, without requirement with changing layout on all views with Dropdown (230 dropdowns on 130 views/screens).

**Comment by aagonzales** [comment]
oooh got it...I thought you wanted this for the opposite effect of having really long fields. I don't think we should let them be super long based on content, they should have a max width and then overflow into a second line then if still too long `...` the content. 

However, oppositely which is the request you are making is acceptable. I think prefectly reasonably for the fields to be a smaller size.

It would be optimal if dev/design could choose between:
- a specific set width (if design wanted them all the same size)
- responded to content up to a max width of 400px? (just guessing on that max width)
