### ISSUE TITLE
Is there any plan to support Chart components? 

### ISSUE THREAD

**Issue by ilovepumpkin** [IBM/carbon-components-react#1216]
Our project needs to show some charts, but carbon-components-react does not provide Chart component, so I have to build them on my own and customize them to carbon chart style.  So I am wondering if carbon-components-react is going to provide Chart components? Thanks.

**Comment by asudoh** [comment]
Hi :wave: this may be your interest: https://github.com/carbon-design-system/carbon-addons-data-viz-react

**Comment by ilovepumpkin** [comment]
@asudoh COOL! this is what I need. 

One question: I see the height/width are number. Does it mean I can not use percentage value like "100%"? Does it mean the chart is not responsive? For example, if the chart container is resizble, the charts could resize automatically or not?

**Comment by asudoh** [comment]
@ilovepumpkin I’m not personally familiar with the implementation of the charting library. You may want to file an issue with your question there…? Thanks!

**Comment by alisonjoseph** [comment]
There is also https://github.com/IBM/carbon-charts @ilovepumpkin

**Comment by joshblack** [comment]
Going to close this issue for now, seems like we have some projects moving forward. Feel free to re-open if you want!

**Comment by ilovepumpkin** [comment]
@asudoh okay, thanks!

**Comment by ilovepumpkin** [comment]
@alisonjoseph thanks! But I got 404 error when opening https://pages.github.com/IBM/carbon-charts/ and https://pages.github.com/IBM/carbon-charts/documentation/ . And from Readme, it seems React is not supported yet.

**Comment by alisonjoseph** [comment]
@ilovepumpkin You can view here, http://charts.carbondesignsystem.com and correct this is currently just vanilla and angular, however, I believe they have or are working on React wrappers.
