### ISSUE TITLE
Wanted Help : Programatically, How do we select/deselect rows of DataTable ?

### ISSUE THREAD

**Issue by subhak77** [IBM/carbon-components-react#1217]
How do we have a control on Data Table to select/deselect rows ?
I tried something below but not luck,
Can someone please help me how we can achieve this behavior ?

Thanks in advance !

![image](https://user-images.githubusercontent.com/42539457/44458049-998c2e80-a622-11e8-9858-7cb60b8a3c41.png)

**Comment by joshblack** [comment]
Hi @subhak77! 👋 Here's an example of how to do it in a Codesandbox: https://codesandbox.io/s/pkwzmj6yv7

Hope that helps! If not, feel free to comment and we can re-open the issue 😄
