### ISSUE TITLE
DropdownV2: Allow users to set custom keys

### ISSUE THREAD

**Issue by Anisa9514** [IBM/carbon-components-react#1219]
Currently, the keys to the dropdown menu are set through the itemToString() function which can be passed as a prop. 

![react-dropdown](https://user-images.githubusercontent.com/25112085/44486252-aa37a700-a618-11e8-8950-37e629977720.png)

As a user, I would like to have the option of setting my own keys that could be different from what I display. This was brought up in fix #1194, but from the looks of it no change has yet been implemented. Instead of an index, this could be an additional optional prop that the user can provide (maybe an itemToKey() function), with the itemToString() function still there as a default.

> Is this a feature request (new component, new icon), a bug, or a general issue?
feature request: slight update to DropdownV2

> Is this issue related to a specific component?
DropdownV2

**Comment by joshblack** [comment]
Hi @Anisa9514! 👋 Could you provide some pseudo-code to show how this code could be used to solve the problem you outlined?

**Comment by Anisa9514** [comment]
Hi @joshblack,

So my problem is that I am trying to render some styling to the dropdown options to implement this mock:

![dropdown](https://user-images.githubusercontent.com/25112085/44488162-ac503480-a61d-11e8-8967-3f41dd860714.png)

From experimenting, I saw that it is possible for the itemToString to return a DOM node rather than return just a string.

![dropdown-code](https://user-images.githubusercontent.com/25112085/44489045-fb976480-a61f-11e8-93f6-48ef3c058e50.png)

This will get rendered in the dropdown as shown in the above mock, but since the same function is passed along as the key as well, it will be converted to '[Object object]', which will be the case for all of the options, resulting in duplicate keys.

![dropdown-error](https://user-images.githubusercontent.com/25112085/44489341-df47f780-a620-11e8-8de7-a89806efcd8f.png)

so if I could pass my own key function I can separate what is rendered to the DOM from what is set as the key.

`itemToKey() { return item.key };`
`itemToString() {return <div>{item.name} <Tag>{item.tag}</Tag></div>}`

**Comment by joshblack** [comment]
Ah, gotcha. I would recommend against doing the node returned for `itemToString` for this exact purpose. `itemToString` should return the label for the item, and nothing more.

**Comment by Anisa9514** [comment]
Is there any way the styling above (with the tag) can be implemented within the dropdown component?

**Comment by joshblack** [comment]
Currently not. Definitely feel free to make an issue suggesting this enhancement 😄 Going to close this for now, feel free to comment if you feel like we should re-open!
