### ISSUE TITLE
Update ui1-04 color for cloud add-on module component

### ISSUE THREAD

**Issue by diana-sun** [IBM/carbon-components-react#1226]
## Detailed description

> Describe in detail the issue you're having.
With the updated ui colors, the divider line should be changed to ui-03, (right now it's ui-04, which is too dark against the background) https://github.com/carbon-design-system/carbon-addons-cloud/blob/master/src/components/module/_module.scss#L30

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
yes the cloud add-on module component

> What did you expect to happen? What happened instead? What would you like to see changed?
The divider line used to be light gray, and now it's dark gray. Would like to change it to a lighter gray.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v9

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Cloud Kubernetes service

## Additional information

<img width="1573" alt="screen shot 2018-08-23 at 11 06 05 am" src="https://user-images.githubusercontent.com/10226935/44540766-897d5900-a6cd-11e8-9b50-545614df8355.png">

^Example

**Comment by joshblack** [comment]
Hi @diana-sun! 👋 Mind making this issue on the `carbon-addons-cloud` project? This project is meant for React components for Carbon 😄

**Comment by diana-sun** [comment]
Oh ok sure thing! thanks @joshblack :)

**Comment by joshblack** [comment]
Thanks! 🙏
