### ISSUE TITLE
The `locale` setting of `DatePicker` is not effective

### ISSUE THREAD

**Issue by zyjiaobj** [IBM/carbon-components-react#1241]
## Detailed description

> I am using `Date Picker`, and I set the attribute `locale` to be `zh` (Chinese). But when the `Date Picker` is rendered, the displayed month is still English… 

> Shouldn’t it be Chinese ?

## Steps to reproduce the issue
Sandbox link: https://codesandbox.io/s/p968k4032j

**Comment by zyjiaobj** [comment]
@alisonjoseph so what's the result?? the `locale` should be set on `<DatePicker>`, instead of `<DatePickerInput>`

but when I set the `locale` to be `zh` on `<DatePicker>` (https://codesandbox.io/s/p968k4032j) , when i click on the DatePicker to select a date,  the displayed month on the calendar is still English.... Does `<DatePicker>` support Chinese calendar?

**Comment by asudoh** [comment]
@zyjiaobj Do you want to upgrade `carbon-components-react` to pick up https://github.com/IBM/carbon-components-react/pull/855? Thanks!
