### ISSUE TITLE
Console Errors when add certain components

### ISSUE THREAD

**Issue by lounestor** [IBM/carbon-components-react#1243]
## Detailed description
[
![screen shot 2018-08-28 at 11 02 21](https://user-images.githubusercontent.com/1750007/44716448-3717b000-aab2-11e8-9984-feba1a8c331d.png)
](url)

When My application starts I see console error messages for some components for
 - AccordionItem
 - PaginationV2
 - Tooltip
 - NumberInput
 - ProgressIndicator
E.g
warning.js:33 Warning: ProgressIndicator: Did not properly initialize state during construction. Expected state to be an object, but it was undefined.

> Describe in detail the issue you're having. The Component seems to behave normally but i am getting stack traces on my browser console since upgrading to ^6.26.0 from 6.14.3

> Is this a feature request (new component, new icon), a bug, or a general issue? general - I dont see it in all components we are using e.g TooltipIcon

> Is this issue related to a specific component? Only seen it in some components

> What did you expect to happen? What happened instead? What would you like to see changed? Console was clear of errors

> What browser are you working in? Chrome mainly

> What version of the Carbon Design System are you using? ^6.26.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Transformation Advisor
## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment]
Hi @lounestor! 👋 It'd be awesome if you could fill out the issue template that was shown when you first created the issue. This will help us figure out what's going on faster. Thanks!

**Comment by lounestor** [comment]
@joshblack I updated the discription. I guess not much  more. with thoes version when i add those specific components i see thoes error messages. I can tell for the PaginationV2 that UNSAFE method hasn't been removed yet in the code but for the other errors im not sure

**Comment by asudoh** [comment]
`warning.js:33 Warning: ProgressIndicator: Did not properly initialize state during construction. Expected state to be an object, but it was undefined.` is a dup of: https://github.com/IBM/carbon-components-react/issues/1204

**Comment by joshblack** [comment]
Related PR: #1255
