### ISSUE TITLE
The overflow menu using floatingMenu is not positioned properly when the window is scrolled in any direction on IE11

### ISSUE THREAD

**Issue by zgrossbart** [IBM/carbon-components-react#1245]
The overflow menu is not positioned properly when the page is scrolled in any direction on IE11.  It works well for every other browser including Edge.

![overflow_menu](https://user-images.githubusercontent.com/664044/44719666-d8821000-aa78-11e8-863f-9edaa70bea14.png)

This happens for horizontal scrolling as well as vertical scrolling.

**Comment by joshblack** [comment]
cc @asudoh do you think this is related to position logic that needs to be synced upstream, or is this something that we just haven't updated yet from the positioning logic upstream?

**Comment by asudoh** [comment]
Hi @zgrossbart you can open the link with Chrome and click download button at the top. After you add `<link rel="stylesheet" type="text/css" href="https://unpkg.com/carbon-components/css/carbon-components.min.css">` to `public/index.html` and then do `yarn install`/`yarn start` you’ll see the example working (you may want to import `babel-polyfill` or the same list of module seen in https://github.com/IBM/carbon-components-react/blob/087604a/.storybook/polyfills.js for IE). After you create your reduced case, you can use upload button at the files section on the left. Hope this helps!

**Comment by zgrossbart** [comment]
I tried running it locally, but I still just get a bunch of errors on IE11.  They are different errors though.

![capture](https://user-images.githubusercontent.com/664044/44752413-c2536e80-aacf-11e8-8cc5-758f53cfac2a.PNG)

**Comment by asudoh** [comment]
@zgrossbart Have you done the polyfill thing I mentioned earlier? Thanks!

**Comment by zgrossbart** [comment]
Is there a sample of that.  I guess I didn't do it correctly.

**Comment by asudoh** [comment]
You may want to try something like this, though I don’t have IE right now and thus haven’t tested: [carbon-components-react.zip](https://github.com/IBM/carbon-components-react/files/2329975/carbon-components-react.zip)

**Comment by zgrossbart** [comment]
I reproduced the issue here:  https://codesandbox.io/s/jnpj1463w9

You need to download this sample and then access it with IE 11.  Then scroll down a little bit and click on one of the overflow menus.

**Comment by asudoh** [comment]
@zgrossbart Do you want to try the latest of `carbon-components-react` to pick up https://github.com/IBM/carbon-components-react/pull/1007? Thanks!

**Comment by zgrossbart** [comment]
I have the fix to #1007 in my app.  That fixed this problem on all browsers except for IE 11.  This problem still happens there.

**Comment by zgrossbart** [comment]
I upgraded my sample to the latest versions and now I can't reproduce this issue.  However, I can still reproduce it with that latest version on my app.  For now I'm going to change the menu to not be floating.  That will make my app work.

I still think there may be a bug here, but since I can't reproduce it in the sample and I have a workaround I'm going to close this issue.
