### ISSUE TITLE
Ability to do a full drop down of options with the combo box even when an item is selected

### ISSUE THREAD

**Issue by JSoet** [IBM/carbon-components-react#1246]
## Detailed description

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

Yes, combo box

> What did you expect to happen? What happened instead? What would you like to see changed?

When you have an item selected and then select the dropdown arrow, then only the current item is shown. In order to display all the items you first need to hit the 'x' to clear the current item. In our discussions with our team we've found that this is a very confusing behaviour for the customer. In our product we have a lot of dropdowns with saved values that the user may want to change. In this case, in order to change the value they first need to know to hit 'x', which may not be obvious to them (they may just try and select the dropdown and think that there are no other options) and then after hitting the 'x' to clear the current selection, if they then decide to not change the value then they have then lost the previous value that was stored there. In our product we cannot just use the normal dropdown v2 component, because we have the potential to have a lot of items in the dropdown, so it needs to be filterable to easily find the correct item. 

I would be fine with keeping the current functionality as the default, but having an option to have the functionality to show all the options would be ideal for us.

> What browser are you working in?

Chrome, Firefox

> What version of the Carbon Design System are you using?

    "carbon-components": "^9.1.13",
    "carbon-components-react": "^6.14.2",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Safer Payments

## Steps to reproduce the issue
This is reproducible in the storybook for the combobox:
http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-Placeholder%20text%20%28placeholder%29=Filter...&selectedKind=ComboBox&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
Just select an item and then try and hit the dropdown icon

## Additional information
![image](https://user-images.githubusercontent.com/4523613/44722255-cc27a280-aacc-11e8-9c71-f0321b404263.png)

**Comment by joshblack** [comment]
cc @IBM/carbon-designers just wanted to confirm this matches what we expect the UX behavior of the control to be 👍

**Comment by claycrenshaw** [comment]
Thank you for bringing this to our attention, @JSoet ! (Unfortunately I can't seem to find your actual name anywhere. . . could you please add your real name to your GH profile?)

Agreed, the default behavior of this component is confusing and could be improved.

Can you provide us with designs as a proposal for the future state of this component? Low fidelity is ok at this stage.

**Comment by JSoet** [comment]
@claycrenshaw any chance to get an update on how you'd like the design to look for carbon going forward? It turns out the other component that we're using has some problems so we might need to make some customizations anyway, so if we're going to make some customizations it'd probably make more sense to make a PR to make the carbon dropdown fit our needs, rather than the other one we're using.

**Comment by apendrich** [comment]
Hi Anna Pendrich here - Just adding my support to this request. In App Connect we were looking to use the combo box, but the fact that when you select an option it essentially becomes the filter for the box makes it difficult to use. When you come back to look at the other options in the future and it shows only one thing in the drop down you don't think to clear the box and then see what's in there.

**Comment by fairclothjm** [comment]
@apendrich @JSoet 
Looks like this is a dupe of https://github.com/IBM/carbon-components-react/issues/1100 and was fixed in PR: https://github.com/IBM/carbon-components-react/pull/1502 Version 6.50.2 

I needed this behavior too 😄

**Comment by JSoet** [comment]
Thanks @fairclothjm ! That screenshot looks great, will have to try it out!!
