### ISSUE TITLE
[MultiSelect]:  initialSelectIedItems not populated on render

### ISSUE THREAD

**Issue by McBrosa** [IBM/carbon-components-react#1254]
**Summary**:
Using the MultiSelect with the `initialSelectedItems` property set on the does not check the expected items.

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
MultiSelect

> What browser are you working in?
Chrome 68.0.3440.106

> What version of the Carbon Design System are you using?
carbon-components: 9.9.0
carbon-components-react: 6.26.2
react: 16.4.2

## Steps to reproduce the issue
https://codesandbox.io/s/64xnr0zlwr

## Additional information
![screen shot 2018-08-29 at 5 34 41 pm](https://user-images.githubusercontent.com/5651466/44819266-da032380-abb1-11e8-8d27-8422b2d64a70.png)

**Comment by joshblack** [comment]
Hi there @McBrosa! 👋 Thanks so much for taking the time to make this issue 😄 

For `initialSelectedItems`, you'll actually need to pass a reference to the item you want reference. For example:

```js
import React, { Component } from "react";
import { render } from "react-dom";
import { Button, MultiSelect } from "carbon-components-react";

class App extends Component {
  state = {
    itemList: [{ label: "item1" }, { label: "item2" }]
    // initialSelectedItems: [{ label: "item1" }]
  };

  messStuffUp = items => {
    this.setState({ items: items }, () => console.log("Hello"));
  };

  render() {
    const items = this.state.itemList;
    // const initialSelectedItems = this.state.initialSelectedItems;
    return (
      <div>
        <Button>Hello world</Button>
        <MultiSelect.Filterable
          light
          placeholder="Categories"
          className="categories"
          items={items}
          initialSelectedItems={[items[0]]}
          onChange={event => this.messStuffUp(event.selectedItems)}
        />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
```

Hope that helps! Going to close this for now, feel free to re-open or comment if that doesn't help out 😄

**Comment by McBrosa** [comment]
Wow! This was a big help. Thank you for taking the time to write this up.

**Comment by krishnasreekoganti** [comment]
Is there any example where we have a user who was assigned few multi select options and saved in local store. Now if we want to show that user along with the multi select options, how are we going to give the reference. Can Someone help with this sort of situation.
