### ISSUE TITLE
ComposedModal: ESC key closes all the opened modals at once

### ISSUE THREAD

**Issue by elbrus** [IBM/carbon-components-react#1271]
## Detailed description

> Describe in detail the issue you're having.

I have 2 use cases:
1. `modal B` inside `modal A`. `modal B` can be opened only from inside of `modal A` (and is rendered inside as well). When `modal B` is closed, I expect `modal A` to stay opened.
2. form element inside modal. When user edits something in a form and tries to close a modal, I want to ask user does he want to close it before saving new data, but pressing ESC closes it automatically.

No.1 is way more important in my case.

> Is this issue related to a specific component?

ComposedModal

> What did you expect to happen? What happened instead? What would you like to see changed?

I'd like to be able to control, when ESC closes it. Similar to `Modal` component. Btw, I'm not using `Modal`, because I have a requirement not to close modal, when outside click occurs, which is a case for `Modal`.

> What version of the Carbon Design System are you using?

latest

## Steps to reproduce the issue

1. go to https://codesandbox.io/s/qxo6xx92q4
2. click `Open modal`
3. click `Open inner modal`
4. press ESC

**Comment by asudoh** [comment]
Hi 👋 thank you for taking time to write up this issue with reduced case! We are not supporting “stacked modal” [earlier discussion](https://github.com/IBM/carbon-components/issues/582) but feel free to articulate if you have a valid use case for that if it’s different from one in there.

**Comment by elbrus** [comment]
@asudoh , thanks for reply.
Actually in my case "stacked modal" isn't a problem. Problem is that sometimes I need to have multiple modals opened (they can be rendered as siblings as well, so no stacking). And I need a way to control, which one is closed while pressing ESC, because now all are closed. Atm I can only reopen the one, which I need. But it's not user friendly + unnecessary rerendering

**Comment by asudoh** [comment]
@elbrus AFAIK we don’t support two modal sitting side-by-side, either, if it’s what you meant. But again feel free to articulate if you have a valid use case for that.
