### ISSUE TITLE
Datatable: can we allow jsx/custom component on column header?

### ISSUE THREAD

**Issue by nelsonchen90** [IBM/carbon-components-react#1273]
## Detailed description

> Describe in detail the issue you're having.

https://codesandbox.io/s/7rw4j94x6
line 109, I define the column name to display a custom html element instead of just the `Name`

> Is this issue related to a specific component?

Table.TableHeader

> What did you expect to happen? What happened instead? What would you like to see changed?

I know we can use the getHeaderProps to render a completely custom component. but in this case, I just want to for render a tooltip next to the column name 'Name'. I expect the header can accept both strings and jsx/node/component.

> What browser are you working in?

browser ignostic

> What version of the Carbon Design System are you using?

6.14.2

## Steps to reproduce the issue

see https://codesandbox.io/s/7rw4j94x6

**Comment by joshblack** [comment]
Hi @nelsonchen90! 👋 Is the suggestion to loosen the TableHeader `children` prop-type from `string` to `node`, or is there more support that we could provide here?

**Comment by nelsonchen90** [comment]
@joshblack I think that will be enough - at least for my case. Thanks!

**Comment by nelsonchen90** [comment]
@joshblack I think it's fixed now, the incorrect prop type warning is gone
https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/TableHeader.js#L80
