### ISSUE TITLE
Select Box Item not rendering Properly

### ISSUE THREAD

**Issue by anupamsomani1** [IBM/carbon-components-react#1278]
Hi,

I used [Select Carbon Component](http://react.carbondesignsystem.com/?knob-Collapsed%20icon%20text%20%28tileExpandedIconText%29=Collapse&knob-Label%20text%20%28labelText%29=Slider%20Label&knob-The%20form%20element%20type%20%28inputType%29=&knob-Label%20text%20%28labelText%20in%20%3CDatePickerInput%3E%29=Date%20Picker%20label&knob-Text%20for%20%22show%20less%22%20button%20%28showLessText%29=Show%20less&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B0%5D=10&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B1%5D=20&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B2%5D=30&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B3%5D=40&knob-Choices%20of%20%60pageSize%60%20%28pageSizes%29%5B4%5D=50&knob-Step%20of%20up%2Fdown%20arrow%20%28step%29=10&knob-Button%20kind%20%28kind%29=primary&knob-Maximum%20length%20%28maxLength%20in%20%3CTimePicker%3E%29=5&knob-Close%20icon%20description%20%28iconDescription%29=Close%20the%20modal&knob-The%20step%20%28step%29=1&knob-Form%20item%20name%20%28name%29=&knob-Accepted%20file%20extensions%20%28accept%29%5B0%5D=.jpg&knob-Accepted%20file%20extensions%20%28accept%29%5B1%5D=.png&knob-The%20modal%20heading%20%28modalHeading%29=Modal&knob-Form%20validation%20UI%20content%20%28invalidText%20in%20%3CDatePickerInput%3E%29=A%20valid%20value%20is%20required&knob-Secondary%20button%20text%20%28secondaryButtonText%20in%20%3CModalFooter%3E%29=&knob-Form%20control%20type%20%28type%29=&knob-The%20description%20for%20the%20backward%20icon%20%28forwardText%29=Forward&knob-No%20label%20%28hideLabel%20in%20%3CTimePickerSelect%3E%29=true&knob-UI%20type%20%28Only%20for%20%60%3CMultiSelect%3E%60%29%20%28type%29=default&knob-Dropdown%20menu%20label%20%28ariaLabel%20in%20%3CDropdown%3E%29=dropdown%20menu%20label&knob-Optional%20title%20%28title%20in%20%3CModalHeader%3E%29=Example&knob-Supports%20multiple%20files%20%28multiple%29=true&knob-Primary%20button%20text%20%28primaryButtonText%20in%20%3CModalFooter%3E%29=Save&knob-Optional%20Label%20%28label%20in%20%3CModalHeader%3E%29=Optional%20Label&knob-Tooltip%20content%20%28tooltipText%29=Brief%20description%20of%20the%20dotted%2C%20underlined%20word%20above.&knob-Form%20item%20%28name%20in%20%3CTileGroup%3E%29=tile-group&knob-Label%20for%20untoggled%20state%20%28labelA%29=Off&knob-Status%20for%20file%20name%20%28filenameStatus%29=edit&knob-Maximum%20value%20%28max%29=100&knob-Minimum%20value%20%28min%29=0&knob-Feedback%20icon%20description%20%28iconDescription%29=Copy%20to%20clipboard&knob-Tab%20index%20%28tabIndex%20in%20%3CDropdown%3E%29=-1&knob-Plceholder%20text%20%28placeholder%20in%20%3CTimePicker%3E%29=hh%3Amm&knob-Text%20for%20%22show%20more%22%20button%20%28showMoreText%29=Show%20more&knob-The%20icon%20%28icon%29=iconInfoGlyph&knob-Total%20number%20of%20items%20%28totalItems%29=103&knob-The%20title%20%28title%29=Section%201%20title&knob-Close%20icon%20description%20%28iconDescription%20in%20%3CModalHeader%3E%29=Close&knob-The%20description%20for%20the%20backward%20icon%20%28backwardText%29=Backward&knob-Locale%20%28locale%20in%20%3CDatePickerInput%3E%29=en&knob-ARIA%20role%20of%20the%20button%20%28role%29=&knob-Feedback%20text%20%28feedback%29=Feedback%20Enabled%20%F0%9F%91%8D&knob-Label%20for%20toggled%20state%20%28labelB%29=On&knob-Link%20%28href%20in%20%3CDropdownItem%3E%29=&knob-Label%20for%20%60pageSizes%60%20select%20UI%20%28itemsPerPageText%29=Items%20per%20page%3A&knob-Max%20height%20%28tileMaxHeight%29=0&knob-The%20initial%20trigger%20text%20%28defaultText%20in%20%3CDropdown%3E%29=Dropdown%20label&knob-ARIA%20label%20%28modalAriaLabel%29=&knob-Placeholder%20text%20%28placeholder%29=Placeholder%20text&knob-Tooltip%20content%20%28text%29=This%20is%20some%20Tooltip%20text.&knob-The%20label%20description%20%28labelDescription%29=only%20.jpg%20files%20at%20500mb%20or%20less&knob-Form%20item%20name%3A%20%28name%29=&knob-Optional%20label%20%28modalLabel%29=Label&knob-Button%20kind%20%28buttonKind%29=&knob-The%20duration%20for%20successful%20state%20before%20%60onSuccess%60%20fires%20%28successDelay%29=1500&knob-Placeholder%20text%20%28placeholder%20in%20%3CDatePickerInput%3E%29=mm%2Fdd%2Fyyyy&knob-Selected%20text%20%28selectedText%20in%20%3CDropdown%3E%29=&knob-Modal%20heading%20%28modalHeading%29=Modal%20heading&knob-Tab%20index%20%28tabIndex%29=0&knob-Href%20for%20clicable%20UI%20%28href%29=%23&knob-The%20modal%20label%20%28optional%29%20%28modalLabel%29=Label&knob-The%20text%20in%20the%20trigger%20button%20%28buttonTriggerText%29=Launch%20Modal&knob-The%20ARIA%20label%20for%20the%20%3Cinput%3E%20%28ariaLabelInput%29=&knob-Dropdown%20type%20%28type%29=default&knob-The%20step%20factor%20for%20Shift%2Barrow%20keys%20%28stepMuliplier%29=4&knob-Trigger%20icon%20description%20%28iconDescription%20in%20%3CDropdown%3E%29=&knob-Collapsed%20icon%20text%20%28tileCollapsedIconText%29=Expand&knob-Secondary%20button%20text%20%28secondaryButtonText%29=Secondary%20Button&knob-Number%20of%20items%20per%20page%20%28pageSize%29=10&knob-Open%20%28open%29=true&knob-The%20current%20page%20%28page%29=1&knob-Primary%20button%20text%20%28primaryButtonText%29=Primary%20Button&knob-How%20long%20the%20text%20is%20shown%20upon%20clicking%20%28feedbackTimeout%29=3000&knob-Close%20after%20submit%20%28shouldCloseAfterSubmit%29=true&knob-Selected%20value%20%28value%20in%20%3CDropdown%3E%29=&knob-The%20label%20title%20%28labelTitle%29=Upload&knob-Icon%20%28icon%29=none&knob-Open%20%28open%20in%20%3CComposedModal%3E%29=true&knob-The%20maximum%20value%20%28max%29=100&knob-The%20text%20shown%20upon%20clicking%20%28feedback%29=Copied%21&knob-The%20minimum%20value%20%28min%29=0&knob-Value%20of%20the%20selected%20item%20%28valueSelected%20in%20%3CTileGroup%3E%29=&knob-The%20text%20in%20the%20secondary%20button%20%28secondaryButtonText%29=Cancel&knob-Form%20item%20name%20%28name%20in%20%3CRadioTile%3E%29=tiles&knob-Loading%20progress%20description%20%28description%29=Loading%20data...&knob-Value%20%28value%29=50&knob-Icon%20description%20%28iconDescription%29=tooltip&knob-Label%20for%20minimum%20value%20%28minLabel%29=&knob-Label%20%28label%29=Number%20Input%20label&knob-Label%20text%20%28labelText%20in%20%3CTimePickerSelect%3E%29=Please%20select&knob-Form%20validation%20UI%20content%20%28invalidText%20in%20%3CTimePicker%3E%29=A%20valid%20value%20is%20required&knob-ARIA%20label%20%28ariaLabel%29=Label%20Name&knob-Label%20for%20maximum%20value%20%28maxLabel%29=&knob-The%20button%20label%20%28buttonLabel%29=Add%20files&knob-Form%20validation%20UI%20content%20%28invalidText%20in%20%3CSelect%3E%29=A%20valid%20value%20is%20required&knob-Form%20validation%20UI%20content%20%28invalidText%29=Number%20is%20not%20valid&knob-Trigger%20icon%20description%20%28iconDescription%20in%20%3CTimePickerSelect%3E%29=open%20list%20of%20options&knob-The%20text%20in%20the%20primary%20button%20%28primaryButtonText%29=Save&knob-Regular%20expression%20for%20the%20value%20%28pattern%20in%20%3CTimePicker%3E%29=%281%5B012%5D%7C%5B1-9%5D%29%3A%5B0-5%5D%5B0-9%5D%28%5Cs%29%3F%28%3Fi%29&knob-Tooltip%20direction%20%28direction%29=bottom&knob-Current%20progress%20%28currentIndex%29=3&knob-The%20date%20format%20%28pattern%20in%20%3CDatePickerInput%3E%29=d%7B1%2C2%7D%2Fd%7B4%7D&knob-Helper%20text%20%28helperText%29=Optional%20helper%20text.&knob-Label%20text%20%28labelText%20in%20%3CTimePicker%3E%29=Select%20a%20time&knob-Active%20%28active%29=true&selectedKind=Select&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and try below url:
https://codesandbox.io/s/2vk4n6jw7y

Issue I found that was not rendering as expected.

Thanks

**Comment by tw15egan** [comment]
If you remove the `className="bx--select-input"` to the `Select` element, and the wrapping `div` it renders correctly. These classes will be provided by the component itself. 

To use the light version, just pass the `light` prop down to `Select`. Hope this helps!
