### ISSUE TITLE
Storybook Story Source is not changed when user clicks different versions of component

### ISSUE THREAD

**Issue by alohr51** [IBM/carbon-components-react#1287]
## Detailed description

> Describe in detail the issue you're having.

* on http://react.carbondesignsystem.com The Story Source doesn’t change when you click the different versions of the component. For example, DataTables component Story Source (after clicking “show info”) is the same for “with toolbar”, “with sorting”, “with selection”, etc… Should the source update with these different versions of the component?

> Is this issue related to a specific component?

* At least the DataTable storybook, I haven't looked at other components story books

> What did you expect to happen? What happened instead? What would you like to see changed?

* I expect the story source to update to reflect the different version of DataTables clicked

> What browser are you working in?

* Google Chrome Version 69.0.3497.81 (Official Build) (64-bit)

## Steps to reproduce the issue

1. Go to http://react.carbondesignsystem.com
2. Click DataTable on the left hand menu
3. Click through the different sub categories of DataTable and notice the Story Source (shown by clicking "show info" in the upper right corner) is the same for all the different versions.

**Comment by asudoh** [comment]
@alohr51 Looks that all stories you brought up have very similar story source, only difference I can see is the `render` prop. Probably that's why you thought all the same? Did you look at the "with dynamic content" story? Thanks!

**Comment by alohr51** [comment]
I was pointing out more about how for example [with toolbar](http://react.carbondesignsystem.com/?knob-Label%20in%20the%201st%20item%20%28labelTwo%29=Estimate%20Monthly%20Cost&knob-Dropdown%20menu%20label%20%28ariaLabel%20in%20%3CDropdown%3E%29=dropdown%20menu%20label&knob-Label%20in%20the%201st%20item%20%28labelOne%29=Need%20Help%3F&knob-Tab%20index%20%28tabIndex%20in%20%3CDropdown%3E%29=-1&knob-The%20title%20%28title%29=Section%201%20title&knob-Link%20%28href%20in%20%3CDropdownItem%3E%29=&knob-The%20initial%20trigger%20text%20%28defaultText%20in%20%3CDropdown%3E%29=Dropdown%20label&knob-Selected%20text%20%28selectedText%20in%20%3CDropdown%3E%29=&knob-Label%20in%20the%201st%20item%20%28linkTextTwo%29=Cost%20Calculator&knob-Link%20href%20in%20the%201st%20item%20%28linkHrefOne%29=www.google.com&knob-Dropdown%20type%20%28type%29=default&knob-CSS%20class%20name%20%28className%29=some-class&knob-Trigger%20icon%20description%20%28iconDescription%20in%20%3CDropdown%3E%29=&knob-Selected%20value%20%28value%20in%20%3CDropdown%3E%29=&knob-Link%20href%20in%20the%202nd%20item%20%28linkHrefTwo%29=www.google.com&knob-Link%20text%20in%20the%201st%20item%20%28linkTextOne%29=Contact%20Bluemix%20Sales&knob-Label%20%28label%29=Label&knob-Footer%20text=&knob-Button%20text%20%28buttonText%29=Create&selectedKind=DataTable&selectedStory=with%20toolbar&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) doesn't show the Story Source that has the toolbar or search bar. Shouldn't the Story source for that look like the render from the story [here](https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/stories/with-toolbar.js#L20)

All i see in the story source is below (when I expect to see whats in the link above). Is this normal?

```
<DataTable rows={[{
      id: 'a',
      name: 'Load Balancer 3',
      protocol: 'HTTP',
      …
    },{
      id: 'b',
      name: 'Load Balancer 1',
      protocol: 'HTTP',
      …
    },{
      id: 'c',
      name: 'Load Balancer 2',
      protocol: 'HTTP',
      …
    }]} headers={[
    {key: 'name',header: 'Name'},
    {key: 'protocol',header: 'Protocol'},
    {key: 'port',header: 'Port'},
    …
  ]} render={render} />
```

**Comment by asudoh** [comment]
I see that @alohr51 - I was referring to `render={render}` thing at the bottom BTW where I guess Storybook cannot show the function implementation as a prop value. Given the only difference is such obfuscated function, every sub-story looked the same?

**Comment by joshblack** [comment]
Yupp! I think @asudoh nailed it. Unfortunately with the DataTable stories, most of the implementation details are in the `render` method. Storybook isn't able to bring out that method, and instead only prints the name. 

You can always search for the stories using this feature of GitHub: https://github.com/IBM/carbon-components-react/find/master specifically searching for `DataTable/stories` which will show you all the files that contain the story source 👍 

Going to close this for now, hope this helps!

**Comment by alohr51** [comment]
@asudoh yes each sub-story looked the same, so it was confusing when I was copying the code from the toolbar story and didn't see the toolbar in my own application.

Is this a limitation of StoryBook? I feel like others might go down the same confusing path as I did and won't know about https://github.com/IBM/carbon-components-react/find/master

**Comment by alohr51** [comment]
Here is an example of what I mean, screen shots usually help

DataTable with sorting

![image](https://user-images.githubusercontent.com/3623618/45434948-81398d80-b67d-11e8-9f60-d23f07bcb3fc.png)

DataTable with toolbar

![image](https://user-images.githubusercontent.com/3623618/45435012-a7f7c400-b67d-11e8-8615-aa2bc16b6016.png)


as you can see they look the exact same even though one has the toolbar and one doesn't

**Comment by joshblack** [comment]
Correct, this is intended. The only difference between the stories is the `render` method. Unfortunately Storybook doesn't embed the method directly.
