### ISSUE TITLE
DatePicker with calendar - cannot customize calendar icon title

### ISSUE THREAD

**Issue by dzaqb** [IBM/carbon-components-react#1288]
DatePicker component - type single - contains the calendar icon. This icon displays a message on hover. The message is: "Provide a description that will be used as the title".
There is no prop to override this generic message. 

I think  this message should be removed or there should be a prop which allows to configure it.

**Comment by alisonjoseph** [comment]
Hi @dzaqb I agree we should pass the prop down to the icon component. Thanks for pointing this out

**Comment by lekterable** [comment]
Hey, @alisonjoseph mind if I'll work on PR for this one?
