### ISSUE TITLE
DatePicker - calendar icon displayed too low when no labelText 

### ISSUE THREAD

**Issue by dzaqb** [IBM/carbon-components-react#1289]
DatePicker displays calendar icon below a date field when DatePickerInput labelText prop is empty. 
I cannot set labelText because it is displayed above the date field while I need it in another place. 
In such case, the calendar icon position is calculated based on some absolute position which doesn't take into account that there is no label above. 

![image](https://user-images.githubusercontent.com/43142933/45305328-54209a00-b51a-11e8-96cb-45a905a76be6.png)

**Comment by tw15egan** [comment]
Seems like `bx--date-picker--nolabel` class needs to be ported over, as we support a no-label version in the vanilla repo

**Comment by lekterable** [comment]
Thanks @tw15egan for the investigation, I'd love to open a PR for that.

**Comment by tw15egan** [comment]
Thanks for taking the time to fix this, @lekterable!
