### ISSUE TITLE
Carbon component react has List view component ? Is there any support for ListView ?

### ISSUE THREAD

**Issue by saguaaru** [IBM/carbon-components-react#1303]

**Comment by saguaaru** [comment]
Hi Asudoh,
Please find the screenshot for your reference.
![shot2](https://user-images.githubusercontent.com/42992646/45406314-c3fe6400-b683-11e8-8273-3f0ee6902a7a.PNG)
I need to add List view in react component.

**Comment by asudoh** [comment]
The closest seems [`<RadioTile>`](http://react.carbondesignsystem.com/?selectedKind=Tile&selectedStory=Selectable) or [`<StructuredList>`](http://react.carbondesignsystem.com/?selectedKind=StructuredList&selectedStory=Selection). If you have more detailed use case (e.g. what kind of feature in what application), our designers may provide a better suggestion. Hope it helps!

**Comment by saguaaru** [comment]
I am using TileGroup with RadioTitle component. Now my demo sample like this.
![snap3](https://user-images.githubusercontent.com/42992646/45409599-47708300-b68d-11e8-9bc6-a3944894da33.PNG)
I have below warning message and how to resolve this.
![snap4](https://user-images.githubusercontent.com/42992646/45409687-83a3e380-b68d-11e8-898d-32c2bef7c890.PNG)
Please refer my code for your reference.
![snap5](https://user-images.githubusercontent.com/42992646/45409757-b352eb80-b68d-11e8-81ca-bb4e73406c4a.PNG)

I want if we click the item the modal window will be open. That window contains list item details.
Please share your suggestion on this.
Thanks in advance.

**Comment by asudoh** [comment]
The console warning seems the same one as #1300. As shown in your screenshot of code, you can use `onChange()` to detect click (new selection) on the tile item. Hope it helps!

**Comment by joshblack** [comment]
Hi @saguaaru! Going to close this for now since it seems like this is a support question at this point. Feel free to reach out in our #carbon-react channel on Slack, or if we have an issue feel free to comment here and we can re-open 😄 Cheers!
