### ISSUE TITLE
[DatePicker]: TypeError on (simulated) mobile device

### ISSUE THREAD

**Issue by EEP-Benny** [IBM/carbon-components-react#1305]
## Description
The DatePicker component produces a Type Error (property access on `undefined`), if Flatpickr detects a mobile device.
![image](https://user-images.githubusercontent.com/9270901/45432479-3d10b200-b6aa-11e8-84aa-fe5133797815.png)

## Steps to reproduce the issue
_Tested in Firefox 60 ESR and Chrome 68/69_
1. [Open the DatePicker in the storybook.](http://react.carbondesignsystem.com/?selectedKind=DatePicker&selectedStory=single%20with%20calendar)
2. Open the Console (`Ctrl+Shift+K` in Firefox, `Ctrl+Shift+I` in Chrome)
3. Simulate a mobile device by hitting `Ctrl+Shift+M` and selecting a predefined device (i.e. Samsung Galaxy S5)
4. Reload the page

After some seconds, an error message appears in the console `TypeError: Cannot read property 'classList' of undefined`, pointing to [this line](https://github.com/IBM/carbon-components-react/blob/1b77b83091966252446b7a000f60dc63fa76fdf8/src/components/DatePicker/DatePicker.js#L330).

In development mode, the error message would appear on the page itself.

## Cause
https://flatpickr.js.org/mobile-support/ writes:
> When flatpickr detects a mobile browser, it turns the date input into a native date/time/datetime input.

This means: There are no additional HTML elements, so `calendar.calendarContainer` remains `undefined`. When Carbon tries to apply its custom classes to this container (in [`updateClassNames`](https://github.com/IBM/carbon-components-react/blob/1b77b83091966252446b7a000f60dc63fa76fdf8/src/components/DatePicker/DatePicker.js#L327)), the mentioned error occurs.

## Possible fixes
Either disable the mobile support of Flatpickr completely, [as mentioned in its docs](https://flatpickr.js.org/mobile-support/).
Or check if the `calendarContainer` exists before setting classes on it.

If it helps, I could submit a PR for either of the two fixes.

**Comment by asudoh** [comment]
Thanks you for writing this up @EEP-Benny especially with some investigations! Given our nature of usage of custom `<input>`, I think your former proposal would better work, but the latter is good, too, as long as it works.

**Comment by EEP-Benny** [comment]
I'm looking into it.

Has anyone an idea how to write a test case for "doesn't break on mobile"?
[FlatPickr looks at `navigator.userAgent` to determine whether it runs on a mobile](https://github.com/flatpickr/flatpickr/blob/03e00773175d497e611379613319e1a7764df9d2/src/index.ts#L1933), so I think I should somehow set this property in the test. But how?
