### ISSUE TITLE
Multiselect items documentation lacks label properties

### ISSUE THREAD

**Issue by LongBu** [IBM/carbon-components-react#1312]
## Summary
MultiSelect items attribute documentation lacks label field
## Relevant information
See link:
http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-UI%20type%20%28Only%20for%20%60%3CMultiSelect%3E%60%29%20%28type%29=default&knob-Label%20%28label%29=MultiSelect%20Label&knob-Form%20validation%20UI%20content%20%28invalidText%29=Invalid%20Selection&selectedKind=MultiSelect&selectedStory=with%20initial%20selected%20items&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

If the variable array provided to the items attribute lacks a label property, the component fails.  Shouldn't this be refelected in the documentation? 
items={[{id: 'item-1',text: 'Item 1', label: 'Item 1'},{id: 'item-2',text: 'Item 2', label: 'Item 2'}]}
instead of:
items={[{id: 'item-1',text: 'Item 1'},{id: 'item-2',text: 'Item 2'}]}

**Comment by joshblack** [comment]
Hi @LongBu! 👋 The goal of the storybook story here is to show that you can have items in your array without a `label` field, as long as you provide the `itemToString` method that properly maps them.

Definitely agreed that this could be better documented! Would gladly accept your PR if you want to add it in 😄

**Comment by aroduribe** [comment]
@joshblack what's a better way of documenting this? I would love to do a PR for this issue.
