### ISSUE TITLE
An extensible <Skeleton /> component

### ISSUE THREAD

**Issue by ryanomackey** [IBM/carbon-components-react#1313]
### Summary

It'd be nice to have a generic `<Skeleton />` component. Something that you could just feed a height and width, and then get a 'loading' element in those dimensions. 

### Justification

This would be useful in cases where another skeleton component might not apply. For instance, an image where I happen to know the dimensions I need ahead of time.

### Desired UX and success metrics

TBD

### "Must have" functionality

An example implementation might look like:

```
<Skeleton height="300px" width="300px" />
```
### Specific timeline issues / requests

None whatsoever.

### Available extra resources

Me?

**Comment by joshblack** [comment]
Hi @ryanomackey! 👋 Definitely agreed. This will be even more important with React v17 when we want to have components display a skeleton by default after a set duration.

I'm definitely down with adding more utility components into the core library, how does the rest of the team feel @IBM/carbon-developers?

**Comment by alisonjoseph** [comment]
This should be a fairly simple addition. You would have to add to the `carbon-components` library first for the styles. There is a skeleton mixin that could be used.
