### ISSUE TITLE
DatePicker with range min and max dates set incorrectly only on IE11

### ISSUE THREAD

**Issue by austinbruch** [IBM/carbon-components-react#1325]
## Detailed description
> Describe in detail the issue you're having.

When using the `DatePicker` component with the `datePickerType` prop set as `range`, the `dateFormat` prop set as `m/d/Y`, and supplying both `maxDate` and `minDate` props as strings (both in a format following `06/16/2018`), I am seeing incorrect max and min dates on the calendar popup, only on IE11. 

For example, if I set `maxDate` to `"09/14/2018"` and `minDate` to `"06/16/2018"`, in Chrome I see this:

Max:
![image](https://user-images.githubusercontent.com/3361835/45572117-65c5b280-b836-11e8-952a-dc733cb57cf0.png)

Min:
![image](https://user-images.githubusercontent.com/3361835/45572140-7544fb80-b836-11e8-9954-599180c6a65d.png)

However, in IE, I see this:

Max: 
![image](https://user-images.githubusercontent.com/3361835/45572177-91e13380-b836-11e8-9df8-fcf64a2c542c.png)

Min:
![image](https://user-images.githubusercontent.com/3361835/45572187-9ad20500-b836-11e8-9a55-48f5d5d78a2f.png)

As the screenshots show, the max is set to September 8, and the min is set to June 8, when they should be September 14 and June 16 respectively.

Debugging the code in the browser shows that flatpickr [builds a regex](https://github.com/flatpickr/flatpickr/blob/master/src/utils/dates.ts#L81-L111) to parse the min and max date values according to the specified `dateFormat` prop. As far as I can tell, the regex is correct, but for some reason, is giving unexpected results. For example, it appears that the "8" in both of the min and max dates comes from the "8" in "2018".

This might need to be an issue opened up in that repo, but I figured I'd start here w/Carbon first.

> Is this issue related to a specific component?

Yes, `DatePicker`

> What did you expect to happen? What happened instead? What would you like to see changed?

See above description.

> What browser are you working in?

This issue is seen in IE11, running on Windows 10.

> What version of the Carbon Design System are you using?

carbon-components-react: 6.8.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Identity.
This issue is seen in code that needs to go out by the end of the month.

## Steps to reproduce the issue
Instantiate a DatePicker instance as described above. Open the picker in IE11.

> Please create a reduced test case in code sandbox

DM me for credentials to a test system where this can be demonstrated

**Comment by alisonjoseph** [comment]
Can you recreate in a code sandbox? I did a quick check on our storybook in IE11 and the min/max appears to be rendering correctly. http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&selectedKind=DatePicker&selectedStory=range%20with%20calendar%20and%20min%2Fmax%20dates&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by austinbruch** [comment]
@alisonjoseph I've recreated it here: https://codesandbox.io/s/4xxwx20kz4. Note that I was not able to get this page to load in IE (probably some kind of transpile or polyfill issue), but it does load in Edge, and the same issue is happening in Edge.

**Comment by alisonjoseph** [comment]
@asudoh do you have any ideas on this? It seems that writing the dates in how we do in our storybook seems to work, but his above code does not.

**Comment by asudoh** [comment]
Hi @austinbruch IE's `Date.toLocaleString()` includes left-to-right marks in it (`U+200E`), which Flatpickr cannot parse. When I replaced that with `${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}` the problem seems gone away. Hope it helps - Feel free to speak up otherwise. Thanks!

**Comment by austinbruch** [comment]
Thanks @asudoh, I was unaware of the LTR characters from IE (and apparently Edge). With this information, I can work avoid running into this issue.
