### ISSUE TITLE
Accordion component throwing errors in sandbox

### ISSUE THREAD

**Issue by elarue3824** [IBM/carbon-components-react#1330]
## Detailed description

I am attempting to recreate an issue using codesandbox with an accordion component to demonstrate in an issue.  However, when I implement the accordion component in the code, I get the following errors:

In Firefox: "A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information."

In Chrome: "Cannot read property 'open' of null"

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/zk185zwml

**Comment by tw15egan** [comment]
Not too sure why, but loading the newest version of the components in the Sandbox gets it to render for me

**Comment by elarue3824** [comment]
What is the newest version, and how do I load them in the sandbox? (Noob question, I know. ;-) )
