### ISSUE TITLE
Expanded accordion hidden when at the bottom of the page

### ISSUE THREAD

**Issue by elarue3824** [IBM/carbon-components-react#1333]
## Detailed description

When using an Accordion component at the bottom of our React application, it is squished against the bottom of the page, and when it is opened, it does not automatically scroll to make room for the inner elements.  One has to manually scroll to access these elements.

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/zk185zwml

<img width="1552" alt="screen shot 2018-09-18 at 3 08 41 pm" src="https://user-images.githubusercontent.com/42156684/45713488-d3365380-bb54-11e8-88bc-f3bf4b72a650.png">
<img width="1552" alt="screen shot 2018-09-18 at 3 08 50 pm" src="https://user-images.githubusercontent.com/42156684/45713489-d3365380-bb54-11e8-8d3e-29da103d003a.png">

**Comment by asudoh** [comment]
@elarue3824 Given automatic scroll-into-view behavior often is intrusive for applications - Do you want to try hooking `onClick()` of `<AccordionItem>` and call [`.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) of a DOM element in your accordion content? Thanks!

**Comment by elarue3824** [comment]
@asudoh - I have tried this method, but it does not produce the desired behavior. I don't know if it's because I'm implementing it wrong or it just won't work with this component.

**Comment by asudoh** [comment]
@elarue3824 Couldn't find `.scrollIntoView()` in https://codesandbox.io/s/zk185zwml - Did you mean another link?

**Comment by elarue3824** [comment]
No, I meant that link. But when I clicked on it, the code changes I made weren't there. I tried re-adding them and re-saving them.

**Comment by asudoh** [comment]
OK let us know once you finish creating the reproducible case - Thanks!

**Comment by elarue3824** [comment]
I already did.

**Comment by asudoh** [comment]
Did you mean one with `scrollIntoView()`?

**Comment by elarue3824** [comment]
Yes.  Is it still not there?

**Comment by asudoh** [comment]
Hmm... Couldn't still see `.scrollIntoView()` call in https://codesandbox.io/s/zk185zwml. Wondering if I'm missing something or there are some sort of miscommunications.

**Comment by elarue3824** [comment]
It's not a miscommunication.  It's that my code changes where I add that function are not getting saved.  I don't understand why that is.

**Comment by asudoh** [comment]
I see. You can download the CodeSandbox content and make edits locally. Once it completes, you can zip it up and put it here. Thanks!

**Comment by amortiz** [comment]
I believe this was solved when the design for the page changed and no longer see the issue with this new design. @asudoh you may close this ticket
