### ISSUE TITLE
Unexpected behavior in keyboard navigation in FileUploaderButton

### ISSUE THREAD

**Issue by ColbyJohnIBM** [IBM/carbon-components-react#1334]
## Detailed description

> Describe in detail the issue you're having.

When using keyboard navigation, the FileUploaderButton gets focus twice.

> Is this issue related to a specific component?

Yes, FileUploaderButton.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

6.28.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Compare & Comply Tooling UI, no extremely pressing deadline

## Steps to reproduce the issue
1. Navigate to the FileUploaderButton Storybook story. (http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-Button%20kind%20%28buttonKind%29=&knob-Label%20text%20%28labelText%29=Add%20files&knob-Form%20item%20name%3A%20%28name%29=&knob-Supports%20multiple%20files%20%28multiple%29=true&knob-ARIA%20role%20of%20the%20button%20%28role%29=&knob-Tab%20index%20%28tabIndex%29=-1&selectedKind=FileUploader&selectedStory=FileUploaderButton&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
2. Press "tab" key. Note that element `div.bx--file.bob` receives focus. Note that pressing enter pulls up the file upload dialog box. (This is all expected.)
3. Press "tab" key again. Note that element `label.bx--btn.bx--btn--primary` receives focus. (Not expected, as this essentially focuses on the same button.) Note that pressing enter pulls up the file upload dialog box. Regardless of what is done in that dialog box, no action is logged. Note that a second dialog box then opens, which then behaves normally.

**Comment by joshblack** [comment]
Re-opening due to feedback above ^

**Comment by joshblack** [comment]
When is the `label` receiving focus? Having a hard time seeing where that happens.

We definitely want to maintain the initial focus target as the button, currently a `div` but ideally we'd have it be a native `button`.

A strategy here might be to have a node inside of the `div` for describing it and we can add `aria-labelledby` on the outermost div to update it's label when the content changes (e.g. a file is uploaded).

**Comment by emyarod** [comment]
the label receiving focus was due to me modifying the storybook knobs in my browser, my mistake.

but I've moved the button styles off of the `label` and placed it on the wrapper `div` instead. I've also set the value of the `label`'s `tabIndex` to `null` if the prop value is falsy so that it won't be focusable
