### ISSUE TITLE
Got errors when pavigating the pages after clicking the tooltip in one page.

### ISSUE THREAD

**Issue by lukewang2018** [IBM/carbon-components-react#1336]
## Detailed description

> Describe in detail the issue you're having.

When we load the page with tooltip, it's showing errors as below: 
`Warning: Tooltip: Did not properly initialize state during construction. Expected state to be an object, but it was undefined.`

After we click the tooltip in page A, and navigate to another page B, it will show errors as below.  This error only occurs for your first try after you refresh the page with tooltip. If you test it again without refreshing, you cannot get the errors again.

`Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

See steps below.

> Is this issue related to a specific component?
carbon component: Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?
Need to fix these errors related to Tooltip.

> What browser are you working in?
Chrome 68.0.3440

> What version of the Carbon Design System are you using?

    "carbon-components": "^9.5.0",
    "carbon-components-react": "6.21.4",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Will deliver in early Oct.

## Steps to reproduce the issue

1. Access one trigger node with a tooltip, it will show the tooltip
2. Click the trigger node
3. Click any other link in the page A, and enter into another page b
4. Check the errors in browser console. It will show the errors above.

**Note: This error only occurs for your first try after you refresh the page with tooltip. If you test it again without refreshing, you cannot get the errors again.** 

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

* Screenshots or code
* Notes

![snip20180919_97](https://user-images.githubusercontent.com/40848250/45760671-3ad7c600-bc5d-11e8-9278-f5667cad7075.png)
![snip20180919_96](https://user-images.githubusercontent.com/40848250/45760673-3ad7c600-bc5d-11e8-8df4-f6c8098a0835.png)
![snip20180919_95](https://user-images.githubusercontent.com/40848250/45760674-3b705c80-bc5d-11e8-8358-77249daeced4.png)

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Looking at https://codesandbox.io/s/r4zxq9pvq, but only seeing a button - Did you overwrite the CodeSandbox or did you mean a different link by any chance?

**Comment by lukewang2018** [comment]
@asudoh thanks for your reply. 

The link is the default link in issue template.  :-)  I just tried to update https://codesandbox.io/s/r4zxq9pvq with below code, while I got the error "TypeError
Cannot read property 'open' of null". 
If I degrade the version of carbon-components-react from 6.21.4 to 5.34, it will be ok to show the tooltip. btw, we are using 6.21.4 in project.


https://codesandbox.io/s/7yzzmwlxwj
```
  <div>
    <Tooltip triggerText={'test tooltip'}>
      <p>This is some content.</p>
    </Tooltip>
  </div>
```

**Comment by asudoh** [comment]
@lukewang2018 Thanks - I see your CodeSandbox has older version of React, which latest version of `carbon-components-react` does not support. Once I changed the CodeSandbox with latest versions of `react` and `react-dom`, it seems to work fine. Hope this helps!

**Comment by lukewang2018** [comment]
thanks @asudoh yes. it's ok to show the tooltip after upgrading the version of react and react-dom. I cannot reproduce the errors in codesandbox right now.

**Comment by asudoh** [comment]
@lukewang2018 Great to hear that things work well now!

**Comment by lukewang2018** [comment]
@asudoh  sorry for the misunderstanding.  I'm not able to reproduce it in codesandbox, while it still exists in our project.

**Comment by asudoh** [comment]
I see @lukewang2018 - Let us know if you can successfully create a reduced case. Thanks!
