### ISSUE TITLE
Feature flags (React)

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#1339]
### Summary

This issue for introducing feature flag system, that has been introduced in vanilla repo recently, to this React repo.

### Justification

Provide the business reasons for this request.

### Desired UX and success metrics

A way to conditionally turn on/off specific set of features, without causing any additional (size) cost to the built version.

### "Must have" functionality

1. A way to build Storybook Sass code with different feature flags
2. Build-time flags, processed by [Webpack DefinePlugin](https://webpack.js.org/plugins/define-plugin/) or [`rollup-plugin-replace`](https://github.com/rollup/rollup-plugin-replace)

### Specific timeline issues / requests

For Q3 new theme ffort.

**Comment by joshblack** [comment]
Could be interesting to explore how React does feature flags: https://github.com/facebook/react/blob/master/packages/shared/ReactFeatureFlags.js https://github.com/facebook/react/search?q=ReactFeatureFlags&unscoped_q=ReactFeatureFlags

I think the high-level summary is that they export a module that can have flags in it be re-written that they then import the flag names in modules and toggle based on their value
