### ISSUE TITLE
Icon component "description" property should not be required

### ISSUE THREAD

**Issue by ColbyJohnIBM** [IBM/carbon-components-react#1345]
### Summary

The `Icon` component requires the description property, and uses a default value if none is given, using the property for an `aria-label` and `alt` attributes and also as the text of a `title` element. I would like to request that the Icon component not require this property and that it only populate the other fields if a `description` is given. This will allow the `Icon` component to be used in ways that do not involve direct user interaction.

### Justification

Our product uses the `Icon` component, and we have run into situations where the fields that this component fills in with the default are not useful to us. (E.g. when we're using an Icon as a purely presentational component or when we're using tooltips in place of `title` attributes)

**Comment by ColbyJohnIBM** [comment]
The `title` attribute is the part that's really giving us trouble in particular, because we don't want text to appear in that way on hover (since we already have a tooltip on hover). If you want `description` as required and keep the `aria-label` and `alt` attributes, that should work for us.

**Comment by asudoh** [comment]
Thank you for providing us with more details @ColbyJohnIBM! We can introduce `title` prop to `<Icon>` where you can set `null` or an empty string to remove the SVG `<title>`. Wondering if it will make sense to you.

**Comment by ColbyJohnIBM** [comment]
I think that makes sense and should work for our needs.

**Comment by asudoh** [comment]
Figured out that there is we have #726, associated with a PR with the code exactly like what I imagined (#1319). Closing, but don't hesitate to speak up in case #1319 wasn't what you wanted. Thanks!
