### ISSUE TITLE
Improperly initializing state during construction

### ISSUE THREAD

**Issue by miniwangdali** [IBM/carbon-components-react#1365]
## Detailed description
I have seen `Warning: AccordionItem: Did not properly initialize state during construction. Expected state to be an object, but it was undefined.` triggered in multiple different components, such as `AccordionItem`, `RadioButtonGroup` and `NumberInput`.
Do you know why this happens?

Also, I cannot reproduce it since when using `6.28.0`, it cannot render at all since some other states that need to read from the component state but the state is null.

## Additional information
version `6.28.0`

**Comment by asudoh** [comment]
Should be addressed by #1255 - Feel free to speak up otherwise!
