### ISSUE TITLE
Storybook fails to run due to Babel error

### ISSUE THREAD

**Issue by AndySeymour2904** [IBM/carbon-components-react#1375]
Error from console;
ERROR in ./.storybook/addons.js
Module build failed: Error: [BABEL] /Users/andy/Documents/Monza/carbon-components-react/.storybook/addons.js: 
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

**Comment by joshblack** [comment]
Hi @AndySeymour2904! 👋 You might need to run `yarn install` to get the latest dependencies. We are no longer using the beta dependencies and instead are using the `v7` set: https://github.com/IBM/carbon-components-react/blob/master/package.json#L138

**Comment by joshblack** [comment]
Going to close this for now, feel free to comment if this isn't the case!
