### ISSUE TITLE
NumberInput component not compatible on Bluemix CLoud-UI Starter project for catalog. 

### ISSUE THREAD

**Issue by vidhi11** [IBM/carbon-components-react#1386]
## Detailed description

> Describe in detail the issue you're having.
- We are creating Marketplace UI for NFV team and are using Bluemix cloud-ui starter kit https://github.ibm.com/Bluemix/cloud-ui-starter. We are using carbon-components-react and are facing issue with `NumberInput` component. We see double repeated arrows on all browsers. I have tested it personally, where this component works perfectly on sandbox/any react project, but does not support cloud-ui starter project. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
- Bug

> Is this issue related to a specific component?
- Yes, related to `NumberInput` component.  

> What did you expect to happen? What happened instead? What would you like to see changed?
- Using `NumberInput` component, i should see `up&down` arrows only one time, but its repeated. 

> What browser are you working in?
- Mozilla, Chrome and Safari.

> What version of the Carbon Design System are you using?
- Using `5.19.1` but even tried updating to `^6`, its still same.  

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
- On craeting Marketplace UI for VNF-F5 by NFV team. Yes we have deadline of 30th Sept. 
 
## Steps to reproduce the issue
- Cannot reproduce issue on sandbox for cloud-ui starter project. Shared screenshot of bug. 

## Additional information

* Screenshots or code
Mozilla Browser: 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/32270454/46355245-0df4bd00-c626-11e8-9f7a-4efffe49e45e.png">

Chrome Browser: 
<img width="632" alt="image" src="https://user-images.githubusercontent.com/32270454/46355286-25cc4100-c626-11e8-8b47-27dfe3f4dd63.png">

Safari Browser:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/32270454/46355344-41cfe280-c626-11e8-85ab-2bf8fef59579.png">

* Notes

**Comment by tw15egan** [comment]
Using an autoprefixer to compile your `scss` should solve this problem

**Comment by vidhi11** [comment]
@tw15egan I'm very new to reactjs. Please help me understand how i can use autoprefixer to compile scss. Some guide / material will be helpful. 
Thankyou.

**Comment by tw15egan** [comment]
You'll need to use a specific webpack loader to handle it: https://github.com/postcss/autoprefixer#webpack

**Comment by vidhi11** [comment]
@tw15egan Thank-you. It fixed the double arrow issue.
