### ISSUE TITLE
ContentSwitcher not taking state passed to it, instead uses its own state

### ISSUE THREAD

**Issue by ashpc** [IBM/carbon-components-react#1394]
## Detailed description
ContentSwitcher doesn't  select the correct Switch component when the correct selected and selectedIndex props are passed.

> Describe in detail the issue you're having.
We are using ContentSwitcher with props selectedIndex and Switch with props selected, the components states are not selecting the right Switch even though the correct content is displayed.

> Is this issue related to a specific component?
ContentSwitcher and Switch

> What did you expect to happen? What happened instead? What would you like to see changed?
When I pass selected value to Switch it should honor it and select the right switch element. Instead the component has its own state and the content doesn't match the Switch component selected.

Since our code is using redux it is not picking the redux state props that is passed to it, instead it is using its own state.

> What browser are you working in?
All

> What version of the Carbon Design System are you using?
  "carbon-addons-beta-react": "1.4.2",
    "carbon-addons-cloud": "2.1.0",
    "carbon-addons-cloud-react": "1.2.0",
    "carbon-components": "9.1.20",
    "carbon-components-react": "6.14.2",
    "carbon-icons": "7.0.7",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Nov release

## Steps to reproduce the issue
1. Pass selectedIndex as 1 for the ContentSwitcher
2. Pass same to Switch component
3. Don't unmount, but go to another tab ro component in that same page 
When you go back to the ContentSwitcher, I expect the 2nd panel to be selected and right content to be displayed.

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! #992 should have addressed the problem. Let us know otherwise!
