### ISSUE TITLE
DataTable with TableToolbarSearch and PaginationV2 not working as expected

### ISSUE THREAD

**Issue by alohr51** [IBM/carbon-components-react#1396]
## Detailed description

When using Pagination and TableToolbarSearch the search only filters on what is shown on the current page. I would expect the TableToolbarSearch to search through all rows available. 

**It is possible the way I am doing this is incorrect too**. I am making a subset of the total items (depending on what pagination tells me to show) and putting that subset as the rows in the table. It seems like the right way to do it, but maybe there is a better way. 

So it makes sense why the search cannot show the items, but its not what I would expect.

> Is this issue related to a specific component?

DataTable, TableToolbarSearch, and PaginationV2

> What browser are you working in?

Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

    "carbon-components": "9.26.0",
    "carbon-components-react": "6.36.1",

## Steps to reproduce the issue

You can see with the below sandbox example I created, but any simple example with the 3 components will work too.

1.  load enough data for there to be at least 2 pages of unique enough data
1.  go to page 1
1.  search for a row on page 2 and no rows will show up. I would expect search to search all rows regardless of page #

> Please create a reduced test case in code sandbox

Example in sandbox https://codesandbox.io/s/z3n54ml4n4

## Additional information

In the below screen shot I would expect the row with ID 3 to show up. But since It wasn't rendered in the table (not part of the pagination subset) it did not.
![image](https://user-images.githubusercontent.com/3623618/46499894-61fecd80-c7ef-11e8-9ea1-014844fd9835.png)

A thought might be to have someway to give DataTable all the rows, but only be able to show what you want to show (like a pagination subset of rows) this way, the search filter will have all the data needed to do a search.

**Comment by colingm** [comment]
I have dealt with this and the problem seems to be that DataTable does not have first class support for pagination. The default sorting and searching only operate on the list of rows given to the table but since when you use pagination you break up the list yourself it doesn't search over them. You can get around this by implementing your own search and sort functions and passing those to the data table to use.

**Comment by alohr51** [comment]
@colingm thanks for the response. I wanted to make sure this was the way to go before writing the code to do that.

**Comment by tw15egan** [comment]
Closing as this particular seems to be resolved, and the code will need to be implemented on the user end. Feel free to re-open if needed

**Comment by alohr51** [comment]
@colingm I tried doing a custom search, but hit a snag. Maybe you could help. 

I passed in the custom search function as a `filterRows` prop to the DataTable like this:

`<DataTable rows={this.state.resourcesSubset} headers={this.getHeaders()} filterRows={this.defaultFilterRows}`

I then used the default filterRows code (from [Here](https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/tools/filter.js)) as an example to get started. I noticed it looks like it wants an array of row IDs that match the search coming in.

If I continue to only pass in a subset of the data (for pagination) and search my whole data set the filterRows function most likely will return Ids that are not in the subset the DataTable knows about, which means it throws the error `Uncaught TypeError: Cannot read property 'cells' of undefined
`

Am I missing something here? Seems like I would have to pass the whole data set to DataTable for the search to work, but then pagination won't work.

**Comment by alohr51** [comment]
I also tried setting the subset of data passed into the DataTable to my search results, but I have to return a `[]` empty array for the `filterRows` function otherwise it tries to do a `map` on undefined and fails. This approach results in an empty DataTable.

**Comment by alohr51** [comment]
Okay I figured out a solution. I'll write out a little explanation in case it helps someone in the future,

I was trying to make the default `filterRows` function on the DataTable work with pagination, but I should have been using the `onChange` prop on the `TableToolbarSearch`

For example, `<TableToolbarSearch onChange={this.filterRows}/>` and then do my filtering on all my data and change the subset to the filtered results.

The second thing was also being able to paginate using the filtered results so after I change the pagination subset to filtered results I also needed to take another subset of the filtered results (if the result set was larger than my pagination page size).

**Comment by colingm** [comment]
Yeah that works great or you can also have your filter rows function look at the pagination information too, both should be fine. In light of this though it definitely isn't an ideal solution and brings up the fact that pagination should definitely be a first class citizen of the data table.
