### ISSUE TITLE
Data table not supporting "short" style?

### ISSUE THREAD

**Issue by tw15egan** [IBM/carbon-components-react#1408]
@mlinnem commented on [Mon Oct 08 2018](https://github.com/IBM/carbon-components/issues/1223)

Data table component doesn't seem to support the "short" style. We use React so it might be specific to that. This is reported by a dev on our team (Justin Pomeroy) so I would follow up with him for any further clarification.

---

@tw15egan commented on [Mon Oct 08 2018](https://github.com/IBM/carbon-components/issues/1223#issuecomment-427952137)

Do you have an example of the `short` style? Not sure what that means

---

@mlinnem commented on [Tue Oct 09 2018](https://github.com/IBM/carbon-components/issues/1223#issuecomment-428272424)

Here's a reference to the style on the website:
<img width="800" alt="screen shot 2018-10-09 at 12 05 14 pm" src="https://user-images.githubusercontent.com/1547834/46685653-9c83b400-cbbb-11e8-9811-3f4a412eb0e7.png">

Here's the style in the kit:
<img width="1426" alt="screen shot 2018-10-09 at 12 04 57 pm" src="https://user-images.githubusercontent.com/1547834/46685672-a3aac200-cbbb-11e8-8dd0-b0dfd298747f.png">

**Comment by tw15egan** [comment]
Need to add `short` version of data-table to React component

**Comment by mohinderps** [comment]
From where do I take the reference for the short table?

**Comment by mohinderps** [comment]
Will 'short' be a props to the DataTable ?

**Comment by mohinderps** [comment]
If we accept the 'short' prop in DataTable, then to pass the prop down to Table component, We would need to write a Prop Getter function, I think. Let me know of a better approach to this.

**Comment by mohinderps** [comment]
Hey @tw15egan , I have added the PR #1434 , so that you can review it and let me know if it needs to be done in some other way.
