### ISSUE TITLE
Introduce style debugging mode in our storybook env

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#1419]
### Summary

This issue is for tracking an effort of easier debugging of styles, in our Storybook environment.

### Justification

As of today, if a developer tries to inspect a style in our Storybook environment, Chrome DevTools points to a `<style>` tag that is almost useless.

### Desired UX and success metrics

Our developer can easily inspect styles in Storybook with DOM inspector tools.

### "Must have" functionality

* Inspecting styles in Storybook yield reasonable source code, optimally in before-compile Sass code. At lease well-formatted CSS code.

**Comment by tw15egan** [comment]
This would be very helpful
