### ISSUE TITLE
Progress Indicator in Safari 5 and Safari 8

### ISSUE THREAD

**Issue by riya-naico** [IBM/carbon-components-react#1420]
Can you please tell whether the Carbon Design Progress Indicator component will render properly in Safari 8?
Currently the progress indicator not rendering properly? [http://www.carbondesignsystem.com/components/progress-indicator/code](url)

And also  Carbon design site is not loading in Safari 5 ? Could you please tell whether the Carbon components will work only in 
    IE11
    IE Edge latest
    Firefox latest
    Chrome latest
    Safari latest

**Comment by tw15egan** [comment]
We only support the latest version of Safari, which at the moment is Safari 12. Please update your browser and see if that resolves your issue. Thanks!

**Comment by riya-naico** [comment]
What about the other browsers components will work only in
IE11
IE Edge latest
Firefox latest
Chrome latest
Safari latest

**Comment by tw15egan** [comment]
Yes, that is correct. We only support the latest version of all the browsers listed

**Comment by asudoh** [comment]
One addition here is FF ESR. Basically we try to be in sync with https://console.bluemix.net/docs/overview/prereqs.html#prereqs unless other BUs have strong requirements for additional browsers.
