### ISSUE TITLE
Reference with #1420 - Browser compactability

### ISSUE THREAD

**Issue by riya-naico** [IBM/carbon-components-react#1422]
What about the other browsers? As per carbon design document components will work only in
IE11
IE Edge latest
Firefox latest
Chrome latest
Could you please confirm this also?

- #carbon-design-system for questions about the Design System
- #carbon-components for questions about component styles
- #carbon-react for questions about our React components

If these resources don't work out, help us out by filling out a couple of
details below!

-->

**Comment by tw15egan** [comment]
Answered in https://github.com/IBM/carbon-components-react/issues/1420#issuecomment-428595213
