### ISSUE TITLE
OverflowMenuItem: Invalid roles

### ISSUE THREAD

**Issue by Joseph-Hitchcock** [IBM/carbon-components-react#1424]
When using OverflowMenuItem, we're seeing the following violations in DAP:

![image](https://user-images.githubusercontent.com/40905872/46753715-728ec800-cc75-11e8-9099-4a9c77137d2e.png)

Making the following changes to the resulting HTML fixes the violations:

![image](https://user-images.githubusercontent.com/40905872/46753763-8df9d300-cc75-11e8-9660-3b5912dfe4d7.png)

**Comment by zgrossbart** [comment]
You also can see this issue on the Carbon storybook here:  http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-Menu%20direction%20%28Only%20with%20%60floatingMenu%60%29%20%28direction%29=bottom&knob-ARIA%20label%20%28ariaLabel%29=&knob-Icon%20description%20%28iconDescription%29=&selectedKind=OverflowMenu&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
