### ISSUE TITLE
Importing individual modules imports entire carbon package

### ISSUE THREAD

**Issue by mstudio** [IBM/carbon-components-react#1427]
## Detailed description

> Describe in detail the issue you're having.

Importing named components results in the entire carbon package (all components) being added to the bundle js.
**Example:**
```
import { ComboBox, Modal } from 'carbon-components-react';
```

However, if I import the package directly from its component directory in node-modules, only the relevant files are included (and the bundle size is much smaller)
**Example:**
```
import ComboBox from 'carbon-components-react/lib/components/ComboBox';
import Modal from 'carbon-components-react/lib/components/Modal';
```

> Is this issue related to a specific component?

This seems to be related to all components.

> What did you expect to happen? What happened instead? What would you like to see changed?

Only relevant components and dependencies should be added to the bundle js.

> What browser are you working in?

All

## Additional information

I'm using webpack-bundle-analyzer to look at the final bundle size:

Using 

```
import { ComboBox, Modal } from 'carbon-components-react';
```
Size: **910KB**
![image](https://user-images.githubusercontent.com/229130/46757048-fefdb280-cc96-11e8-9463-b0df954256fc.png)

Using
```
import ComboBox from 'carbon-components-react/lib/components/ComboBox';
import Modal from 'carbon-components-react/lib/components/Modal';
```
Size: **83KB**
![image](https://user-images.githubusercontent.com/229130/46757139-47b56b80-cc97-11e8-849d-8fc2a2d037e3.png)

**Comment by joshblack** [comment]
Hi @mstudio! 👋 Thanks so much for taking the time to make this issue 😄 

I'm going to reference this comment from a previous discussion: https://github.com/IBM/carbon-components-react/issues/964#issuecomment-401847400

Since I believe this is a duplicate, I'm going to close this for now. Feel free to make a new issue if you feel like that answer doesn't help solve your use-case. Cheers! 🍻
