### ISSUE TITLE
ProgressStep change label PropType to "node"

### ISSUE THREAD

**Issue by joetex** [IBM/carbon-components-react#1433]
### Summary

We want to make the ProgressStep clickable, so that we can route users to that specific step.  However, when injecting an anchor tag into the label property, the console shows a "Warning" about the PropType not being a String.
Changing the label property to have a PropType node, should fix the warning from showing.

### Justification

Allow customizing the label of ProgressStep for our customers to navigate to the correct view that belongs to the step clicked.

### Desired UX and success metrics

The label should allow injecting components or html in order to allow custom functionality like clicking the Step label to navigate.

### "Must have" functionality

Must have possibility to inject component/html into the label property.

### Specific timeline issues / requests

As soon as possible

### Available extra resources

n/a

**Comment by matheushrt** [comment]
I'm taking this one.
