### ISSUE TITLE
Button inside TooltipIcon is not clickable on FF

### ISSUE THREAD

**Issue by tymekg** [IBM/carbon-components-react#1440]
## Detailed description
> Describe in detail the issue you're having.

The code like this:
```
<TooltipIcon
	tooltipText="Press the button to hear a click"
>
	<Button onClick={() => {console.log("*click*!");}} small>Press me</Button>
</TooltipIcon>
```
does not work on Fiefrox. The button gets displayed, the tooltip shows up, but if I click the button `onClick` handler is not triggered.
On Chrome it executes `onClick` as expected.

> Is this issue related to a specific component?

`TooltipIcon` 
> What did you expect to happen? What happened instead? What would you like to see changed?

`onClick` handlers of `TooltipIcon`'s children should be executed when clicked, but it does not happen on Firefox.
> What browser are you working in?

Firefox Quantum 60.2.2esr on Windows
> What version of the Carbon Design System are you using?

```
    "carbon-components": "9.14.0",
    "carbon-components-react": "6.32.1",
```
## Steps to reproduce the issue

Use the sandbox below and compare behavior on Chrome and Firefox:
https://codesandbox.io/s/w22v9opjqw

## Additional information

There is also this warning produced:
```
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    in button (created by Button)
    in Button (created by App)
    in button (created by TooltipIcon)
    in div (created by TooltipIcon)
    in TooltipIcon (created by App)
    in div (created by App)
    in App
```

**Comment by asudoh** [comment]
@IBM/carbon-designers IIUC interactive elements in icon tooltip is not something we intend. Is it correct...? Thanks!

**Comment by tymekg** [comment]
@asudoh Please note that the tooltip text is static (i.e. "Press the button to hear a click"). It's the trigger element that I expected to behave interactively (a Button in this case).

**Comment by asudoh** [comment]
I see, wondering why do you want to put `<Button>` there - Probably you want your `onClick` handler run there? If so, have you tried `<TooltipIcon onClick={yourOnClick}>`?

**Comment by tymekg** [comment]
Well, I just want to have a button with a tooltip to hint users. I thought this is quite common scenario, isn't it?
Anyway, I've tried moving `onClick` handler from `Button` to `TooltipIcon` and now it works indeed. :+1: 
Is that the recommended way?

I have another case with `OverflowMenu` . If wrapped in a `TooltipIcon` it does not respond to clicking on FF. How to deal with it in such case? Below is sample code:

```
    <TooltipIcon
      tooltipText={"Open the menu"}
      showIcon={false}
    >
      <OverflowMenu flipped>{actionOptions}</OverflowMenu>
    </TooltipIcon>
```
and here is a corresponding sandbox: https://codesandbox.io/s/xrnn903k4

So the problem is, in general, with adding `TooltipIcon` to anything clickable on FF.

**Comment by asudoh** [comment]
Great that `onClick` worked! Wrt overflow menu, I don't see `<TooltipIcon>` would support overflow menu put in there. If you have particular use case that led you do that, please file another issue. Thanks!

**Comment by tymekg** [comment]
^ @asudoh I've opened a separate issue for the case with OverflowMenu, as you've asked.
