### ISSUE TITLE
Validation in Checkbox

### ISSUE THREAD

**Issue by riya-naico** [IBM/carbon-components-react#1443]
Could you please suggest how to implement validation in checkbox using carbon components in react? Couldn't find any documentation or example for checkbox validation.

Thanks

**Comment by asudoh** [comment]
Hi @riya-naico do you want to bring up your use case doing form validation with checkbox? Thought yours may fit in our regular use cases of form validation. Thanks!

**Comment by riya-naico** [comment]
Hi, while going through the carbon design system components it provides validation for input fields using the data-invalid attribute. But it is not working when used with checkbox.Can you please suggest me how to trigger the data-invalid attribute for checkbox validation or is there any other methods or attribute for the same.
And the form which designed using carbon design system is not fully working(design classes are not reflecting) in IE 11. Can you please suggest a method for this also.
Thanks!

**Comment by asudoh** [comment]
Before talking about the specifics, let me provide more details wrt where my earlier question was from. AFAIK Carbon checkbox does _not_ have form validation style/UI. IIRC somewhere in Slack conversation brought up "I agree with terms and conditions" checkbox where hitting Submit button without checking the checkbox showing form validation UI. Was it yours? If so, our designers may chime in if it's a use case Carbon ecosystem may contain.

**Comment by riya-naico** [comment]
Hii

1.How i can Provide data-invalid dynamically to Component. Data-invalid set as inactive when validation checking Success.

2.How can i fix issue in Progress indicator component when direction is RTl.

Thanks..

**Comment by asudoh** [comment]
Hi 👋

Wrt 1. is your "how to provide data-invalid dynamically to component" question adding form validation UI to checkbox, or something else?

Wrt 2. Is your issue with progress indicator relevant to what this issue originally describes?

**Comment by riya-naico** [comment]
Hii

Wrt1. I mean textbox .

Wrt2. Please Check the Attached 
![capture](https://user-images.githubusercontent.com/2970289/47199431-3f43eb80-d38f-11e8-9433-a4e527fc3f02.PNG)
 image.
