### ISSUE TITLE
How to disable FileUploaderButton?

### ISSUE THREAD

**Issue by hongcbjch** [IBM/carbon-components-react#1444]
In our case, we want to disable the FileUploaderButton in some condition. Is there a way to disable FileUploaderButton? 

<FileUploaderButton
  className="bob"
  labelText="Add files"
  name=""
  multiple
  role=""
  tabIndex={-1}
  onChange={onChange}
/>

**Comment by asudoh** [comment]
Hi 👋 looks not, will be a good enhancement as far as I see. Would be passing along `disabled` to the `<input type="file">`.

**Comment by hongcbjch** [comment]
Thanks. Please let me know when the enhancement is implemented.
