### ISSUE TITLE
Add FooterItem component

### ISSUE THREAD

**Issue by vpicone** [IBM/carbon-components-react#1445]
### Summary

I think it'd be cool to easily add additional Footer items without needing to go look up the appropriate class names and dom heirarchy.

This is an example of how writing a Footer looks now with the default styling in place:

https://codesandbox.io/s/2x6453ypxp

### Justification

The "labelOne, linkTextOne, linkHrefOne, labelTwo,linkTextTwo,linkHrefTwo" could signal to individuals that the Footer component is more strict than it actually is. Or someone might wonder "is there a label/link/linkText Three?

If someone wants to add additional links, the need to go and mimic the styling of the first to elements or start from scratch.

From the carbon-react slack:
> `<Footer> Component not supporting more than two link to add. Do we have any solution to fix this issue. Please share your in case any solution or workaround to this issue.`

### "Must have" functionality

User's should be able to supply a link, label, and linkText to a FooterItem and have it handle the styling to match the default link/label/linktext styles

Additionally, users could be able to select a `type` property from `['link', 'cta']`

### Available extra resources

I could implement this if folks think it's a good idea.

**Comment by joshblack** [comment]
Definitely like the suggestion! I'd be down for adding it in if others are 👍

**Comment by vpicone** [comment]
Cool, I'll give it a shot then!

**Comment by joshblack** [comment]
Thanks for the help @vpicone! 🙏

**Comment by xrissot-ibm** [comment]
Hi,
If I can add one item to the wish list, please add also the target attribute to the link in order to be able to open the link in a new window for example.

**Comment by vpicone** [comment]
@xrissot-ibm I think that's a nice thought. I think the best API for this would allow folks to supply their own Link component. I'm gonna revisit this.

**Comment by vpicone** [comment]
Closing this since the footer is being handled in addons now.
