### ISSUE TITLE
ComposedModal Clicking "outside" the modal causes it to close, make this feature optional

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-components-react#1456]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary
A recent release of ComposedModal has added and auto-close when users click outside the dialog.  I'd like to request that this be controlled through a prop so that I can disable because I'm using certain dialogs within dialogs (I know it's kind of a bad pattern, but it really doesn't feel bad the way we're using them) but when I interact with the nested dialog, it closes the parent dialog behind it, (since the interactions are "clicks" outside the parent)

I'd like to request that a property be added (default to true) called closeOnClickOutside, that I can override, to allow these nested dialogs to continue to work.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! While I'm open for making click-outside-to-close optional, AFAIK nested modal is _not_ a pattern Carbon recommends. I'd recommend design efforts to avoid nested modal (alternate UI for second-level modal, piggybacking multiple modals, etc.), but let us know if there is a case that would be very hard. Also a PR will be nice. Thanks!

**Comment by scottdickerson** [comment]
I got rid of the nested modals, but still need to stop this from closing (since I am preserving the state of the previous modal by leaving it open in the background)

**Comment by scottdickerson** [comment]
I don't need a separate prop, I can just return false from the "onClose" prop that I pass to ComposedModal.
