### ISSUE TITLE
Skeleton RadioButton doe not work in RadioButtonGroupInput

### ISSUE THREAD

**Issue by nicoxxie** [IBM/carbon-components-react#1457]
## Detailed description

> Describe in detail the issue you're having.

When I use Skeleton RadioButtons, it doesn't show the skeleton but shows the radio button instead.

> Is this issue related to a specific component?

RadioButtonGroupInput

> What did you expect to happen? What happened instead? What would you like to see changed?

I should see list of skeleton RadioButtons in the group

> What browser are you working in?
All

> What version of the Carbon Design System are you using?
6.41.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud, yes

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in code sandbox
https://codesandbox.io/s/zr93l1487x

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Hi @nicoxxie thank you for reporting! It appears that the CodeSandbox link has table tool bar search box instead of radio button skeleton. Probably you wanted to put a different link...? Thanks!

**Comment by nicoxxie** [comment]
Hi @asudoh, I updated the sandbox, accidentally override it.  Here is the code to reproduce, just stick a skeleton inside the RadioButtonGroup

```
        <RadioButtonGroup
          defaultSelected="default-selected"
          legend="Group Legend"
          name="radio-button-group"
          valueSelected="default-selected"
        >
          <RadioButtonSkeleton />
          <RadioButton
            value="default-selected"
            id="radio-2"
            className="some-class"
            disabled={false}
            labelText="Radio button label"
          />
        </RadioButtonGroup>
```

**Comment by nicoxxie** [comment]
@asudoh Thanks for the reply, a mix between skeleton and RadioButton is not a requirement.

**Comment by asudoh** [comment]
Great thanks @nicoxxie for clarifying! In such case, you can use `<RadioButtonSkeleton>` _without_ `<RadioButtonGroup>`. Hope it makes sense!

**Comment by asudoh** [comment]
Closing as a solution exists. Please speak up if anybody finds otherwise!
