### ISSUE TITLE
DropdownSkeleton does not support label

### ISSUE THREAD

**Issue by nicoxxie** [IBM/carbon-components-react#1460]
## Detailed description

> Describe in detail the issue you're having.
DropdownSkeleton does not cover label and support hideLabel attribute, other input supports it

> Is this issue related to a specific component?
DropdownSkeleton

> What did you expect to happen? What happened instead? What would you like to see changed?
Support hideLabel also ability to toggle label skeleton

> What browser are you working in?
All

> What version of the Carbon Design System are you using?
6.14.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud
## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

* Screenshots or code
* Notes

**Comment by nicoxxie** [comment]
@alisonjoseph so I should use SelectSkeleton for DropdownV2 component? DropdownV2 supports labels and on the http://react.carbondesignsystem.com/ story when I select DropdownV2-skeleton the page says to use DropdownSkeleton

**Comment by alisonjoseph** [comment]
DropdownV2 doesn't have a label above it, it's not a form element. Unless you are looking at something different than I am. 🤔

**Comment by nicoxxie** [comment]
@alisonjoseph you are right, we hard coded the label.  Closing this issue thank you
