### ISSUE TITLE
How to set style for selectable tiles in Carbon

### ISSUE THREAD

**Issue by riya-naico** [IBM/carbon-components-react#1465]
Hi,
how can we implement spacing for tiles (padding,margin etc) and for div tags in carbon ? I could find some other fields with styles in the below link.So can we implement $tile-padding-bottom : 32px for tile?
https://github.com/carbon-design-system/carbon-themes/blob/master/themes/carbon.scss

Thanks!

**Comment by asudoh** [comment]
HI 👋  you can implement it with your custom CSS. Hope it helps!

**Comment by riya-naico** [comment]
Hi,
Can we add manual class and then use carbon style variables inside it?
.padding-bottom-xl{
    padding-bottom: $spacing-xl;
}
Here padding-bottom-xl is a custom class added by me to a div.

**Comment by asudoh** [comment]
As you said, you can use our variables in your CSS (Sass) class. Hope this helps!

**Comment by riya-naico** [comment]
Hi,

It worked. Thanks a lot.
