### ISSUE TITLE
How to data-invalid inactive when validation passed.

### ISSUE THREAD

**Issue by riya-naico** [IBM/carbon-components-react#1466]
How to trigger  data-invalid inactive when validation passed.

to avoid duplicate input.
<div className="bx--select">
                {!this.state.validCountry ?
                  <select id="ddlCountry" name='CountryValue' className="bx--select-input"
                    value={this.state.countryValue} onChange={this.countryChange.bind(this)}>
                    {countriesList}</select>
                  :
                  <select id="ddlCountry" name='CountryValue' className="bx--select-input"
                    value={this.state.countryValue} data-invalid onChange={this.countryChange.bind(this)}>
                    {countriesList}</select>
                }
              </div>

**Comment by asudoh** [comment]
Hi 👋 is it a question for `carbon-components-react` or something else? If it's the former, could you be more clear on your question? Thanks!

**Comment by riya-naico** [comment]
Hi
carbon-components vanilla js .Talking about below textbox
http://www.carbondesignsystem.com/components/text-input/code

https://codepen.io/team/carbon/pen/YEZLyd

Thanks

**Comment by asudoh** [comment]
Given you are talking about vanilla, https://github.com/IBM/carbon-components/issues is the place to go. For vanilla, you can use regular DOM API to set `data-invalid`. Hope it helps!

**Comment by riya-naico** [comment]
Thanks
