### ISSUE TITLE
NumberInput: Misalignment of number controls

### ISSUE THREAD

**Issue by Joseph-Hitchcock** [IBM/carbon-components-react#1468]
When a NumberInput's invalidText wraps onto another line, it causes the number controls to no longer be centered in the input field.

![image](https://user-images.githubusercontent.com/40905872/47236615-8d59ee80-d391-11e8-9c0d-3c46b23fe198.png)

![image](https://user-images.githubusercontent.com/40905872/47236617-8fbc4880-d391-11e8-8563-3b0b46a37456.png)

This [code sandbox](https://codesandbox.io/s/wqwmxpo435) illustrates this behavior.

**Comment by alisonjoseph** [comment]
Thanks for pointing this out, moving over to carbon-components since this is a css bug.

**Comment by alisonjoseph** [comment]
Issue moved to [IBM/carbon-components #1310](https://github.com/IBM/carbon-components/issues/1310) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alisonjoseph** [comment]
Issue moved to [IBM/carbon-components #1311](https://github.com/IBM/carbon-components/issues/1311) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alisonjoseph** [comment]
moved to carbon-components since this is a css bug. Thanks for reporting! https://github.com/IBM/carbon-components/issues/1312
