### ISSUE TITLE
MultiSelect.Filterable : clears the filter after one selection, not allowing multi select.

### ISSUE THREAD

**Issue by sandhya-r-reddy** [IBM/carbon-components-react#1476]
## Detailed description

> Describe in detail the issue you're having.

When using MultiSelect.Filterable, we are able to filter the items and display filtered list based on filter string, but the filter is cleared just after one selection.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug
>Is this issue related to a specific component?

MutliSelect
> What did you expect to happen? What happened instead? What would you like to see changed?

Expectation is to allow user to select multiple items in the filtered list .
> What version of the Carbon Design System are you using?

6.39.3

## Steps to reproduce the issue
1) Have a list with items as " item 1", "list 1", "item 2", "list 2"
2) Filter in MultiSelect component for filter string "2"
3) Select item2, then the filter is cleared, before we select the list 2.

**Comment by alisonjoseph** [comment]
Hi 👋  tagging @IBM/carbon-designers to see if this is the recommended pattern they would expect.

**Comment by aagonzales** [comment]
Yes, I think it fine to have the filter stay after selection. However, I think the filter should still clear after the menu is closed.

**Comment by sandhya-r-reddy** [comment]
Hi, any updates on when this bug will be fixed.

**Comment by alisonjoseph** [comment]
Hi @sandhya-r-reddy this is isn't currently prioritized in our upcoming sprints for the year. However, we always welcome PRs and fixes if this is something you or someone on your team would like to take on.
