### ISSUE TITLE
Date picker input doesn't disable autocomplete

### ISSUE THREAD

**Issue by kfrost-ibm** [IBM/carbon-components-react#1482]
### Detailed description

When a date has been previously entered, the date picker input shows autocomplete.

### What browser are you working in?
Chrome 69.0.3497.100

### What version of the Carbon Design System are you using?
carbon-components-react 6.38.1

![d48f46f8-d92f-11e8-8b23-89bf3c58ef54](https://user-images.githubusercontent.com/44509556/47587749-f1505a00-d931-11e8-95cc-a007360e0474.png)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Just wanted to see if you have tried `<DatePickerInput autocomplete="off">`.

**Comment by kfrost-ibm** [comment]
That seems to work. Thanks. Should that be disabled by default?

**Comment by asudoh** [comment]
^ @tw15egan thoughts...? Thanks!
