### ISSUE TITLE
Update Storybook to reflect the use of carbon-icons

### ISSUE THREAD

**Issue by carvallegro** [IBM/carbon-components-react#1491]
## Detailed description

It's not an issue related to the components per se, more to the Storybook documentation. In [Storybook](http://react.carbondesignsystem.com), the example using icons are not truthful.

Using Storybook code leads to mistake when you're not familiar with the codebase. If we look at Structured List as an example we can see that when copy and pasting code the `icon` property is actually a JS object, which is not correct, it should be an object imported from `carbon-icons`.

Code examples and solution below.

## Steps to reproduce the issue

1. Go to the Storybook for [Structured List](http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&selectedKind=StructuredList&selectedStory=Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
2. Copy and paste code in your own app.

**Test Case in Sandbox:** 
https://codesandbox.io/s/k24o7pomm5

**Solution in Sandbox:**
https://codesandbox.io/s/q8580y7jww

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Storybook's "Story Source" feature seems to have a limitation showing prop with complex object, where it shows some inner-properties with "...", which seems to have caused a confusion. The actual Storybook code can be found at https://github.com/IBM/carbon-components-react/blob/v6.39.0/src/components/StructuredList/StructuredList-story.js#L85, whose icon is actually [coming from `carbon-icons`](https://github.com/IBM/carbon-components-react/blob/v6.39.0/src/components/StructuredList/StructuredList-story.js#L4). Hope this helps!

**Comment by carvallegro** [comment]
Hey,

It does help, thanks! Could we keep this issue open? I'd like to find a way to fix that but I don't have any ETA to provide at the moment.

Cheers

**Comment by asudoh** [comment]
Sure @carvallegro! Looking forward to hearing from you - It may end up with a fix to Storybook or its add-on.

**Comment by asudoh** [comment]
@carvallegro Just wanted to ping to see if you are still interested in this area. Thanks!

**Comment by carvallegro** [comment]
Hey! I'm currently without any computer so literally not able to touch
code. Not sure when I'll be able to have a look

**Comment by asudoh** [comment]
Thanks @carvallegro for the response - Closing for now, can reopen if anybody else has an interest!
