### ISSUE TITLE
Modify DropdownItem to accept children in place of itemText

### ISSUE THREAD

**Issue by justinpurcell1** [IBM/carbon-components-react#1495]
### Summary

Instead of itemText, which can only be styled one way, update DropdownItem such that it can render multiple child components which are styled differently. 

Eg:

   Messages _3 unread_

### Justification

I would like to use this feature in an upcoming project.

### Desired UX and success metrics

The user will be able to access more information in a compact area if text is bolded, colored differently, etc.

### "Must have" functionality

DropdownItem must be able to accept and render children when itemText is not supplied.

### Specific timeline issues / requests

Within two weeks would be ideal.

### Available extra resources

I can write the feature if needed.

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Sounds a good change, and a PR is welcome as you alluded!
