### ISSUE TITLE
Update Storybook to v4

### ISSUE THREAD

**Issue by vpicone** [IBM/carbon-components-react#1496]
### Summary

Storybook v4 has been released and has a lot of great updates for performance and customization.

https://medium.com/storybookjs/storybook-4-0-is-here-10b9857fc7de

### Justification

This upgrade would let us match more closely the carbon-design documentation with style and layout. 

### Specific timeline issues / requests

The migration guide is pretty straightforward, barring any weird addon issues:
https://medium.com/storybookjs/migrating-to-storybook-4-c65b19a03d2c

I'll give this a go.

**Comment by joshblack** [comment]
Definitely would love to get this updated, v4 work looks great 😄 I know @asudoh has some reservations around it's alpha status though, so we should wait to hear him chime in before working on a PR 👍

**Comment by vpicone** [comment]
It's no longer alpha as of this morning!
