### ISSUE TITLE
Welcome To Storybook

### ISSUE THREAD

**Issue by aroduribe** [IBM/carbon-components-react#1499]
## Summary
Welcome To Storybook has an incorrect directory and file location. **src/stories** directory and **src/stories/index.js** do not exist. Instead, I see stories.index.js in the stories directory. 
## Relevant information
<img width="1380" alt="screen shot 2018-10-29 at 5 59 07 pm" src="https://user-images.githubusercontent.com/1895440/47688841-688d2480-dba4-11e8-89df-09ef5c95b26c.png">

**Comment by aroduribe** [comment]
I actually wanted to write it in the React components.

**Comment by asudoh** [comment]
I see, where did you find `stories.index.js` in `carbon-components-react` codebase?

**Comment by aroduribe** [comment]
<img width="266" alt="screen shot 2018-10-29 at 10 10 53 pm" src="https://user-images.githubusercontent.com/1895440/47697288-98015880-dbc7-11e8-9be5-e565e5d4316b.png">

**Comment by asudoh** [comment]
https://github.com/IBM/carbon-components-react/tree/master/stories gives me 404 - What version of `carbon-components-react` are you referring to?

**Comment by aroduribe** [comment]
This is my forked version https://github.com/aroduribe/carbon-components-react

**Comment by joshblack** [comment]
Hi @aroduribe! We don't write our stories in a `story` or `stories` directory. Instead, we write them inside each component folder in `src/components` with the `<ComponentName>-story.js` convention 👍

**Comment by aroduribe** [comment]
Right! I wondered how that appeared... I'll re forked again :) Thanks!
