### ISSUE TITLE
DataTableSkeleton results in TypeError: Object doesn't support property or method 'keys' on IE11

### ISSUE THREAD

**Issue by austinbruch** [IBM/carbon-components-react#1516]
## Detailed description

> Describe in detail the issue you're having.

Rendering `DataTableSkeleton` on IE11 is resulting in an error: 
```
TypeError: Object doesn't support property or method 'keys'
```
Looking at the source, it appears that `Array.prototype.keys` is called, but that is not supported in IE11. 

> Is this issue related to a specific component?

Yes, `DataTableSkeleton`.

> What did you expect to happen? What happened instead? What would you like to see changed?

DataTableSkeleton should render, but an error is thrown instead.

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

6.45.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Identity

## Steps to reproduce the issue

1. Include a `DataTableSkeleton` in your react app's rendered output.

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

I cannot get codesandbox to work on IE11, so I can't produce a reduced test case. Appears there's some issue with codesandbox itself.

## Additional information

I suspect this was introduced in this commit: https://github.com/IBM/carbon-components-react/commit/63543c476710ec0a8f30ed265c0bf9f7ac5d66bb#diff-3055cc730be6e994e8d2d9abe2938111 with the goal of supporting the `columnCount` prop.

The [list of required polyfills](https://github.com/IBM/carbon-components-react/blob/master/.storybook/polyfills.js) for older browsers like IE11 does not seem to satisfy this issue. 

I think the list of required polyfills should be updated to account for this new requirement, or the `DataTableSkeleton` code should be updated to achieve the goal of supporting `columnCount` using some other mechanism.

**Comment by austinbruch** [comment]
Following the pattern for polyfill inclusion from `core-js`...
Adding `import 'core-js/modules/es6.array.iterator';` seems to resolve the issue.

The `Array.iterator` module  includes the `keys` prototype function, among other things, per this issue: https://github.com/zloirock/core-js/issues/421

You might want to consider including the above module in the list of required polyfills mentioned in the original issue.

**Comment by joshblack** [comment]
Thanks for the report, @austinbruch! Most likely we should just re-write this to not use `keys()` from `Array.prototype`.
