### ISSUE TITLE
[OverflowMenu Storybook]: Not rendering properly

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-components-react#1542]
## Detailed description

`OverflowMenu` is currently not rendering in the storybook. The associated info in the story is also incomplete with single letter component names, and some visual regression overflow with the props table.

![image](https://user-images.githubusercontent.com/3360588/48221431-b00b7180-e357-11e8-9ffd-6cf847057fc3.png)

![image](https://user-images.githubusercontent.com/3360588/48221452-c7e2f580-e357-11e8-8a26-40bf31633fd1.png)

**Comment by vpicone** [comment]
This is happening in a lot of components. It looks like the displayName isn't getting set appropriately in static builds. Explicitly setting the display name in the component fixes the problem. `OverflowMenu.displayName = 'OverflowMenu';`

Something must be funky with the wrapComponent business.

![screen shot 2018-11-09 at 2 03 26 pm](https://user-images.githubusercontent.com/4078018/48285470-51fa8f00-e428-11e8-86dc-f1f2871d47fc.png)

**Comment by asudoh** [comment]
Hi @vpicone 👋 thanks a lot for doing thorough analysis and providing us with a set of proposals! I agree with you that 1. is the least brittle (thus the best) solution. Let's see how others respond and unless anybody disagrees I'm looking forward to seeing a PR!

**Comment by alisonjoseph** [comment]
Yes thank you so much for taking the time to research this. 🙌 I agree on 1. defining the display name for each component sounds like the best solution.

**Comment by vpicone** [comment]
@joshblack that one worked really well, it essentially does what has always happened in that it grabs the function name. My PR actually broke some snapshot tests because a few of the components were given the "ForwardRef" display name. Explicitly setting the display name fixes that.

From the snapshot test:
{code}
    @@ -1,6 +1,6 @@
    - <ForwardRef // Our snapshot has ForwardRef as the component's displayName
    + <SideNavMenuItem // Explicitly setting it overrides that.
        className="custom-classname"
        href="#"
        isActive={true}
      >
        <li
    @@ -26,6 +26,6 @@
                </span>
              </SideNavLinkText>
            </a>
          </Link>
        </li>
    - </ForwardRef>
    + </SideNavMenuItem>
{code}
