### ISSUE TITLE
Search: user input is not visible

### ISSUE THREAD

**Issue by youda97** [IBM/carbon-components-react#1543]
## Detailed description

> Describe in detail the issue you're having.

When you type in the search input in storybook, the text is not visible.

> Is this issue related to a specific component?

Search

> What did you expect to happen? What happened instead? What would you like to see changed?

Whats happening right now is that a change event is occurring but any text you type in is not visible.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

## Steps to reproduce the issue

http://react.carbondesignsystem.com/?selectedKind=Search&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by lekterable** [comment]
Hey man, I think this is kind of intentional. To change the Search component value you can use Storybook's knobs.
![Knob example](https://i.imgur.com/G6EEsnn.png)
