### ISSUE TITLE
Slider doesn't provide a callback for handle release

### ISSUE THREAD

**Issue by tombrowndev** [IBM/carbon-components-react#1568]
It would be useful to get the current value of the Slider when the user releases the handle. 

For example, if you want to perform an action such as an API call only when the user lets go of the handle.

There is an implementation which I have created a PR for linked below

https://github.com/IBM/carbon-components-react/pull/1567

**Comment by tombrowndev** [comment]
For example, the Airbnb Rheostat slider, their onChange callback only fires when the handle is released. The have another callback for dragging like the carbon slider called onValuesUpdated which can be used to make it a controlled component.

Please see my demo of how this works and an application for connecting with an api...
(mimics an api being called by setting a state value apiCalled to true)

https://codesandbox.io/s/zrrj650pl3

Another example is the React Component slider. It uses onChange similar to the carbon slider, but it also has onAfterChange which according to the documentation... "onAfterChange will be triggered when ontouchend or onmouseup is triggered." which is the same implementation I have used in my pull request.

I believe this is a really important feature to add, because you don't want to call an API multiple times a second.

Any feedback would be really appreciated.

**Comment by asudoh** [comment]
Closing as #1567 has been merged.
