### ISSUE TITLE
Regression when consuming UMD: ReferenceError: module is not defined

### ISSUE THREAD

**Issue by asfordmatt** [IBM/carbon-components-react#1620]
We have some old AnguarJS code that embeds Carbon components using react2angular.
The Karma tests fail with:
```
 "message": "An error was thrown in afterAll\nReferenceError: module is not defined\n    at <Jasmine>\n    at Suite.<anonymous> 
```

This code doesn’t have a webpack build it consumes the following UMDs:
```
      './node_modules/react/umd/react.production.min.js', 
      './node_modules/react-dom/umd/react-dom.production.min.js', 
      './node_modules/classnames/index.js',
      './node_modules/prop-types/prop-types.min.js',
      './node_modules/carbon-icons/dist/carbon-icons.js',
      './node_modules/carbon-components-react/umd/carbon-components-react.js',
```

The problem started in carbon-components-react v6.53.2 after this PR:
https://github.com/IBM/carbon-components-react/pull/1540

**Comment by asfordmatt** [comment]
@asudoh @alisonjoseph @joshblack this is a weird one. I reverted to the previous commit, built carbon-components-react.js and it's fine, but with carbon-components-react.js build with the CSS prefix changes, it fails. Is there a UMD for carbon-components I should be loading now as well?

**Comment by joshblack** [comment]
@asudoh do we just need to add the UMD global name in our [rollup config](https://github.com/IBM/carbon-components-react/blob/master/scripts/rollup.config.js#L93)?

**Comment by asfordmatt** [comment]
That looks promising @joshblack! I was able to get things working by adding:
```
'carbon-components': 'CarbonComponents'
```
to rollup, and then adding this to the list of UMDs we load:
```
'./node_modules/carbon-components/scripts/carbon-components.min.js'
```

Is that the right UMD for carbon-components? Why isn't it in the umd folder?
