### ISSUE TITLE
http://react.carbondesignsystem.com doesn't work at all in edge browser

### ISSUE THREAD

**Issue by LongBu** [IBM/carbon-components-react#1624]
Visit http://react.carbondesignsystem.com/ using an edge browser

## Detailed description

Does carbon support the edge browser?  Some ibm customers might utilize products with edge?

**Comment by joshblack** [comment]
Hi @LongBu! 👋 We definitely support edge, but the tool we use for development (storybook) might not. Are you getting an error in console when loading it in edge?
