### ISSUE TITLE
Inline Select Styling looks to be broken in carbon-components-react

### ISSUE THREAD

**Issue by LongBu** [IBM/carbon-components-react#1651]
## Inline Select Styling looks to be broken in carbon-components-react

-->

## Detailed description

> See title

> Visit http://react.carbondesignsystem.com =>type in select, select inline in the knobs tab

> What did you expect to happen? What happened instead? What would you like to see changed?
I'd expect the arrow to be next to the actual selector

> Chrome 71

> What version of the Carbon Design System are you using? 6.58.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
 Yes

- Screenshots or code
![image](https://user-images.githubusercontent.com/7905656/49901148-6ae2cf80-fe2e-11e8-9859-85c0c713d56b.png)

**Comment by asudoh** [comment]
Similar issue can be seen at: http://react-experimental.carbondesignsystem.com/?selectedKind=Select&selectedStory=Default

**Comment by emyarod** [comment]
it looks like this is also broken for the vanilla v9 component

**Comment by asudoh** [comment]
Seems that #1218 introduced the problem - It appears that `helperText` was introduced without considering inline mode. It appears that IBM/carbon-components#1821 has been merged, and `carbon-components-react` has reference to newer `carbon-components` version already. Does this mean this issue has been fixed in `v10`...?

**Comment by emyarod** [comment]
@asudoh it's fixed in v10, but I'm holding off on modifying the React component until https://github.com/IBM/carbon-components/pull/1978 is merged as well. Will we address this issue for v9/legacy?

**Comment by asudoh** [comment]
@emyarod Yes this level of breakage is something we should address to `v9`, especially given we haven't released `v10`. Thanks!

**Comment by emyarod** [comment]
I believe this has been addressed in https://github.com/IBM/carbon-components-react/pull/2030
