### ISSUE TITLE
Browser related : Tabs > Tab is not tab-able in firefox.

### ISSUE THREAD

**Issue by schhimw** [IBM/carbon-components-react#1694]
## Detailed description

> Describe in detail the issue you're having.

Tab is not tab-able in Firefox (latest version)

> Is this issue related to a specific component?

Tabs

> What did you expect to happen? What happened instead? What would you like to see changed?

Tabs should be tab-able in all browsers

> What browser are you working in?

Firefox (latest version)

> What version of the Carbon Design System are you using?

"carbon-components": "~9.8.4",
"carbon-components-react": "6.32.4",

## Steps to reproduce the issue

1. Access Tabs in Firefox (latest version)
2. Navigate to Tabs > Tab using tab key

**Comment by joshblack** [comment]
Hi @schhimw! 👋 I believe that the Tab widget was recently changed to support arrow keys for navigation instead of the tab key explicitly (PR: https://github.com/IBM/carbon-components-react/commit/17fb3dde47b600492e6d05e23521394aa95df98d) is this the behavior that you're noticing?

**Comment by schhimw** [comment]
Hi @joshblack , we are noticing tabbing issue with firefox .. 
Chrome and Edge works fine .. 
While investigating I found that the tabindex was always set to `-1`. 
So yes above PR will resolve the issue.

For clarification: Looks like with above PR `17fb3dd` tab navigation will be supported using arrow keys and not tabs. Is that correct ?

**Comment by joshblack** [comment]
@schhimw correct, that PR that was merged in made it so that you use arrow keys for navigation versus tab in the tabs widget 👍

**Comment by schhimw** [comment]
sounds good @joshblack thank you
