### ISSUE TITLE
Allow for an additional option for a label for the dropdown v2? 

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-components-react#1706]
## Detailed description

DropdownV2 component does have an option to provide a label to the dropdown. It makes sense to have an optional label and helper text as all other form components have that option. 

I am using carbon-react-component of below version.
"carbon-components": "9.62.6",
    "carbon-components-react": "6.70.1",

## Steps to reproduce the issue

http://react.carbondesignsystem.com/?selectedKind=DropdownV2&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

> CodeSandbox
https://codesandbox.io/s/p5z81rov0

## Additional information

- Like the way text input can have a label and helper text so expectation is something similar for dropdownV2 also.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/22093326/50776114-237d2100-12be-11e9-87f6-71b17cd0dfe3.png">

**Comment by joshblack** [comment]
Hi @kalyanixraut! 👋 Thanks for taking the time to make this issue 😄 Definitely agreed that this should be a part of the component!
