### ISSUE TITLE
Form validation UI content text should not influence styling of number input up/down buttons

### ISSUE THREAD

**Issue by LongBu** [IBM/carbon-components-react#1710]
## When utilizing the number input, but stripping out the helper text/label/Form validation UI content, but clicking on the form validation, the number buttons are out of place int he input field

> See picture

> Is this issue related to a specific component? number input

> What did you expect to happen? What happened instead? What would you like to see changed?

I'd expect given the content the number input buttons not to have it's styling influenced

> What browser are you working in? Chrome Version 71.0.3578.98 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?     carbon-components-react": "^6.58.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Yes
## Steps to reproduce the issue
See comments/screen capture
![image](https://user-images.githubusercontent.com/7905656/50794060-12b9b480-1298-11e9-85e8-e44a2d00c42f.png)

**Comment by aledavila** [comment]
Hi @LongBu! :wave:  Thanks so much for taking the time to make this issue :smile: 

This does seem wonky as positioning for the arrows depends on the validation message. 
I just want to make sure and check with @IBM/carbon-designers. 
Can number input validation can be used without a validation message?

**Comment by aagonzales** [comment]
The validation message shouldn't effect the placement of the arrows. They should always be aligned with the number.

**Comment by emyarod** [comment]
Related ticket: https://github.com/IBM/carbon-components/issues/1621

**Comment by emyarod** [comment]
I believe this will be fixed in v10 via https://github.com/IBM/carbon-components-react/pull/1654
