### ISSUE TITLE
In DropDownV2, the selectedItem should be update when the items list are changed

### ISSUE THREAD

**Issue by yqinxa** [IBM/carbon-components-react#1719]
## Detailed description

> In DropdownV2, when the items are changed, the selectedItem is still the one users selected last time, but this item may be not in the items list already. 

> The current issue exists in "Anonymize" node, when the fields users select to do anonymize are changed, the selectedItem is still the one users selected last time, which is not updated accordingly. We hope when the items list are updated, the selectedItem will be the first one in the list

> Browser: Chrome

> The version of carbon:
    "carbon-components": "8.20.3",
    "carbon-components-react": "6.20.0"

## Steps to reproduce the issue
 I create a simple example to reproduce this issue in sandbox, please go to https://codesandbox.io/s/180y1j6j97 for reference

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
hi @yqinxa, are you passing in a value for the `selectedItem` prop to `<DropdownV2 />`? [I added that to your CodeSandbox example and it seems to be working as expected](https://codesandbox.io/s/v8qwvz6jq7). Otherwise, please let me know if I have misunderstood your issue

**Comment by yqinxa** [comment]
I am sorry, I forgot to add this property. And now it works well, thanks very much.
