### ISSUE TITLE
Button: When clicking on icon of a button, the target returned is different 

### ISSUE THREAD

**Issue by nicoxxie** [IBM/carbon-components-react#1739]
## Detailed description

> Describe in detail the issue you're having.

I'm passing in an onClick function for a button with icon.  When I click on the text,  the event target returned is the `<button>`, but when I click on the icon on the button I get `<svg>` as the event target.  How can I get the actual button as the target when clicking anywhere inside the button? `imaginaryTarget` doesn't work also.

> Is this issue related to a specific component?

Button

> What did you expect to happen? What happened instead? What would you like to see changed?

Return the <button>

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
^6.45.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud
see sandbox

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

https://codesandbox.io/s/p9zw5j9zlx

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Wanted to double-check if you have tried [`currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget). Thanks!

**Comment by nicoxxie** [comment]
@asudoh that solved it, thank you!
