### ISSUE TITLE
[ModalWrapper]: triggerButtonIcon can't be SVG file

### ISSUE THREAD

**Issue by Snurppa** [IBM/carbon-components-react#1749]
## Detailed description

*ModalWrapper* component has `triggerButtonIcon` parameter, which currently can only be a string:
`triggerButtonIcon: PropTypes.string`.
https://github.com/IBM/carbon-components-react/blob/master/src/components/ModalWrapper/ModalWrapper.js#L25

The prop is passed directly to *Button* component, which can take icon as either string or an SVG:
https://github.com/IBM/carbon-components-react/blob/master/src/components/Button/Button.js#L133

Wouldn't it be logical to have `triggerButtonIcon` be having the same type as the `icon` prop in *Button* component? As in, accept either string or SVG.

I'm now facing an issue, where I can't use my own icons with ModalWrapper `triggerButtonIcon`.

## Expected behaviour

I can give *ModalWrapper* `triggerButtonIcon` prop also as SVG, because *Button* component accepts either string class or SVG as prop for the icon.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! While `<ModalWrapper>` is an "working as an example" component and `<ComposedModal>` may be closer to your need, I'm open for supporting the shape you suggested. Also, team is working on "icon as a React component" for next release where it's nice to be supported here and other components.

**Comment by asudoh** [comment]
Fixed by: #1908
