### ISSUE TITLE
Write migration guide for v10

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-components-react#1759]
With the move towards v10, we need to make sure that we have written migration documentation for any significant changes in the release. This issue is for identifying those topics and coordinating getting them merged in.

**Comment by asudoh** [comment]
### Components React

- [ ] Slider - Value change via props no longer fires `onChange` event
- [ ] Tag - List of strings supported by `type` prop has been changed

**Comment by shinytoyrobots** [comment]
Status of this?

**Comment by joshblack** [comment]
So far we only have: https://github.com/IBM/carbon-components-react/blob/master/docs/migration/migrate-to-10.x.md

**Comment by asudoh** [comment]
#2105 completes the effort. More on what @joshblack said on ^ - https://github.com/IBM/carbon-components-react/blob/master/docs/migration/migrate-to-10.x.md works as the entry point, which has links to component-level migration docs.

**Comment by asudoh** [comment]
OK #2105 has been merged - Can reopen if we find anything missing.
