### ISSUE TITLE
Checkpoint component doesn't align with multi-line label.

### ISSUE THREAD

**Issue by vidhi11** [IBM/carbon-components-react#1773]
## Detailed description

> Describe in detail the issue you're having.
- Facing issue with using checkpoint component for multi-line label. When the label is multi-lined, checkpoint positions to the middle rather than starting from top along with label. 

> Is this issue related to a specific component?
- Yes, Checkpoint component.

> What did you expect to happen? What happened instead? What would you like to see changed?
- I expect the checkbox to align with label. Instead, label starts from top and checkbox positioned to be in middle of label. 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/32270454/51492812-abf8c880-1d78-11e9-9bb5-7fef7dcadad8.png">

> What browser are you working in?
- Mozilla, Safari and Chrome

> What version of the Carbon Design System are you using?
- 9.67.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
- I'm from IBM hybrid cloud - GCAT team. We have created micro-service using react/carbon-components. We have release on 31st Jan'19.  

> Please create a reduced test case in CodeSandbox
- https://codesandbox.io/s/oxnwlzxy06

## Additional information

- Screenshots:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/32270454/51492816-af8c4f80-1d78-11e9-8acb-042513b7a6f4.png">

**Comment by emyarod** [comment]
hi @vidhi11 thank you for reporting this! Checkbox positioning is aligned to the start of the label in the next major version release of Carbon (Carbon v10). Is this a major issue for your current project at the moment?

**Comment by vidhi11** [comment]
@emyarod Not a major issue, but an issue.  For now I have added temporary fix in our project. Thanks.
