### ISSUE TITLE
Form select dropdown has a scrollbar in Firefox

### ISSUE THREAD

**Issue by rob-richards** [IBM/carbon-components-react#1775]
## Detailed description

Form select dropdown has a scrollbar in Firefox (v60.4.0esr)

## Additional information
![2019-01-20_13-45-05](https://user-images.githubusercontent.com/7707326/51496229-eff5c880-1d8c-11e9-86a0-2d122ded1c4c.png)

<img width="202" alt="screen shot 2019-01-21 at 2 46 41 pm" src="https://user-images.githubusercontent.com/7707326/51497126-1c5f1400-1d90-11e9-99ef-0baad18cb6e4.png">

**Comment by emyarod** [comment]
hi @rob-richards thanks for submitting a ticket! To help me understand the issue better, would you mind providing some additional context?

**Comment by rob-richards** [comment]
Sure. If you open Firefox and go to the [Carbon storybook and view the `<Form>` component](http://react.carbondesignsystem.com/?selectedKind=Form&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), you will see when you click on the select dropdown, there is now a scrollbar on the right side. Before upgrading Firefox, the scrollbar was not there.


<img width="318" alt="screen shot 2019-01-31 at 2 52 12 pm" src="https://user-images.githubusercontent.com/7707326/52081275-d102ed80-2567-11e9-9aae-9139ebcbf7e0.png">

**Comment by emyarod** [comment]
and just to confirm, is this not the default behavior of Firefox on macOS?

**Comment by rob-richards** [comment]
That is correct, it is not the default behavior in Firefox. Carbon uses custom styled form elements.

The picture below is the default style in Firefox.
<img width="129" alt="screen shot 2019-02-01 at 9 45 13 am" src="https://user-images.githubusercontent.com/7707326/52129765-60f77480-2606-11e9-83b2-5ddcb5b7d4ce.png">

**Comment by emyarod** [comment]
It looks like the scrollbar only renders when `background-color` is applied to the `<select>` element. After a bit of searching I found that [this is a known issue with Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1498926)
