### ISSUE TITLE
Button: expose a 'ref' prop to allow focusing on the element

### ISSUE THREAD

**Issue by lauraalkhoury** [IBM/carbon-components-react#1777]
### Summary

In order to facilitate programmatically focusing on elements, we're asking that the Button component provides a `ref` prop that allows us to call .focus() on the html element.

> Clarify if you are asking for both design and development, or just design, or just development.

Just development.

### Justification

> Provide the business reasons for this request.

This is critical for a11y work - see this checkpoint for more info: https://www.ibm.com/able/guidelines/ci162/focus_order.html

Essentially, if the user exits from, say, a modal, we need to take the focus back to what triggered the modal. (See also https://www.ibm.com/able/guidelines/ci162/focus_order.html#PointOfRegard)

### "Must have" functionality

> Highlight any "must have" needs and functionality for the request.

Must be able to use refs to set focus on the Button.

### Specific timeline issues / requests

> Do you want this work within a specific time period? Is it related to an upcoming release?

We committed to having all a11y work complete by January 31st.

_NB: The Carbon team will try to work with your timeline, but it's not guaranteed. The earlier you make a request in advance of a desired delivery date, the better!_

**Comment by lauraalkhoury** [comment]
Not sure if this is relevant, but in particular we really need this feature for the Ghost Button.

**Comment by emyarod** [comment]
hi @lauraalkhoury thank you for submitting this ticket! If I'm not mistaken, [this commit](https://github.com/emyarod/carbon-components-react/commit/102f805f22b0ff8c296f9038bc84f947fb77fb85) from [this PR](https://github.com/IBM/carbon-components-react/pull/980) should have exposed refs on the `Button` component. Does your version of `carbon-components-react` include this change, or am I misunderstanding your initial request? Please let me know if the referenced PR does not address your issue

**Comment by joshblack** [comment]
Closing this for now, feel free to comment or make another issue if this still occurs! 👍
