### ISSUE TITLE
Checkbox: Shown as ForwardRef in React DevTools

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#1786]
## Detailed description

> Describe in detail the issue you're having.

React DevTools shows our `<Checkbox>` as `<ForwardRef>`:

![image](https://user-images.githubusercontent.com/1259051/51656792-ca173080-1fe5-11e9-829e-4ba7ebd9eb69.png)

> Is this issue related to a specific component?

`<Checkbox>`, `<Select>` and `<TextInput>`

> What did you expect to happen? What happened instead? What would you like to see changed?

React DevTools shows our `<Checkbox>` as it is.

> What version of the Carbon Design System are you using?

`6.79.0`

**Comment by rmullan** [comment]
I believe TextInput is behaving the same way due to release 6.78.0. I don't have time to investigate further so pinning back until this is resolved.

Cheers guys 
R
