### ISSUE TITLE
TextInput is shown as ForwardRef in React dev tool

### ISSUE THREAD

**Issue by rmullan** [IBM/carbon-components-react#1789]
![image](https://user-images.githubusercontent.com/26763947/51673179-46e5e280-1fc5-11e9-9d9b-45b5ccd33898.png)

If this is permanent please close and let me know. Much prefer TextInput though ;)

See comment from me in: https://github.com/IBM/carbon-components-react/issues/1786

**Comment by rmullan** [comment]
https://github.com/IBM/carbon-components-react/pull/1687/files

**Comment by asudoh** [comment]
Hi 👋 probably what you wanted to inspect is React component tree (VDOM), instead of actual DOM? You need React DevTools plugin for the former.

**Comment by rmullan** [comment]
https://github.com/IBM/carbon-components-react/pull/1770

**Comment by rmullan** [comment]
OK inspecting in React dev tools. It's a shame it breaks our tests though.

I will change tests to reflect changes.

Thanks

**Comment by rmullan** [comment]
Sorry reading around it's the ForwardRef which has broken my tests. Works if I dive.

![image](https://user-images.githubusercontent.com/26763947/51674715-5c5d0b80-1fc9-11e9-9663-32f48c7fa80e.png)

Is this expected?

**Comment by rmullan** [comment]
This is the same as :https://github.com/IBM/carbon-components-react/issues/1786

Cheers :)

**Comment by IdanAdar** [comment]
@asudoh Hello. We see this is regressed... The latest 6. release fails with this error. we reverted to 6.106 and the tests pass again.

**Comment by asudoh** [comment]
Hi @IdanAdar my apologies for the inconvenience. Given you brought up a test I guess you are doing Emzyme `find('TextInput')`? If so, I suggest replacing it with find(TextInput)` where `TextInput` is the React component. Hope it helps!

**Comment by IdanAdar** [comment]
Unfortunately this did not help.
https://github.ibm.com/security-services/certificate-manager-dashboard/blob/develop/test/unit-tests/client-unit-tests/components/Settings/NotificationChannel.test.js
```
 1) RequestInfo
       renders as expected
         has 3 children (legend, description and form):
     AssertionError: expected 'ForwardRef' to include 'TextInput'
      at Context.<anonymous> (test/unit-tests/client-unit-tests/components/Order/RequestInfo.test.js:46:66)
  

  2) NotificationsChannel
       renders as expected
         correct UI (row with 6 cells) of existing channel:

      AssertionError: expected 'settings.notifications.testConnection' to deeply equal '<Button />'
      + expected - actual

      -settings.notifications.testConnection
      +<Button />
      
      at Context.<anonymous> (test/unit-tests/client-unit-tests/components/Settings/NotificationChannel.test.js:81:29)
  

  3) NotificationsChannel
       renders as expected
         correct UI (row with 6 cells) of new channel:
     ReferenceError: TextInput is not defined
      at Context.<anonymous> (test/unit-tests/client-unit-tests/components/Settings/NotificationChannel.test.js:100:43)
  

  4) NotificationsChannel
       functions as expected
         on edit:
     ReferenceError: TextInput is not defined
      at Context.<anonymous> (test/unit-tests/client-unit-tests/components/Settings/NotificationChannel.test.js:182:34)

```

**Comment by asudoh** [comment]
Did you import `TextInput` in your test? 3)4) seems to tell otherwise.
