### ISSUE TITLE
Tab: content class name without prefix

### ISSUE THREAD

**Issue by diego-codes** [IBM/carbon-components-react#1790]
## Detailed description

> Describe in detail the issue you're having.

The `Tab` component has styles for a class name selector that is `.tab-content` I expect all class names in the design system to be prefixed.

> Is this issue related to a specific component?

Yes, `Tab`

> What did you expect to happen? What happened instead? What would you like to see changed?'

I expect the all tab related class names to include the set prefix (ie `bx--`)

> What version of the Carbon Design System are you using?

9-something

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Security

**Comment by joshblack** [comment]
Moved it over here @diego-codes! 👍
