### ISSUE TITLE
Datatable with OverflowMenu and pagination

### ISSUE THREAD

**Issue by nunomaia** [IBM/carbon-components-react#1791]
## Detailed description

When using a DataTable with PaginationV2 and an OverflowMenu, when OverflowMenu is trigged the last row, OverflowMenu is displayed below PaginationV2 with scrollbars. 

![untitled1](https://user-images.githubusercontent.com/771138/51701574-a1a12d80-2009-11e9-84c9-07aa5a82aed5.png)

![untitled2](https://user-images.githubusercontent.com/771138/51701582-a5cd4b00-2009-11e9-8df1-31e403428248.png)

**Comment by asudoh** [comment]
Hi :wave: would you want to create a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox? Another thing I'm wondering if you have `true` set to `floatingMenu` prop. Thanks!

**Comment by nunomaia** [comment]
You are correct, missing floatingMenu prop. Thanks a lot
