### ISSUE TITLE
Allow radio button in data table

### ISSUE THREAD

**Issue by sgraden** [IBM/carbon-components-react#1796]
Data tables allow checkboxes, but should also allow some form of radio select (see images below)

## Detailed description

This would be a new feature I believe. 

Currently checkboxes are a component that can be included within the data table.
https://www.carbondesignsystem.com/components/data-table/code#skip-to-content

We are working on a feature/service and are wanting to allow the user to select a single item in a table which would then enable additional options that they can do with that selected item. Anyways, that means it is a single select at a time in a data table.
We have designed something like this:
![image](https://user-images.githubusercontent.com/6685872/51762034-423c2f80-2094-11e9-858f-7dcd4f79a32f.png)

This function is possible in structured lists, but then we aren't able to complete pagination as well. Would be nice to have something like it enabled in a standard data table.

**Comment by emyarod** [comment]
cc @IBM/carbon-designers just to confirm, is this proposal one that we want to incorporate in the core library?
