### ISSUE TITLE
SkeletonText not work on IE with width error

### ISSUE THREAD

**Issue by gracelo** [IBM/carbon-components-react#1806]
## Detailed description

> Describe in detail the issue you're having.
My react code has:
`<SkeletonText className='someName' paragraph={true}/>`

and IE11 gives me error with width.includes not supported.
![image](https://user-images.githubusercontent.com/25369764/51996694-48128600-2483-11e9-9981-00202b5e6c89.png)

> Is this issue related to a specific component?
SkeletonText

> What did you expect to happen? What happened instead? What would you like to see changed?
no error and render fine

> What browser are you working in?
IE11

> What version of the Carbon Design System are you using?
"carbon-components-react": "^6.12.1"
but the source seem to be the same for those lines in the latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud Console

**Comment by asudoh** [comment]
The application needs a polyfill of `Array.prototype.includes()`. The full list of required polyfills can be found at: https://github.com/IBM/carbon-components-react/blob/v6.39.0/.storybook/polyfills.js
