### ISSUE TITLE
customize sortRow in DataTable does not work when sortStates is 'NONE'

### ISSUE THREAD

**Issue by zhuzmzm** [IBM/carbon-components-react#1833]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. use the sortRow in DataTable as we need to do all data sorting in grid but current sorting is used for current page
2. cusotomized sortRow in my code, after click the sorting button two times, i find the sortStates is 'NONE', so can not trigger sortRow callback funtion. 

here is the code i list below:
carbon-components-react/src/components/DataTable/state/sorting.js
![1](https://user-images.githubusercontent.com/42019585/52315891-e064b980-29f3-11e9-8ea2-1a42d0481ad6.jpg)

If the NONE state is useful in our code?

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting - Would you try creating a reduced test case based on https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox?

**Comment by zhuzmzm** [comment]
@asudoh Hi, i created an example for your refrence. https://codesandbox.io/s/5vw1860p2k.

**Comment by asudoh** [comment]
Thanks @zhuzmzm! Seems that what you want to do is handling sorting by your own. Is it correct...?

**Comment by zhuzmzm** [comment]
Yes, i want to do all data sorting, not only the current page.

**Comment by asudoh** [comment]
OK [direct assignment of `onClick()` to `<TableHeader>`](https://github.com/IBM/carbon-components-react/tree/v6.39.0/src/components/DataTable#prop-getters) seems to be the closest to your need. Don't hesitate to let us know if it doesn't work for you - Thanks!

**Comment by zhuzmzm** [comment]
@asudo Could you please help give an example on https://codesandbox.io/s/5vw1860p2k? Thanks!

**Comment by asudoh** [comment]
You can start adding `onClick={this.sortRow}` and `sortDirection={this.state.sortDirection}` to `<TableHeader>` and remove `sortRow` prop from `<DataTable>`. That said, your component manages sorting direction by yourself. Also your `sortRow` method turns to be a simple event handler and thus the argument list will be different. Hope this helps!

**Comment by zhuzmzm** [comment]
Thanks very much! I will try to have a test.
