### ISSUE TITLE
Request a composable notification component option for InlineNotification

### ISSUE THREAD

**Issue by yiwenh** [IBM/carbon-components-react#1834]
### Summary
We are trying to implement a notification that contains an action button:
<img width="924" alt="screen shot 2019-02-06 at 10 38 04 am" src="https://user-images.githubusercontent.com/18095052/52317615-b0b9af80-29fb-11e9-92fc-62ffc5fe728c.png">
According to doc, it takes a `children` prop:
<img width="692" alt="screen shot 2019-02-05 at 4 49 49 pm" src="https://user-images.githubusercontent.com/18095052/52317672-ef4f6a00-29fb-11e9-8519-1d825d744abb.png">
However I'm not able to get the `children` to show, with code like:
```
<InlineNotification
     kind="warning"
     title="Notification title"
     subtitle="Subtitle text goes here."
     iconDescription="describes the close button"
     onCloseButtonClick={()=>{}}
     hideCloseButton={true}>
     <div>I am childen text</div>
</InlineNotification>
```

Is action buttons inside InlineNotification a supported design?  If so, could the InlineNotification component be updated to add this feature?  Thanks.

### Justification
Providing an action button within the notification is a convenience and straightforward way for a user to take suggested/corrective actions.

### Desired UX and success metrics
User is able to perform actions provided in InlineNotification box.

### "Must have" functionality
Support a composable notification component option.

### Specific timeline issues / requests
no

### Available extra resources
I have some experience using react carbon components and would be interested in contributing to the development of this feature.

**Comment by asudoh** [comment]
@IBM/carbon-designers Does this kind of notification UI make sense...? Thanks!

**Comment by aagonzales** [comment]
Yes adding a button/action to a notification makes since. I think we would prefer a different button though. Perhaps a ghost button instead. Like this example (from another team)
![image](https://user-images.githubusercontent.com/11670886/52431868-b3390980-2ace-11e9-8aa3-77958b1bbaa6.png)
