### ISSUE TITLE
Search component should have option of searching on hit of enter

### ISSUE THREAD

**Issue by arnajdas1992** [IBM/carbon-components-react#1853]
### Summary

Please describe your request in one or two sentences.
The search functionality right now is on each key stroke. The user should have an option of having the search on every keystroke or on hit of enter button.

Clarify if you are asking for both design and development, or just design, or just development.
Just development

### Justification

The feature we are working on, has a requirement of this functionality. On hit of enter button, we call an API with the entered values as input. Right now, on every keystroke the API is called, which is not required

**Comment by emyarod** [comment]
hi @arnajdas1992 thanks for submitting this ticket! would wrapping your `<Search>` component in a `<form>` and providing a handler for `onSubmit` handle your use case here?

**Comment by arnajdas1992** [comment]
Hi @emyarod . I think that should handle the case as long as the user has the option to call the function on hit of enter or submit and not on every keystroke.

**Comment by emyarod** [comment]
@arnajdas1992 if I'm not mistaken, the handling of every keystroke should be contained in the `onChange` method right? if I am misunderstanding, if you could please provide a [Code Sandbox](https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox) illustrating what you mean that would be very helpful

**Comment by arnajdas1992** [comment]
@emyarod - I used the `onKeyDown` function to fix this issue. This function passes what key was pressed, and so can be used to check if `Enter` was pressed. The `onChange` function just passes what value is typed. May be the documentation can be updated to include this. Closing this issue as any new feature is not required from our side as of now. Thankyou
