### ISSUE TITLE
DataTable: how to center th content

### ISSUE THREAD

**Issue by devniel** [IBM/carbon-components-react#1892]
Hello,

I have a problem trying to center the content of the `thead` cells for a DataTable with selection options, the content (a button) occupies all the cell content and have a flex display property.

I have tried many things, using flex in the `thead` with other changes to the button could work in the  `inspector` but in a new render of the table it will got broken. It seems that the non-invasive solution seems that the inner content needs a wrapper, just a `<div/>` enveloping the `<button/>`, or maybe passing all the button css rules to an inner wrapper inside the `button`, but it'll require changing `carbon-components` styles.

![image](https://user-images.githubusercontent.com/1231888/52977312-d0a58780-339a-11e9-8666-23b1de2b918f.png)

**Comment by asudoh** [comment]
Hi @devniel thank you for reporting! Any more info on why you seem to think style override won't work?

**Comment by devniel** [comment]
I have found that if there is a custom class provided to the `th`, the button also use the same, maybe it's causing some kind of conflict.

https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/TableHeader.js#L80

**Comment by asudoh** [comment]
OK one thing I can suggest is fiddling with DOM inspector (as you seem to have been doing already), create a selector that matches where you want to change the style, and deal with selector priority order. Hope it makes sense to you - Thanks!

**Comment by devniel** [comment]
That approach could work in a common context, but when tables are involved some CSS things don't work as usual.

**Comment by asudoh** [comment]
Seems that the first step is setting something like `display: inline-block` to the `<button>` - In this way, you can ensure the `<button>` won't take the whole width of `<th>` and `text-align: center` there changes the alignment of `<button>`. Wrt CSS class assignment of `<TableHeader>` applied to both `<th>` and `<button>` doesn't make sense to me either, but I guess you can differentiate the selector by the tag. Hope this helps - Don't hesitate to let us know if you have any further questions - Thanks!
