### ISSUE TITLE
Experimental multi select: Remove "selected item going top" feature

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#1897]
From @laurenmrice at https://github.com/IBM/carbon-components/pull/1752#pullrequestreview-204880585:

When selecting Option 2 first, Option 2 jumps to the top of the list in the dropdown, it should stay where it is in the dropdown list and should not move.
<img alt="screen shot 2019-02-18 at 10 48 31 am" width="358" src="https://user-images.githubusercontent.com/43969356/52965603-d5eade00-336a-11e9-9b69-cb8c9aac27f8.png">

**Comment by emyarod** [comment]
do we want to support the option to bump selected items to the top of the list or do we want to remove that behavior altogether?

**Comment by laurenmrice** [comment]
@emyarod Yes we want to remove this behavior for the multiselect. I know this is how it was implemented in v9 component but the correct behavior should be that it does not bump up the selections, they should stay in place.

**Comment by emyarod** [comment]
thanks for the clarification @laurenmrice ! I'm ok with making that change, and I guess my only concern is if it's been the default behavior for a significant amount of time there may be some requests for that behavior to at least remain as an option for users. But I'm also ok with refusing those requests if it's the direction we want to enforce in v10 onwards
