### ISSUE TITLE
DropdownV2 highlights all items if items have no id property and selectedItem is used

### ISSUE THREAD

**Issue by toeikmei** [IBM/carbon-components-react#1898]
Using the DropdownV2 component with items that have no id property and setting the `selectedItem` results in items that all have the highlighted class attached. This is due to the check in https://github.com/IBM/carbon-components-react/blob/master/src/components/DropdownV2/DropdownV2.js#L191

If `item` and `selectedItem` both have no id property the check becomes `undefined === undefined` which is true. 

![image](https://user-images.githubusercontent.com/11832153/53037529-bba02580-347a-11e9-807c-f6f4dc982164.png)

Work around for this is to add an id to selectedItem and/or the other items

https://codesandbox.io/s/n5x6jj8p2j

**Comment by ricardo-jsx** [comment]
It's possible to know if the `isActive` property of a MenuItem is truthy with a strict equality operator, which is being used on the following line https://github.com/IBM/carbon-components-react/blob/master/src/components/DropdownV2/DropdownV2.js#L188. Maybe a pull request using the same logic in the `isHighlighted` will solve this issue.
