### ISSUE TITLE
[Carbon X] Ranged DatepickerInput does not match design kit (no icon)

### ISSUE THREAD

**Issue by jendowns** [IBM/carbon-components-react#1904]
## Detailed description

(NOTE: I'm going by what's in the latest Carbon Design System V0-beta sketch file, so please let me know if things have changed & I'm mistaken here 😅)

In the latest design kit shared in the last week or so, the ranged `DatePicker` component has icons included within the `DatePickerInput`:

<img width="637" alt="screen shot 2019-02-21 at 10 50 17 am" src="https://user-images.githubusercontent.com/9057921/53186537-ca93ee80-35c6-11e9-9cbf-67093b47febf.png">

However, in the Carbon X `DatePickerInput` component, that icon is not being applied to `datePickerType="range"` variations: https://github.com/IBM/carbon-components-react/blob/master/src/components/DatePickerInput/DatePickerInput.js#L81

```javascript
const datePickerIcon = (() => {
  if (datePickerType !== 'single') {
    return;
  }
  if (componentsX) {
    return (
      <Calendar16
        className={`${prefix}--date-picker__icon`}
        aria-label={iconDescription}
        onClick={openCalendar}
        role="img"
      />
    );
  }
  return (
    <Icon
      name="calendar"
      className={`${prefix}--date-picker__icon`}
      description={iconDescription}
      onClick={openCalendar}
      focusable="false"
    />
  );
})();
```

You can see right at the top, the logic `if (datePickerType !== 'single') { return; }` prevents an icon from being added for `range` variations of the `DatePicker`.

**Comment by jendowns** [comment]
Just to add, I realize the solution here (assuming this should follow the latest design guide) is not as simple as just removing `if (datePickerType !== 'single') { return; }` 😅 The icon ends up getting added if you do that, but it is in the label area:

![screen shot 2019-02-21 at 10 58 33 am](https://user-images.githubusercontent.com/9057921/53186951-a5ec4680-35c7-11e9-879e-77698df025d2.png)

So there would need to be additional adjustments, beyond removing the if statement. 🤔

**Comment by jendowns** [comment]
I opened an issue to fix the `.#{$prefix}--date-picker__icon` style rule, which I believe is a first step to resolving this issue: https://github.com/IBM/carbon-components/pull/1876

**Comment by jendowns** [comment]
One more note:

Based on the design kit, I believe that this logic (for the `single` type)...
https://github.com/IBM/carbon-components-react/blob/master/src/components/DatePickerInput/DatePickerInput.js#L81

```javascript
if (datePickerType !== 'single') {
  return;
}
```

Should actually be... 

```javascript
if (datePickerType === 'simple') {
  return;
}
```

Instead. Because the design kit shows calendar icons for all variations except for the `simple` variation:

<img width="786" alt="screen shot 2019-02-21 at 11 15 41 am" src="https://user-images.githubusercontent.com/9057921/53188153-5f4c1b80-35ca-11e9-9583-36853a851a15.png">

**Comment by asudoh** [comment]
Hi @jendowns 👋 thank you for the style fix - Wrt the logic you are referring to, though I don't know the historical reason behind it, I think it's for coping with whether `<DatePicker>` or `<DatePickerInput>` handles calendar icon for single/range variants: https://github.com/IBM/carbon-components-react/blob/v6.97.0/src/components/DatePicker/DatePicker.js#L446-L455 - Wondering if it makes sense to you?

**Comment by jendowns** [comment]
Good point @asudoh! I'm not 100% sure about the historical context either, but it looks like the logic for adding an icon for the Carbon X version of the `DatePicker` only exists in `DatePickerInput`, given that the lines (https://github.com/IBM/carbon-components-react/blob/v6.97.0/src/components/DatePicker/DatePicker.js#L446-L455) are passed over if `componentsX === true` due to line 447...


So I'm thinking that for the logic in the `DatePickerInput` (https://github.com/IBM/carbon-components-react/blob/master/src/components/DatePickerInput/DatePickerInput.js#L81), we'd need to keep it still compatible with any existing versions and still make it work for Carbon X 🤔 

What if we update the logic from...

```javascript
if (datePickerType !== 'single') {
  return;
}
```

to this

```javascript
/// Keeps it compatible with existing code
/// but doesn't exclude icons from Carbon X version
if (!componentsX && datePickerType !== 'single') {
  return;
}
/// Prevents the icon from being applied to Carbon X version's `simple` type.
/// I know this seems wordy but in my experiments just now,
/// icons *are* applied to `simple` (when they shouldn't be, per the screenshots
/// I posted above from the design kit). So this prevents that.
if (componentsX && datePickerType === 'simple') {
  return;
}
```

What do you think? 🤔

**Comment by emyarod** [comment]
hi @jendowns thanks for reporting these! The React components will be slightly behind the vanilla components and will be addressed soon after the vanilla components have been finalized. There are still a few open tickets for the vanilla date picker so it's likely the solutions for these issues will change and come up over the next week or so

**Comment by jendowns** [comment]
Thankyou @emyarod -- I'm part of the Security team & we are very sensitive to the fact that these components are experimental. We are sponsors users who are currently testing the Carbon X components in a product context (specifically a React environment). 

I've seen some of the issues in the vanilla repo (and opened a few myself 😅), but this issue deals with proper usage of the `componentsX` flag to render a calendar icon on the `DatePicker` React component (specifically, inside `DatePickerInput`). None of the issues in the vanilla repo, with the exception of a positioning issue I opened & suggested a fix for (https://github.com/IBM/carbon-components/pull/1876) apply to this logic, as far as I can tell.

With regards to this React component, it looks like a first pass was complete but the logic doesn't quite match the design spec. Our designers are following the Carbon X design kit & have some expectations around icon placement... this issue + my suggested fix (https://github.com/IBM/carbon-components-react/issues/1904#issuecomment-466095478) will help us keep moving 🎉  I believe the fix will be very simple & not interfere with any additional updates being made here, or in the vanilla repo.

**Comment by emyarod** [comment]
yes if I'm not mistaken it seems there are two different issues presented in this ticket. The first is about the missing calendar icon for some date picker variants, referenced in the title of this issue, which we can address. There's also another issue about the positioning of the icons for some other variants. I believe the 2nd issue is currently being addressed in the vanilla repo (avoiding absolute vertical positioning to account for different label lengths). If I am misunderstanding your points please let me know

**Comment by jendowns** [comment]
> There's also another issue about the positioning of the icons for some other variants. I believe the 2nd issue is currently being addressed in the vanilla repo (avoiding absolute vertical positioning to account for different label lengths).

Ah, so it looks like you opened your issue & PR (https://github.com/IBM/carbon-components/issues/1877) and hour *after* I opened this issue + a related PR (https://github.com/IBM/carbon-components/pull/1876) 😅 

Could you comment in https://github.com/IBM/carbon-components/pull/1876 to reference the change in direction you took?

As for this issue, I still believe it is very relevant and worth resolving. Per design spec (screenshots), calendar icons should appear for all variations except the `simple` variation (whereas currently, the Carbon X version has no icons except for the `simple` type). This issue calls that out. I can update the title if that would be more helpful?

**Comment by emyarod** [comment]
sure, I left a comment on your PR, and yes I agree this issue needs to be resolved. In my initial response I just wanted to inform you that the fix would probably not be immediate and would likely come after the vanilla component has incorporated requested changes from our recent component audits. This way it's a bit easier for us to keep track of the necessary changes that need to be ported over to our React component in addition to tickets already in our React repo issue tracker, if that makes sense. Of course if there are critical breaking issues I can address it sooner rather than later, just trying to triage our open issues
