### ISSUE TITLE
RadioButton still not working inside Toolbar

### ISSUE THREAD

**Issue by asfordmatt** [IBM/carbon-components-react#1916]
This bug was recently marked as resolved, but the issue is not fixed:
https://github.com/IBM/carbon-components-react/issues/1885

See here:
https://codesandbox.io/s/148z6wn694
I've updated it to use v6.98.2, and the onChange handler is still not firing. Should this work or is there something wrong with the code?

I see this warning in the console:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `OverflowMenu`.
    in ToolbarOption (created by OverflowMenu)
    in ul (created by OverflowMenu)
    in div (created by ClickListener)
    in ClickListener (created by OverflowMenu)
    in OverflowMenu (created by App)
    in ToolbarItem (created by App)
    in div (created by Toolbar)
    in Toolbar (created by App)
    in App
```

**Comment by asfordmatt** [comment]
FYI @asudoh @emyarod

**Comment by emyarod** [comment]
thanks for the update on this issue @asfordmatt. for now, it seems you can render `<OverflowMenu>` with the `floatingMenu` prop and it should work as a temp fix, and I will look into this for non-floating menus

**Comment by emyarod** [comment]
in any case it would probably be best to use floating menus from here on out, as we may look into deprecating non-floating menus

**Comment by asfordmatt** [comment]
Thanks @emyarod I can switch to floatingMenu. Presumably I shouldn't be getting that 'refs' warning? Can you use this issue to address that?

**Comment by emyarod** [comment]
@asfordmatt #1920 addresses this ticket. I'll open a new one for the console warnings
