### ISSUE TITLE
Need to provide a way to add custom text to area-label for Icon component under TableHeader->th->button->Icon

### ISSUE THREAD

**Issue by ajaysikdar** [IBM/carbon-components-react#1940]
We have a requirement to translate area-label text for Icon which comes under TableHeader->th->button->Icon.
The component is DataTable.
At present, I don't see any way to pass area-label text to the Icon.

**Comment by asudoh** [comment]
Hi 👋 `<TableHader>` has `translateWithId` prop, where you can provide an instance of [`react-i18next`](https://github.com/i18next/react-i18next) or a compatible library. Make sure it has a translation for `carbon.table.header.icon.description`. Hope this helps!

**Comment by ajaysikdar** [comment]
Thanks @asudoh . It is working.
