### ISSUE TITLE
DropdownV2 - label created by titleText prop doesn't follow carbon-design rules, when dropdown is disabled.

### ISSUE THREAD

**Issue by tomkdgun** [IBM/carbon-components-react#1941]
DropdownV2 - label created by adding **titleText** prop, doesn't follow carbon-design rules, when dropdown is disabled. Currently label has same color regardless of disabled value.

According to carbon design rules, label for disabled input element should have different color.
From ANNA GONZALES: "In V9 the label should be at 50% opacity in V10 the label should be using the `$disabled-02` color toke"

https://ibm-analytics.slack.com/archives/C0M053VPT/p1550691220019200

Version info:
    "carbon-components": "9.76.7",
    "carbon-components-react": "6.98.0",
    "carbon-icons": "7.0.7",

**Comment by asudoh** [comment]
@aagonzales Should the color of "This is not a dropdown title" thing below be changed when dropdown is disabled...? Thanks!

![image](https://user-images.githubusercontent.com/1259051/53704088-4eb66380-3e5c-11e9-844a-14a903de042f.png)

**Comment by emyarod** [comment]
I believe this is fixed in https://github.com/IBM/carbon-components/pull/1968 and should be addressed when we complete our form component audit for the React repo

**Comment by aagonzales** [comment]
The component shown above is v9, which if disabled should be at 50% opacity. 

IBM/carbon-components#1968 is addressing V10 issues

**Comment by emyarod** [comment]
@aagonzales do the same disabled label styles and tokens apply to the helper text as well?

**Comment by aagonzales** [comment]
Yes, same color applies to the helper text as well.

**Comment by shinytoyrobots** [comment]
Make sure this is added to v10 form controls (not just data table). That's priority over v9 bug fix.
