### ISSUE TITLE
FileUploader: Can select all kinds of file on IE11, Edge, Safari even with 'accept' specified

### ISSUE THREAD

**Issue by hyzhangIBM** [IBM/carbon-components-react#1947]
Issue with `FileUploader` component

**Version**:
"carbon-components-react": "6.71.0"

**Current behavior**:
Passed `.xlsx` to `accept`, however it still let me choose all kinds of file types on **IE 11**, **Edge** (Windows, Version: Microsoft Edge 38.14393.2068.0) and **Safari** (Mac, Version: 11.0.3 (13604.5.6)), but it works fine on Chrome (Mac, Version: 70.0.3538.110) and Firefox (Mac)

**Expect Behavior**:
On IE11, Edge and Safari, the file uploader should only let user select the file types which are specified in the `accept` prop.

An example of this issue: 
https://codesandbox.io/s/zkm2qwoyjp
(This doesn't work correctly on Safari Version 11.0.3 (13604.5.6), but works fine on Version 12.0.3 (14606.4.5))

**Comment by emyarod** [comment]
hi @hyzhangIBM thanks for reporting this! I believe these are known limitations of the browser versions you listed: https://caniuse.com/#feat=input-file-accept, but please let me know if I have misunderstood the issue!

**Comment by hyzhangIBM** [comment]
Hi @emyarod ,

Thank you for the reply! 
and thanks for providing the link, this issue can be closed.
Thanks!
