### ISSUE TITLE
OverflowMenuItem: Potential breaking change with onClick

### ISSUE THREAD

**Issue by ryanomackey** [IBM/carbon-components-react#1951]
## Detailed description

<img width="477" alt="image" src="https://user-images.githubusercontent.com/17710824/53606208-a95f6f00-3b7f-11e9-9b96-7a286ee35db6.png">

So, it looks like if `<OverflowMenuItem />` isn't a direct descendant of `<OverflowMenu />`, the `closeMenu/handleClick` prop methods lose context.

This is a breaking change for me, and I _can_ refactor it (since there's probably an argument that I shouldn't be doing that), but I thought I'd see what y'all thought.

## Steps to reproduce the issue

1. Visit this sandbox: https://codesandbox.io/s/k2wqok1v57
2. Click on the `<OverflowMenuItem />`
3. Code go boom

**Comment by asudoh** [comment]
@ryanomackey Thank you for reporting - As you said, `<OverflowMenu>` has to be a direct child of `<OverflowMenu>` for the communication between them. Made a change to the code to avoid NPE and better communicate you on the requirement.
