### ISSUE TITLE
Date picker (range): The dropdown hould be aligned to the edge of the start range input not the end range input

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#1987]
From @aagonzales at #1966:

When open the end range calendar, the calendar should be aligned to the edge of the start range input not the end range input.

This is wrong:
![image](https://user-images.githubusercontent.com/11670886/53982479-a8c45c80-40da-11e9-890e-7fb52a92d3e2.png)

**Comment by asudoh** [comment]
Trying to get this into `v10` given flatpickr/flatpickr#1693 has been fixed and we are waiting for a Flatpickr release.

**Comment by aagonzales** [comment]
Why does it work in vanilla but not in react?

**Comment by asudoh** [comment]
@aagonzales Good question - We have a bunch of work-around code (which is, creating an intermediate input box that interacts with Flatpickr, separate from the input box user interacts on IIRC) to get around this, which has caused many other user-facing issues. That has raised a question you can see at: https://github.com/IBM/carbon-components-react/issues/1899#issuecomment-469122138

Given those, we are trying to solve issues in Flatpickr side instead of working around issues in our side, for ones that arose from Flatpickr.

**Comment by joshblack** [comment]
cc @dakahn if we are pinning flatpickr to a previous version, does that mean we will lose out on the update posted above?

**Comment by dakahn** [comment]
@joshblack @asudoh the plan moving forward is to pin Flatpickr to 4.3 for keyboard support and implement the SSR work missing from a later patch on our end before code freeze. **This update wouldn't include whatever fixes are being talked about here.** Having Datepicker be _usable and minimally accessible_ for v10 is the goal.

**Comment by shinytoyrobots** [comment]
Won't fix this specific issue, as we are reassessing use of flatpickr, and this fix is reliant on them.
