### ISSUE TITLE
DatePicker Calendar year is showing additional up and down arrows

### ISSUE THREAD

**Issue by ketanb3** [IBM/carbon-components-react#2001]
## Detailed description

> Describe in detail the issue you're having.

![image](https://user-images.githubusercontent.com/6772611/54158839-d5051380-4421-11e9-9b3f-43f10ad5fc09.png)

> Is this issue related to a specific component?
DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected to see only blue up and down arrows instead I am seeing additional arrows on top of year element.

> What browser are you working in?

Tried on MacOS Mojave 1. Chrome 2. Firefox (Both browsers with the latest version)

> What version of the Carbon Design System are you using?
 "carbon-components-react": "^6.99.1",
"carbon-components": "^9.69.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Working on IBM internal project. 

## Steps to reproduce the issue

Add DatePicker range component and check the calendar. 

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

## Additional information

- Screenshots or code

Attached above.

Code screenshot is here: (Code generated by Carbon)
![image](https://user-images.githubusercontent.com/6772611/54159053-6a080c80-4422-11e9-8ec6-029cd2e7841f.png)

- Notes

**Comment by vpicone** [comment]
This comes from using an input with type: number. There’s no official way of styling it away. We should instead use an input with type of text and then use the pattern attribute to check. 

I think this input is generated by the flatpickr library.

**Comment by asudoh** [comment]
Thanks @vpicone for finding this out! Let's do it: #2004

**Comment by ketanb3** [comment]
Yes upgrading carbon to latest version fixed this problem. Thank you.
