### ISSUE TITLE
DatePicker / DatePickerInput not rendering correctly

### ISSUE THREAD

**Issue by rmartinez213** [IBM/carbon-components-react#2002]
## Summary

I began using the Data Picker component with the use of "range with calendar and min/max dates" I followed closely with the react documentation, however my output is different than what is shown in the documentation. It somehow doesn't render the calendar icon and month/year.

I noticed that the 'labelText' prop does not provide the calendar icon either.

Also, the month & year did not render. Instead 

> 'I'
> 'W'
> 'TH'

Sorry I am quite new to React, however I was not sure if this was a bug or just an error on my part. Any help would be greatly appreciated!

## Screenshot
Output: 
<img width="140" alt="Capture" src="https://user-images.githubusercontent.com/25447970/54163077-00353600-4415-11e9-8dc1-63d70c3ca65f.PNG">

Expected: 
<img width="235" alt="Capture2" src="https://user-images.githubusercontent.com/25447970/54163783-602cdc00-4417-11e9-8618-c39e1712998d.PNG">

## Relevant information

This is my code from the picture above:

`<DatePicker
                    minDate="1/1/2018"
                    maxDate="8/31/2018"
                    datePickerType="range"
                    dateFormat="m/d/Y"
                >
                    <DatePickerInput id="date-picker-input-id-start" labelText='Start Date' placeHolder='mm/dd/yyyy' />
                    <DatePickerInput id="date-picker-input-id-end" labelText='End Date' placeHolder='mm/dd/yyyy' />
                </DatePicker>`

## Version 

"carbon-components-react": "^6.92.1",
"carbon-icons": "^7.0.7",

**Comment by asudoh** [comment]
Hi 👋 do you want to create a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox? Meanwhile, you can try inspecting DOM with Chrome DevTools and comparing http://react.carbondesignsystem.com/?selectedKind=DatePicker&selectedStory=range%20with%20calendar%20and%20min%2Fmax%20dates and your application. Hope this helps!

**Comment by rmartinez213** [comment]
So after comparing my application with same one on the documentation page I see a few differences. 

Output: 

<img width="709" alt="flatpickr" src="https://user-images.githubusercontent.com/25447970/54167079-63c75f80-4425-11e9-9f6e-3bb4d763ab7d.PNG">

Expected: 

<img width="568" alt="flatpickr2" src="https://user-images.githubusercontent.com/25447970/54167100-75106c00-4425-11e9-8a8c-1659147893f2.PNG">

Also, I recreated my code using code pen. Could my issue possible be because of the css?

https://codesandbox.io/s/ll7w0955zq

**Comment by asudoh** [comment]
Hi 👋 In [your codepen](https://codesandbox.io/s/ll7w0955zq) the date picker style looks correct, which means that it does _not_ reproduce the issue you may be facing. When you inspect DOM with Chrome DevTools, focus on Styles tab. It shows that styles are effective and what styles are not. Hope this helps!
