### ISSUE TITLE
Icons: Decide whether we just deprecate legacy <Icon> for v10 or remove in v10

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#2003]
## Summary

Need to see whether we just deprecate legacy `<Icon>` for v10 or remove in v10. The former approach allows consumer to use alternate icon with legacy icon data structure, but may cause a false impression that usage of our legacy icon in v10 is an accepted UX pattern.

**Comment by joshblack** [comment]
I think we can deprecate it to make interop a little easier 👍 Nothing wrong with folks using it until v11, and we might want to hold off on folks migrating to the dedicated package until we feel good that the work is a suitable solution 👍

**Comment by joshblack** [comment]
I'm also down for leaving `<Icon>` as-is for now and letting people still use that while we figure out migration strategy 👍

**Comment by asudoh** [comment]
OK thank you for your reply @joshblack! `<Icon>` as-is makes sense until we provide a clear migration path.
