### ISSUE TITLE
SkeletonText warning on React

### ISSUE THREAD

**Issue by gracelo** [IBM/carbon-components-react#2013]
I use SkeletonText like:
```
      { resources !== false && !resources &&
        <SkeletonText className='my__loading' paragraph={true}/> }
```

with React Server rendering.
After client is rendered, I see error on console:
```
Warning: Prop `style` did not match. Server: "width:calc(100% - 19px)" Client: "width:calc(100% - 68px)"

warningWithoutStack | @ | VM871 client-details.js:4269
-- | -- | --
  | warnForPropDifference | @ | VM871 client-details.js:11227
  | diffHydratedProperties | @ | VM871 client-details.js:11909
  | hydrateInstance | @ | VM871 client-details.js:12689
```

Chrome
"carbon-components-react": "^6.12.1",

I do not have any related styling for SkeletonText.

**Comment by asudoh** [comment]
@alisonjoseph Seems that we generate random width for skeleton text, is it correct? If so I can imagine this problem (out-of-sync SSR/CSR rendering results) would happen. Probably pre-defined set of widths? Thoughts...? Thanks!

**Comment by alisonjoseph** [comment]
Correct, we are setting random widths so that if we have a block with many lines of text they aren't all the same size. However, we could still achieve this random look by setting pre-defined random widths.
