### ISSUE TITLE
TextInput invalid state doesn't have background SVG

### ISSUE THREAD

**Issue by rave-ibm** [IBM/carbon-components-react#2014]
## Detailed description

> Describe in detail the issue you're having.
The TextInput doesn't show the background svg as expected and shown in Carbon design 

> Is this issue related to a specific component? Yes

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in? Chrome 72

> What version of the Carbon Design System are you using?
├─ carbon-components-react@6.107.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

## Additional information
Expected:

<img width="363" alt="Screen Shot 2019-03-14 at 11 19 44 AM" src="https://user-images.githubusercontent.com/30185076/54378663-2b5e9600-465e-11e9-9a5f-51a2406c720e.png">

Actual: 
<img width="512" alt="Screen Shot 2019-03-14 at 11 03 55 AM" src="https://user-images.githubusercontent.com/30185076/54378642-1eda3d80-465e-11e9-84e5-e7cc8e1130b5.png">

- Screenshots or code
- Notes

**Comment by emyarod** [comment]
hi @rave-ibm, thank you for reporting! There is an open pull request to implement this change already, and you can see its progress here https://github.com/IBM/carbon-components-react/pull/1990
