### ISSUE TITLE
Question: TextInput has its fixed min-width

### ISSUE THREAD

**Issue by vidhi11** [IBM/carbon-components-react#2015]
Issue: In-order to give input field width, i have to give two fields `width` and `min-width`. Because TextInput field has `min-width` defined in CSS which over-writes custom `width`. 

Question: Is this bug?

CodePen: https://codesandbox.io/s/84ljjk1v58

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! As the `min-width` we set tells, we don't recommend creating a text input smaller than that width. Hope this explains!
