### ISSUE TITLE
Toggles with the same ID do not function correctly

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-components-react#2017]
## Detailed description

> Describe in detail the issue you're having.

When multiple `Toggle` elements exist, with the same `id`, then only the first `Toggle` is ever affected by the user's interaction.

> Is this issue related to a specific component?

`Toggle` (and likely `ToggleSmall`)

> What did you expect to happen? What happened instead? What would you like to see changed?

Whether or not a multiple `Toggle` controls use the same ID, the ID should affect the behaviour of the control.  Clicking any individual toggle should only affect itself.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest in git

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Maximo

## Steps to reproduce the issue

Here's a story that clearly shows the issue

```jsx
.addWithInfo(
    'Default',
    `
      Toggles are controls that are used to quickly switch between two possible states. The example below shows
      an uncontrolled Toggle component. To use the Toggle component as a controlled component, set the toggled property.
      Setting the toggled property will allow you to change the value dynamically, whereas setting the defaultToggled
      prop will only set the value initially.
    `,
    () => (
    <div>
      <Toggle {...toggleProps} className="some-class" id="toggle-1" />
      <Toggle {...toggleProps} className="some-class" id="toggle-1" />
      <Toggle {...toggleProps} className="some-class" id="toggle-1" />
    </div>
    )
  )
```

## Additional information

While you might argue that IDs should the unique in the DOM, the DOM specification clearly understands that is not always the case.

https://dom.spec.whatwg.org/#dom-nonelementparentnode-getelementbyid

> The getElementById(elementId) method, when invoked, must return the **first** element, in tree order, within the context object’s descendants, whose ID is elementId, and null if there is no such element otherwise.

In a React system, this more common that we'd like, since, in many cases you might render a list of child components and one of those components might be a composite component and that component might use a Toggle with an ID to better support automation testing.

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! You brought up a good topic on ID duplication, and it's actually what explains the problem here. `id` prop in our `<Toggle>` is used for setting the `id` to (hidden) `<input>` that the `<label>` working as our toggle UI refers to. Given the ID uniqueness is broken with multiple `<Toggle>`s with the same ID, the ID reference from `<label>` to `<input>` is broken.

It may be worth noting that `<Toggle>` has a mechanism to auto-generate a unique ID if `id` is not given. Probably that's what you may have wanted. Hope this helps!
