### ISSUE TITLE
Dragging to resize textarea is not working in IE and Edge

### ISSUE THREAD

**Issue by jingxxue** [IBM/carbon-components-react#2019]
## Detailed description

> Describe in detail the issue you're having.
Dragging the bottom-right corner to resize text area is not working in IE and Edge

> Is this issue related to a specific component?
TextArea 

> What did you expect to happen? What happened instead? What would you like to see changed?
Dragging the bottom-right corner should resize the text area, just like what you can do in Chrome and Firefox
> What browser are you working in?
IE11, Microsoft Edge 44.17763.1.0
> What version of the Carbon Design System are you using?
"carbon-components": "^9.82.13",
    "carbon-components-react": "^6.99.1",
    "carbon-icons": "^7.0.7",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. in a text area
2. dragging the bottom-right corner 
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>https://codesandbox.io/s/4zw79jr7p0

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Our textarea component relies on the browser's native resizer. IE11 doesn't seem to have one. Edge seems to have an open ticket: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7600603/
