### ISSUE TITLE
WIP: v10 Migration Process

### ISSUE THREAD

**Issue by mattrosno** [IBM/carbon-components-react#2027]
## 1. Document needed Sass updates

We should call out in the [React v10 migration doc](https://github.com/IBM/carbon-components-react/blob/master/docs/migration/migrate-to-10.x.md) that you'll also need to update `carbon-components` too for styling. I knew to do that, but others may not.

## 2. Confusion with feature flags

I understand that we won't need to set feature flags in JS once v10 is released, but I happened to use the Webpack config [code snippet from vanilla](https://github.com/IBM/carbon-components/blob/master/docs/experimental.md#application-usage) instead of [React](https://github.com/IBM/carbon-components-react/blob/master/docs/experimental.md#application-usage)... after finding and fixing the syntax errors... I eventually realized I referenced the wrong code snippet. They look so similar.

## 3. More prominently call out removed components

After updating to v10 JS, your React code won't compile because it won't recognize removed components like `<Footer />`. The client console let me know that there was an export/import error, but not that it was specifically with the footer component. We should call that out at the top of the migration doc.

## 4. Document removal of danger primary button

`<Button kind="danger--primary">Danger Primary button</Button>` no longer has styling.

## 5. Bug in content switcher (not migration-specific)

React content switcher has `height: 2.5rem;` on `.bx--content-switcher-btn` but vanilla component does not have that height on that class?

## 6. Bug in date picker (not migration-specific)

Can't click right icon in date picker. Both v10 vanilla and React.

## 7. Bug in progress picker (not migration-specific)

When large container, there are gaps between progress steps. That intentional? All the examples have progress indicator center-aligned... not in a display block container.

## 8. Bug in search (not migration-specific)

The React search component is small by default? The placeholder text looks too big.

## 9. Bug in tabs (not migration-specific)

Awkward how underline disappears when tab has focus.

## 10. Tooltip color bug (not migration-specific)

`.bx--tooltip__label` is a dark color, and the new tooltips have dark backgrounds.

## 11. Icon `description` to `aria-label`?

When migrating the Icon component to `@carbon/icons-react`, should we encourage people to migrate `description` prop to the standard attribute `aria-label`?

## 12. Select in accordion has floating caret

Look into this.

**Comment by mattrosno** [comment]
How the v9 Icon used `description`: https://github.com/IBM/carbon-components-react/blob/v6.62.0/src/components/Icon/Icon.js#L140

**Comment by asudoh** [comment]
Hi @mattrosno thank you for writing up! I thought I wrote a reply in last weekend, but I seem to have not. Here it is:

> 1. Document needed Sass updates

The plan is updating `peerDependencies` in `package.json` so NPM/Yarn yields peer dependency warning if next major release of `carbon-components-react` (say `v7`) used with `v9` `carbon-components`.

> 2. Confusion with feature flags

The plan is flipping default values of feature flags right before we ship `v10` so additional build process is no longer necessary to use our `v10` code.

> 3. More prominently call out removed components

Interesting point - Probably we can replace `null` exports with stub components. BTW the longer-term plan is eliminating removed components completely from the codebase to make it very close to wrong names for named imports in general.

> 4. Document removal of danger primary button

Makes sense.

> 5. Bug in content switcher (not migration-specific)
> 6. Bug in date picker (not migration-specific)
> 7. Bug in progress picker (not migration-specific)
> 8. Bug in search (not migration-specific)
> 9. Bug in tabs (not migration-specific)
> 10. Tooltip color bug (not migration-specific)

Could you please enter separate issues for each? Thanks!

> 11. Icon `description` to `aria-label`?

In `<Icon>`, `description` prop goes to two places:

* `aria-label`
* `<title>`

In `carbon-elements` icons support for both of them seems based on direct assignment (the former is by the prop with the same name, the latter is via `children`).

More wrt `<title>` (hover-over text on icon):

* We seem to be in an agreement that `title` attribute of a surrounding `<button>` should take precedence
* Some people seem to want to discourange usage of `<title>` as a whole, but I cannot see an alternative for "icon as a status" scenario (e.g. icon in [`<FileUploader>`](http://react.carbondesignsystem.com/?selectedKind=FileUploader&selectedStory=FileUploader) that's seen when you select a file and then change `filenameStatus` knob to `complete`) - Keep `<title>`? Icon tooltip?

**Comment by mattrosno** [comment]
Thanks @asudoh. I opened a PR to address (3) and (11).

I will open separate issues as I recreate each component bug.

> 3. More prominently call out removed components

To prevent a graveyard of stubbed components, I'm comfortable letting removed components break client-side JS. If you feel otherwise, please create an issue to create remove component stubs.

**Comment by mattrosno** [comment]
@joshblack @asudoh do we have an issue that contains a "release checklist" so we don't forget to bump up the peerDependency? Just making sure we don't forget that.

**Comment by joshblack** [comment]
@mattrosno I've been adding to: https://github.com/carbon-design-system/issue-tracking/issues/101

**Comment by mattrosno** [comment]
Logged non-migration bugs:

- https://github.com/IBM/carbon-components/issues/2137
- https://github.com/IBM/carbon-components/issues/2138
- https://github.com/IBM/carbon-components-react/issues/2059
- https://github.com/IBM/carbon-components/issues/2139
