### ISSUE TITLE
[Accordion] broken dropdown inside

### ISSUE THREAD

**Issue by shixiedesign** [IBM/carbon-components-react#2037]
Dropdown inside the accordion is broken. Chevron should be inside the field for options.

![image](https://user-images.githubusercontent.com/15144993/54557541-66780680-4989-11e9-80aa-57b99335933b.png)

Observed here (on Chrome): https://deploy-preview-2031--carbon-components-react.netlify.com/experimental/?selectedKind=Accordion

**Comment by emyarod** [comment]
this should be resolved by #2031 (currently blocked), but you can confirm the issue is not present in the deploy preview for that branch
