### ISSUE TITLE
[TooltipSimple]: Does not show tooltip on hover.

### ISSUE THREAD

**Issue by rob-richards** [IBM/carbon-components-react#2050]
## Detailed description

> Describe in detail the issue you're having.

When hovering over the text in the `<TooltipSimple>` component, the tooltip is never displayed, with or without and icon

> Is this issue related to a specific component?

`<TooltipSimple>`

This behavior can be seen on [storybook](http://react.carbondesignsystem.com/iframe.html?selectedKind=TooltipSimple&selectedStory=no%20icon&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel&iframe.html%3FselectedKind=Accordion).

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! `<TooltipSimple>` is a deprecated component and you are right that it's not functional as of now. Some workarounds are:

1. (Recommended) Use `<TooltipDefinition>` or `<TooltipIcon>` instead
2. Bring in style rulesets with selectors beginning with `.#{$prefix}--tooltip--simple` from https://github.com/IBM/carbon-components/blob/v8/src/components/tooltip/_tooltip.scss into your application Sass code

Hope this helps!
