### ISSUE TITLE
TooltipDefinition- button cannot appear as a descendant of button

### ISSUE THREAD

**Issue by ajlohr** [IBM/carbon-components-react#2058]
## Detailed description

> Describe in detail the issue you're having.

When the TooltipDefinition component is rendered, Chrome and Firefox browsers will throw the below error out:
```
index.js:1446 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    in button (created by TooltipDefinition)
    in div (created by TooltipDefinition)
   ...
```

Everything tooltip-wise seems to be working Okay, but not sure this is a pattern that should continue.

> Is this issue related to a specific component?

TooltipDefinition

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect to see no errors in the console when TooltipDefinition is rendered, but the above error happens.

> What browser are you working in?

Chrome Version 73.0.3683.75 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

```
        "carbon-addons-data-viz-react": "1.21.0",
        "carbon-components": "9.84.14",
        "carbon-components-react": "6.108.0",
```

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Render TooltipDefinition and look in the developer console

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! My quick glance at `<TooltipDefinition>` didn't reveal a nested `<button>` as you described. That made me wonder how you tried to use `<TooltipDefinition>`. Would you try to create a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox? Thanks!

**Comment by alohr51** [comment]
@asudoh ah okay, after a closer look I am putting a ToolTipDefinition inside a table header using the `TableHeader` carbon component. 

Looks like this message will happen when the 2 are used together like I did. Is there a better alternative?  You can see the button for the sort (I think) includes another button from the `TooltipDefinition`.

```
<TableRow>
	{headers.map(header =>
		{let headerKey = header.key;
		return (
			<TableHeader {...getHeaderProps({ header })}>
				{
					<div className="headerWithTooltip">
						<TooltipDefinition direction="top" tooltipText="tooltip text">
							{header.header}
						</TooltipDefinition>
					</div>
				}
			</TableHeader>
		)}
	)}
</TableRow>

```

**Comment by asudoh** [comment]
Hi @ajlohr I see - Two choices I can think of:

1. Browser-native approach (`title="Tooltip content"` attribute) - I think this is the approach we recommend in your use case.
2. CSS approach: If you take a look at [our `<TooltipDefinition>` code](https://github.com/IBM/carbon-components-react/blob/v6.110.0/src/components/TooltipDefinition/TooltipDefinition.js#L37-L49), you'll find it's very simple. In fact, definition tooltip and icon tooltip are implemented by CSS-only and our React code merely emits the markup. That said, you can use your custom markup with `<button>` replaced with `<div>` as long as it won't hurt UX and a11y.

Hope this helps!

**Comment by alohr51** [comment]
@asudoh great! thanks for the suggestions. I am sure one of those will fix the error problem. Feel free to close this issue.

**Comment by asudoh** [comment]
Cool thanks @ajlohr for your response!
