### ISSUE TITLE
v10: Click-to-open tooltip: Visual issues

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#2061]
From @shixiedesign at #2047:

- [ ] Focus outline is incorrect. Should use $focus color token and same focus as link (I think...)
![image](https://user-images.githubusercontent.com/15144993/54656944-9dd3d980-4a95-11e9-8e16-5621d6a5aaf9.png)
- [ ] Tooltip's link's hover underline color should be $link-01, same as link. Also wrong is link's `active` state
![image](https://user-images.githubusercontent.com/15144993/54657828-03759500-4a99-11e9-93f9-bf5908247ea6.png)
- [ ] Tooltip's shark fin / triangle tip for Left, Top, and Right are all a couple pixels off 
![image](https://user-images.githubusercontent.com/15144993/54658010-8991db80-4a99-11e9-989b-6261f38db115.png) 
![image](https://user-images.githubusercontent.com/15144993/54658032-9ca4ab80-4a99-11e9-94cf-ad6808339860.png)
![image](https://user-images.githubusercontent.com/15144993/54658039-a201f600-4a99-11e9-9743-8ebd870d759d.png)

**Comment by emyarod** [comment]
I believe the first point is related to https://github.com/IBM/carbon-components-react/issues/2048 as well

**Comment by tw15egan** [comment]
Should be resolved now that https://github.com/IBM/carbon-components/pull/2145 has been merged
