### ISSUE TITLE
DataTable: expanded row style

### ISSUE THREAD

**Issue by dante07577** [IBM/carbon-components-react#2086]
## DataTable expanded row style
DataTable expanded row without `colspan="headers.length + 1"` - all the cells have `border-right: 1px solid #3d70b2;` style applied on `TableExpandRow :hover` 

> Is this issue related to a specific component?
`DataTable `

> What did you expect to happen?(1) What happened instead?(2) What would you like to see changed?(3)
(1) Expanded row has same styles as parent row (see screenshots)
(2) Each Expended row cell has `border-right` style.
(3) Only last cell has `border-right`

## Additional information
Issue:
![issue](https://user-images.githubusercontent.com/11247993/54878513-a9792480-4e36-11e9-8f96-ae84d572a8b7.png)
Expected:
![expected](https://user-images.githubusercontent.com/11247993/54878514-a9792480-4e36-11e9-9bb2-c2fe673c36d2.png)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! IIUC the expandable area is meant to be composed of a single a single container and not for use with regular table cells, CC @IBM/carbon-designers to double-check.

**Comment by dante07577** [comment]
@asudoh Hi!
Oh, i see, it's just unique case in my situation (i need the same number of table cells with same header labels, so it's perfectly lined without colspan used)
I guess you can close this issue.
Thanks for your time!
