### ISSUE TITLE
Scss for the inline version of the DropdownV2 component is not loaded

### ISSUE THREAD

**Issue by michielwoerkom** [IBM/carbon-components-react#2087]
When trying to use the inline version of the DropdownV2 component, I can see the 'inline' class on the dropdown component: `bx--dropdown bx--list-box bx--list-box--inline` but the (s)css is not loaded. I'm including `@import '~carbon-components/scss/components/dropdown/dropdown';` that works fine. But when trying to use the inline version, I'm not getting the expected result.

I'm using:
carbon-components: "9.87.4"
carbon-components-react: "6.111.3"

Am I missing something? Do I need a DropdownV2 scss? 

## The unexpected (with the use of 'inline'):
![unexpected](https://user-images.githubusercontent.com/15747003/54903036-32499c00-4edb-11e9-8c21-1e8bfe666a3e.jpg)

## Should look something like this:
![expected](https://user-images.githubusercontent.com/15747003/54903055-41304e80-4edb-11e9-89f3-90ce48d43d64.jpg)

**Comment by asudoh** [comment]
Hi 👋 likely that you need `carbon-components/scss/components/list-box/list-box`, too - Hope this helps!

**Comment by michielwoerkom** [comment]
Oops, that does the trick indeed. :sweat_smile:

Thanks for the quick repsonse!
