### ISSUE TITLE
Create storybook story for PaginationV2 (now Pagination)

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-components-react#2101]
Looks like with the rename that there is no storybook story for `PaginationV2`, we should create one and add it in 👍

**Comment by lovemecomputer** [comment]
i'll do this after the rename for `Pagination` is merged into v10 release branch!

**Comment by lovemecomputer** [comment]
closed in https://github.com/IBM/carbon-components-react/pull/2129
