### ISSUE TITLE
some pages are not rendering properly - next.carbondesignsystem.com

### ISSUE THREAD

**Issue by harshzalavadiya** [IBM/carbon-components-react#2117]
## Detailed description

Some pages in next.carbondesignsystem.com goes blank after some seconds

Sample URL: 
https://next.carbondesignsystem.com/updates/v10-migration/designers#layout-and-grid

> What browser are you working in?
- Chrome
- Firefox

## Steps to reproduce the issue

1. Go to https://next.carbondesignsystem.com/updates/v10-migration/designers#layout-and-grid
2. Wait for page to fully load
3. after some seconds page goes blank

## Additional information

![Screenshot_20190329_142428](https://user-images.githubusercontent.com/5774849/55221187-ebd3a480-522e-11e9-903d-93c2f370b7ee.png)

## Update
It seems that by searching it's redirecting to wrong hash and due to that it's not able to render page properly

**Comment by asudoh** [comment]
Moving to `carbon-website` repo given the call stack points to the code there.
