### ISSUE TITLE
migrate-to-10.x.md is missing from the repo

### ISSUE THREAD

**Issue by Yohanna** [IBM/carbon-components-react#2119]
In the new [v10 website](https://next.carbondesignsystem.com), under `v10 Migration guide` section, the [carbon-components-react](https://next.carbondesignsystem.com/updates/v10-migration/developers#carbon-components-react) section links to this file [migrate-to-10.x.md](https://github.com/IBM/carbon-components-react/blob/master/docs/migration/migrate-to-10.x.md) which is missing from the repo.

**Comment by joshblack** [comment]
Hi @Yohanna! 👋 We're replacing it with `migrate-to-7.x.md` in this project 👍

**Comment by joshblack** [comment]
PRs to update:

https://github.com/carbon-design-system/carbon-website/pull/1411
https://github.com/carbon-design-system/carbon-website/pull/1410

**Comment by joshblack** [comment]
Going to close this for now, feel free to comment if I missed a spot!
