### ISSUE TITLE
DropDown V2 not changing label after dropDown options are changed

### ISSUE THREAD

**Issue by sumanth10** [IBM/carbon-components-react#2130]
## Detailed description

> Describe in detail the issue you're having.

I have an issue with the DropdownV2 component. There are two dropdown X and Y. Onchange of X will change the values of Y. So i will go ahead and select the a particular value for the dropdown Y. This scenario is working fine. But when I i go back and change the value in dropdown X the bold label in dropdown Y remains the same (i.e The value i have selected previously). How do i get rid of this value and get back the initial value of dropdown Y. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

A bug
> Is this issue related to a specific component?

DropDown V2
> What browser are you working in?

Effecting in all the browser
> What version of the Carbon Design System are you using?

9.59.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Working on IBM cloud Mobile foundation service. Planning to go to GA on April 4th and this is a UI blocker

 [CodeSandbox](<https://codesandbox.io/s/2wmxz1m94y>)

## Additional information

- <img width="981" alt="Screenshot 2019-03-15 at 5 29 48 PM" src="https://user-images.githubusercontent.com/14212012/55288074-e5c8f980-53cf-11e9-95b9-ff918228cb56.png">

- As you can see in the screenhot from the dropdown “Please select space” I do not have a value `MobileFoundationTest` in my dropdown elements. That value is appearing from the previous array. Is there a way to clear the label and reinstate the initial values

**Comment by asudoh** [comment]
Hi :wave: https://2wmxz1m94y.codesandbox.io/ seems to show something like:

![image](https://user-images.githubusercontent.com/1259051/55306738-28eaa180-5490-11e9-9abb-df91d57ed892.png)

Did you mean to put another CodeSandbox link?

**Comment by sumanth10** [comment]
Yes, that is the correct functionality. Pardon my CSS. But the main issue is once you select something from the dropDown the label changes to the selected value. For Eg: if you select 'Prod' from the dropDown the label will change to 'Prod'. The issue lies when you click on the button 'Change Dropdown options'. Onclick of that button I have updated the array displaying the dropDown option using the `this.setState`. So technically the entire element of the dropDown should get re-rendered and the new values should be pushed in as the option of the DropDown, which is working fine. But the problem is the selected value label does not change it still shows the previously selected value. From the previous Eg:  the values in the array get changed from 'Prod' to 'Prod1' but the selected label still remains as 'Prod'

**Comment by asudoh** [comment]
I see, while I can imagine your desire to auto-reset the selection in such scenario, probably to the 1st item, there are a couple of options I can think of:

1. Update `selectedItems` in your `changeValue()`
2. Write your own `<DropdownV2>` - If you take a look at [the code](https://github.com/IBM/carbon-components-react/blob/v6.100.0/src/components/DropdownV2/DropdownV2.js), you'll find it's merely a consumer of [Downshift](https://github.com/downshift-js/downshift) library and Carbon UI logic in `<ListBox.*>`

Hope this helps!

**Comment by ZacharyStair** [comment]
I was looking for a different dropdown issue but i think react may already provide a solution for this one.

If you give the dropdown component a `key` prop, react will unmount and remount your component if that key changes (https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key). So basically you can just make the logic for 'Change Dropdown options' also change the `key` passed to the Dropdown and the component will 'reset', marking one of the new options as 'selected'.

**Comment by sumanth10** [comment]
@ZacharyStairI tried adding the key prop and gave the 1st value of the state array to the dropdown. But I am still experiencing the same issue. The state gets updated so eventually the key prop will get the new updated value but the dropDown Label is not getting changed

**Comment by ZacharyStair** [comment]
i opened your sandbox and forked it: https://codesandbox.io/s/m3nxrm35ny

adding the key on the dropdown itself wasn't working because `withState` was holding onto the old state value (and dropdown doesn't recognize that because it isn't part of the new dropdown); but moving the `key` to `withState` seems to accomplish what you were looking for

**Comment by sumanth10** [comment]
This solution worked. Thanks
