### ISSUE TITLE
Regression with the latest release: focus-trap

### ISSUE THREAD

**Issue by shiranyo** [IBM/carbon-components-react#2131]
## Detailed description

> Describe in detail the issue you're having.
After update to new version (6.114.0) we got an error: `Uncaught Error: You can't have a focus-trap without at least one focusable element` which breakes our app. 

> Is this issue related to a specific component?
Modal

> What browser are you working in? 
All

> What version of the Carbon Design System are you using? 
6.114.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
AppID service 

Link to slack disscussion: https://ibm-cloud.slack.com/archives/C2K6RFJ1G/p1553871347049100

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/3xm58lwrnp

## Additional information

- Screenshots or code
- Notes

**Comment by vpicone** [comment]
Thanks Shiran!

This happens when the Modal is passed a "visibility: hidden" style. This can come from custom class names or styles being passed in. 

A temporary fix is to explicitly pass a `style={{visibility: 'visible'}}` prop to the modal component.

If you're already passing in styles you can append it to the end:

`style={{...myModalStyles, visiblity: 'visible}}` to override those styles.

**Comment by asudoh** [comment]
Saw that https://codesandbox.io/s/3xm58lwrnp has `<Modal focusTrap={false} ...>`, however, `focus-trap-react` has `active: true` in its `defaultProps`, and thus https://codesandbox.io/s/3xm58lwrnp activates `focus-trap-react` even though `focusTrap={false}`.

@dakahn @vpicone Do you want to ensure we pass along `false` to `active` prop of `<FocusTrap>` if `open && focusTrap` is falsy at https://github.com/IBM/carbon-components-react/blob/v6.114.0/src/components/Modal/Modal.js#L351?

Or alternatively we can prevent `<FocusTrap>` from being rendered if `focusTrap={false}`:

```javascript
const modal = (
  <div
    {...other}
    onKeyDown={this.handleKeyDown}
    onClick={this.handleClick}
    onBlur={this.handleBlur}
    className={modalClasses}
    role="presentation"
    tabIndex={-1}
    onTransitionEnd={
      this.props.open ? this.handleTransitionEnd : undefined
    }
    ref={this.outerModal}>
    {modalBody}
  </div>
);

return !focusTrap ? modal :
  // `<FocusTrap>` has `active: true` in its `defaultProps`
  (
    <FocusTrap active={!!open} _createFocusTrap={this.createFocusTrap}>{modal}</FocusTrap>
  );
```

What do you think? Thanks!

**Comment by vpicone** [comment]
Right now we have `<FocusTrap active={open && focusTrap}>` so passing `focusTrap={false}` to modal should set active to false no?

Does this solution work if they pass `style={{visibility: 'hidden'}}`

**Comment by asudoh** [comment]
@vpicone Looks that `open && focusTrap` yields `null` or `undefined` and thus the [default prop](https://github.com/davidtheclark/focus-trap-react/blob/6.0.0/src/focus-trap-react.js#L94) gets in effect - Does this make sense to you?

**Comment by vpicone** [comment]
@asudoh Ah! You're correct, on initial render `open` is undefined, since it's not included in our default props. `undefined && false === undefined` so the defaultProps of FocusTrap kick in. React default props don't get applied if the null is passed in (which was my assumption here).

It looks like our solution might be as simple as adding `open: false` to the defaultProps so that we don't pass in `undefined` to the `active` prop of FocusTrap.

`<FocusTrap active={!!open && focusTrap}>` would also do the trick.

**Comment by asudoh** [comment]
Thanks @vpicone for your thoughts! From user's PoV it's ideal they get free from any possible side effects if `focusTrap` is falsy, which is achieved by not rendering `<FocusTrap>`.

**Comment by tonydiaz** [comment]
I'm having the same issue on Watson Assistant. The `temporary fix` seems to stop the modal from crashing and renders fine. I'm seeing a number of warnings on the console now for the Modal not have an **offsetWidth**:
![Screen Shot 2019-04-05 at 1 36 59 PM](https://user-images.githubusercontent.com/7145340/55645973-fd292d80-57a7-11e9-99d6-21c0a0fcc0f2.png)

**Comment by tonydiaz** [comment]
FWIW the storybook also has the warnings displaying on the console:
![Screen Shot 2019-04-05 at 1 42 31 PM](https://user-images.githubusercontent.com/7145340/55646260-bab42080-57a8-11e9-93f7-d7130d3d9d9d.png)

http://react.carbondesignsystem.com/?selectedKind=Modal&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
