### ISSUE TITLE
DropdownV2 item has fixed item height leading to overlapping items

### ISSUE THREAD

**Issue by dzaqb** [IBM/carbon-components-react#2138]
## Detailed description
When items in DropdownV2 component are very long and are folded into 3 lines, then they start overlapping each other. 

> Is this issue related to a specific component?
DropdownV2

> What did you expect to happen? What happened instead? What would you like to see changed?
item height should adjust to contain entire item without overlapping to other items. 

> What browser are you working in?
Firefox, Chrome

> What version of the Carbon Design System are you using?
carbon-components-react 6.111.1
carbon-components 9.87.0

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/43142933/55411073-4178bb80-5565-11e9-9890-c3854cdd8ab9.png)

**Comment by dzaqb** [comment]
.bx--list-box__menu-item has  height set to 2.5 rem.

**Comment by asudoh** [comment]
Hi :wave: we are not supporting multi-line content in our drop down item. I can bring up two approaches for your use case, one is widening the dropdown box, another is using `text-overflow: ellipsis`. Hope this helps!
