### ISSUE TITLE
Application-level control of our stateful components

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#2152]
## Summary

Many of our stateful components, especially ones started with a React prop dictating initial state, has ended up with enhancement requests for supporting subsequent updates coming after. This issue is for sharing the history of such requests.

@emyarod is pushing for providing stateless versions to meet such kind of request.

## Relevant information

Here's the list of (solved) issues I have been able to capture:

* (Issue# 117 in our old repo)
* https://github.com/IBM/carbon-components-react/issues/61
* https://github.com/IBM/carbon-components-react/issues/187
* https://github.com/IBM/carbon-components-react/issues/335
* https://github.com/IBM/carbon-components-react/issues/677
* https://github.com/IBM/carbon-components-react/issues/669
* https://github.com/IBM/carbon-components-react/issues/740

**Comment by asudoh** [comment]
@emyarod Feel free to re-open this issue if you want to base your work in this area on. Thanks!

**Comment by emyarod** [comment]
alright @asudoh I will be reopening when the v10 release is in a more stable state!
