### ISSUE TITLE
MultiSelect.Filterable tool tips not translated

### ISSUE THREAD

**Issue by el-moshme** [IBM/carbon-components-react#2162]
## Environment

N/A

## Detailed description

> version in product is 

    "carbon-addons-cloud-react": "^1.9.0",
    "carbon-components": "^9.83.22",
    "carbon-components-react": "^6.106.0",

and using 
    import { Search, MultiSelect } from 'carbon-components-react';
    import { NestedFilterableMultiSelect } from 'carbon-addons-cloud-react';

> What did you expect to happen?

using MultiSelect.Filterable && NestedFilterableMultiSelect - passing function 
translateWithId={id => translateWithId(id)}
where translateWithId(id) returns translated strings for 
close.menu
open.menu
clear.all
clear.selection

> What happened instead?

translated strings are ignored for MultiSelect.Filterable (although used for MultiSelect)

## Steps to reproduce the issue

re-created at https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox, 

##  Create with MultiSelect 

```
import React from "react";
import { render } from "react-dom";
import { MultiSelect } from "carbon-components-react";

function translateWithId(id) {
  if (id === "close.menu") return "translated close menu";
  return "translated open menu";
}

const App = () => (

  <div>
    <MultiSelect
      id="first-filter"
      items={["a", "b"]}
      label={"status.type"}
      translateWithId={id => translateWithId(id)}
    />
  </div>

);

render(<App />, document.getElementById("root"));
```

## Create with MultSelect.Filterable

```
import React from "react";
import { render } from "react-dom";
import { MultiSelect } from "carbon-components-react";

function translateWithId(id) {
  if (id === "close.menu") return "translated close menu";
  return "translated open menu";
}

const App = () => (
  <div>
    <MultiSelect.Filterable
      id="first-filter"
      items={[{ label: "a" }, { label: "b" }]}
      label={"a"}
      translateWithId={id => translateWithId(id)}
      placeholder="a"
    />
  </div>
);

render(<App />, document.getElementById("root"));

```
## Additional information

This may be more than one issue, and I realize the example code is not complete but the end goal is to use the components (MultiSelect.Filterable & NestedFilterableMultiSelect) and be able to provide the translated strings for 
close.menu
open.menu
clear.all
clear.selection

![image](https://user-images.githubusercontent.com/27785752/55638427-255b6100-5795-11e9-8fb2-35428156d813.png)

This issue can be viewed at cloud.ibm.com/status

**Comment by asudoh** [comment]
HI @el-moshme thank you for reporting! Could you please put a correct link to your CodeSandbox example? Thanks!

**Comment by el-moshme** [comment]
@asudoh I am not familiar with this tool - but hopefully this is it.  https://codesandbox.io/s/0yxk3vz6kv

I just used the link suggested (https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox) and edited the index.js file, with the code snippets above.

**Comment by asudoh** [comment]
Thanks @el-moshme - I needed to replace `items={["a", "b"]}` with `items={[{ label: "a" }, { label: "b" }]}` so your CodeSandbox code won't throw when I open up the dropdown, but once I have done that, I see `translateWithId` is in effect - Getting `translated open menu` and `translated close menu`. So looks that you have almost figured out what to do here?

**Comment by el-moshme** [comment]
I updated with the line as you suggest and added MultiSelect.Filterable instead of MultiSelect
In this case, I don't believe that it is showing the translated strings.  

https://codesandbox.io/s/0yxk3vz6kv

**Comment by el-moshme** [comment]
thank you @asudoh -can you advise how I might set translated strings fro 
clear.all
clear.selection
for the same components? MultiSelect.Filterable & NestedFilterableMultiSelect ?

**Comment by asudoh** [comment]
Hi @el-moshme it'll be the same as the example you provided earlier, providing `translateWithId` with the same translation keys.
