### ISSUE TITLE
Data table rendering without styles

### ISSUE THREAD

**Issue by jikkujj** [IBM/carbon-components-react#2166]
As of the the latest version of carbon-react, the datatable renders without styles.
Here is the reproduction
https://codesandbox.io/s/pj6nv5l50

**Comment by asudoh** [comment]
Hi 👋 our React variant of data table is [still under construction](https://www.carbondesignsystem.com/components/component-status) - Please stay tuned!

**Comment by naythanwilliams** [comment]
@asudoh Does this mean the React DataTable component is currently unusable? Is this currently being addressed?

**Comment by vpicone** [comment]
@naythanwilliams yes, and yes. Hoping to have the rest of the pieces completed by tomorrow night.

**Comment by naythanwilliams** [comment]
@vpicone Thanks a ton for responding so quickly. I'll look out for your changes. In the future, I and the company I work for would be happy to lend a hand, since we're making heavy use of this component.
