### ISSUE TITLE
Datatable expansion causes table headers to move akwardly

### ISSUE THREAD

**Issue by jikkujj** [IBM/carbon-components-react#2167]
If the text in the expanded area in the grid is small, the table headers dont move but if it pretty large, the table headers move messing up the grid.
Reproduced in 
https://codesandbox.io/s/pj6nv5l50
where the first row expansion text is small and hence the table header dont move but the 2nd and 3rd row expansion text is large and the table headers move

**Comment by asudoh** [comment]
@vpicone Is this something one of your recent fixes addresses? Thanks!

**Comment by vpicone** [comment]
It is!

**Comment by asudoh** [comment]
Closing as #2127 or #2247 should address this issue according to @vpicone. Can re-open if anybody finds otherwise. Thanks @vpicone!
