### ISSUE TITLE
Need the unupdated stylesheet

### ISSUE THREAD

**Issue by RakshithaGowda** [IBM/carbon-components-react#2168]
### Summary

Can I get the code of the previous stylesheet? I have used it in my project and the updated stylesheet doesn't contain the exact features that i want

**Comment by asudoh** [comment]
Hi 👋 do you want to update your `package.json` to use Carbon's specific versions, like `"carbon-components": "@^9.90.0"`? Or are you talking about something different?

**Comment by rmartinez213** [comment]
Hello! I believe he is talking about the recently updated style from:

https://unpkg.com/carbon-components/css/carbon-components.css

which is now updated to:

https://unpkg.com/carbon-components@10.0.0/css/carbon-components.css

Is there any way to retrieve the previous stylesheet that was used before it was updated?

**Comment by rmartinez213** [comment]
I believe I found out the previous stylesheet version actually: 

https://unpkg.com/carbon-components@9.90.9/css/carbon-components.css

Thank you.

**Comment by asudoh** [comment]
OK closing as there seems a solution, don't hesitate to let us know otherwise!
