### ISSUE TITLE
Modal: Browser property offsetWidth not working in Chrome 73 (Mac OS)

### ISSUE THREAD

**Issue by IOIO72** [IBM/carbon-components-react#2182]
## Detailed description

The Modal uses the property offsetWidth which causes the console error:

`Uncaught TypeError: Cannot read property 'offsetWidth' of null`

Here's the Line:

https://github.com/IBM/carbon-components-react/blob/e769f33cd31eadf790aad0637aedb01092ff19b0/src/components/Modal/Modal.js#L252

> What browser are you working in?

Chrome 73 (MacOS)

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.1.0"
    "carbon-components-react": "^7.0.0"

**Comment by vpicone** [comment]
This will be fixed in the next release. You can see there's a new null check in master just before the line you linked.
