### ISSUE TITLE
Typescript types error in version 7.0.1

### ISSUE THREAD

**Issue by httpsOmkar** [IBM/carbon-components-react#2201]
## Detailed description

In the latest version of `carbon-components-react` the typescript types are included which have errors which prevent the project from compiling.

## Errors
`lib/components/Accordion/Accordion.Skeleton.d.ts`
![DeepinScreenshot_select-area_20190411224642](https://user-images.githubusercontent.com/29942725/55977223-e2751e00-5cab-11e9-85f3-5d797572958e.png)

`lib/components/UIShell/HeaderGlobalAction.d.ts`
![DeepinScreenshot_select-area_20190411224709](https://user-images.githubusercontent.com/29942725/55977246-f1f46700-5cab-11e9-876f-c7d7057aebe8.png)

**Comment by joshblack** [comment]
Hi @httpsOmkar! 👋 Sorry about this, looking into fixing it now!
