### ISSUE TITLE
Tabs dropdown label references cached tab label

### ISSUE THREAD

**Issue by Jinhei** [IBM/carbon-components-react#2204]
## Detailed description

Currently, updating props.children and props.selected at the same time uses prevProps.children's label in the dropdown. This occurs because getTabAt checks the refs cached in the class, which are not updated until ref is called (after selectedLabel is populated).

## Steps to reproduce the issue

1. Update `selected` while also updating the component's `children`

https://codesandbox.io/s/jl71ql90l3

## Additional Information

I've opened #2196 with a simple fix.

**Comment by asudoh** [comment]
Thanks @Jinhei for writing this up! Could you elaborate more on how https://codesandbox.io/s/jl71ql90l3 should have worked? The code gives me an impression that the tab is `new` is shown and selected (obviously with `new` label), but I may be missing something.

**Comment by Jinhei** [comment]
The issue is in the dropdown -- the tab `new` is shown (correctly), but the dropdown label is incorrect. The label displays the previous `children`'s label at `selected` index. 

See screenshots below:

![image](https://user-images.githubusercontent.com/7538453/56040624-cea9d600-5d04-11e9-939d-c0dff861af56.png)
![image](https://user-images.githubusercontent.com/7538453/56040635-d49fb700-5d04-11e9-933d-46db5e589dce.png)
