### ISSUE TITLE
NumberInput: Input invalid value issue

### ISSUE THREAD

**Issue by AngelaChenBJ** [IBM/carbon-components-react#2226]
I'm using NumberInput widget, and my usage scenario is that there are one NumberInput and one Button, when the NumberInput is with valid value, the Button is enabled, when NumberInput is with invalid value, the Button is disabled.
While I find when I try to input a value that lower than minimum value or clear the input area to be empty, it automatically resets to the minimum value, BUT the value I can track is already invalid, then the Button is disabled, however，the value show in NumberInput widget is the minimum value which is a valid one that means Button shall be enabled.
So my question is that how I detect the value to make my condition to judge button with disabled correctly?
Right now, I'm using value === ' ' or value > {<max_value>} or value < {<min_value>}
Take clear the input area as an example, when I clear the input area, the value I can detect is ' ', so button disabled is true, button is shown in disabled status, BUT, the value shown in NumberInput widget is automatically changed to minimum value(it is 1 in my test scenario) , which is a valid value and the button shall be enabled.
<img width="179" alt="Screen Shot 2019-04-17 at 6 10 19 PM" src="https://user-images.githubusercontent.com/41713412/56280825-9871b980-613d-11e9-9283-f0f1dc8eec9c.png">

The code:
import React from 'react';
import { Button, NumberInput } from 'carbon-components-react';

export default class AlertConfigBK extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      numberInputValue: 0,
      disabled: false,
    };
  }

  onChange = value => {
    value = value.imaginaryTarget.value;

    let disabled = !!(value === '' || value > 100 || value < 1);

    this.setState({ numberInputValue: value, disabled });
  };

  render() {
    let { numberInputValue, disabled } = this.state;

    return (
      <div id="dialogHolder">
        <div>
          <NumberInput
            id="number_input"
            value={numberInputValue}
            max={100}
            min={1}
            step={1}
            onChange={this.onChange}
          />
          <Button kind="primary" disabled={disabled}>
            test
          </Button>
        </div>
      </div>
    );
  }
}

## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment]
Hi :wave: thank you for bringing up this topic! As you may have imagined, our `<NumberInput>` auto-caps the given value. You can cap the value yourself to see if the number input is in an invalid state, like:

```javascript
const newValue = Math.min(Math.max(1, Number(value.imaginaryTarget.value)), 100);
const disabled = isNaN(newValue);
this.setState({ numberInputValue: newValue, disabled });
```

If you desire `<NumberInput>` not to auto-cap the given value, you can create a new issue for that. Hope this helps!
