### ISSUE TITLE
OverflowMenu with floatingMenu option should support direction `left` and `right`

### ISSUE THREAD

**Issue by Dr-KiranJogu** [IBM/carbon-components-react#2244]
OverflowMenu with floatingMenu option should support direction `left` and `right`

## Detailed description
When we use floatingMenu option in OverflowMenu, user should have control to display the menu to left or right.  The current implementation does not support `left` and `right`. which is causing the menu items to be displayed at incorrect location / alignment.

 <  OverflowMenu floatingMenu> {overflowMenutItems} <  /OverflowMenu>

> Is this issue related to a specific component?

<  OverflowMenu floatingMenu> {overflowMenutItems} <  /OverflowMenu>

> What did you expect to happen? What happened instead? What would you like to see changed?

- OverflowMenu should support the directions left & right.

## Steps to reproduce the issue
just click on the overflow menu in the following code sandbox.
 https://codesandbox.io/s/6wkkxl3923

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/43074433/56416164-af371e00-62ad-11e9-8576-feed2095419e.png)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting. While our design deliberately doesn't have left/right placement, our overflow menu has `flipped` prop that may be closer to what you are looking for. You can go to http://react.carbondesignsystem.com/?selectedKind=OverflowMenu&selectedStory=basic, click on KNOBS tab at the bottom, and turn on `flipped` there to see the details. Hope this helps!
