### ISSUE TITLE
Storybook example for an inline Dropdown should exist

### ISSUE THREAD

**Issue by cknabe** [IBM/carbon-components-react#2266]
I had a designer give me a mock-up with an inline Dropdown and I could not find it anywhere in the Storybook. Because the way the design was put together I was unsure what component it represented.

![image](https://user-images.githubusercontent.com/13582620/56582808-bc018d80-659d-11e9-8270-8d405a0efb9f.png)

http://react.carbondesignsystem.com/?selectedKind=Dropdown&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by asudoh** [comment]
Hi 👋 thank you for bringing this up! You can go to Storybook KNOBS tab at the bottom and change "Dropdown type (type)" to achieve what you were looking for. Hope this helps!
