### ISSUE TITLE
DataTable > TableExpandedRow > TableCell creating a td inside a div element

### ISSUE THREAD

**Issue by babieste** [IBM/carbon-components-react#2274]
## Summary
My TableCell component inside of TableExpandedRow is creating a td element inside of a div (`class="bx--child-row-inner-container"`) and that makes the td element to span only in a td area (not in the full width of a row). Like this:
```
<tr class="bx--expandable-row" data-child-row="true">
    <td>
        <div class="bx--child-row-inner-container">
            <td colspan="4">
                <p>hey</p>
            </td>
        </div>
    </td>
</tr>
```

My component was created like in the React Components tutorial:
```
<DataTable.TableBody>
    { rows.map(row => (
        <React.Fragment key={row.id}>
            <DataTable.TableExpandRow {...getRowProps({ row })}>
                 { row.cells.map(cell => (
                     <DataTable.TableCell key={cell.id}>{cell.value}</DataTable.TableCell>
                 ))}
            </DataTable.TableExpandRow>

            { row.isExpanded && (
               <DataTable.TableExpandedRow>
                   <DataTable.TableCell colSpan={headers.length+1}>
                       <p>hey</p>
                   </DataTable.TableCell>
               </DataTable.TableExpandedRow>
          )}
       </React.Fragment>
    ))}
</DataTable.TableBody>
```
## Relevant information
How it looks like:
![Screenshot_2019-04-25 React App](https://user-images.githubusercontent.com/16684882/56745039-ff9bf900-674f-11e9-9bed-8bc9562da523.png)

What am I doing wrong? Or is it a bug?

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! `<TableExpandedRow>` spans across the whole row and does not expect any table cells. Hope this helps!

**Comment by babieste** [comment]
@asudoh the README needs corrections then! Thanks!
