### ISSUE TITLE
opening Tooltip or OverflowMenu crashes IE11 - caused by method 'closest"

### ISSUE THREAD

**Issue by JessNah** [IBM/carbon-components-react#2277]
Hi,
I have recently upgraded to the newest Carbon v10 and newest version of Carbon-components-react as well.
When I open any of my Tooltip components or even open an OverflowMenu component, my entire site on IE11 goes blank white, and I get an error message
"Object doesn't support property or method 'closest"

(Same error message/bug happens with Tooltip/OverflowMenu)

![ClosestBug](https://user-images.githubusercontent.com/14356838/56820490-08590180-681a-11e9-919d-a725a714de5b.png)

**Comment by asudoh** [comment]
Hi 👋 you [need the polyfill for `Element.prototype.closest()`](https://github.com/IBM/carbon-components-react/blob/v7.1.0/docs/migration/migrate-to-7.x.md#polyfills), starting `v10`. Please see the whole list at: https://github.com/IBM/carbon-components-react/blob/v7.1.0/.storybook/polyfills.js - hope this helps!
