### ISSUE TITLE
Add support for "all" option in Pagination component

### ISSUE THREAD

**Issue by alisonemiller** [IBM/carbon-components-react#306]
We've had a request to add an "all" option for the "items per page" dropdown within the Pagination component. It looks like the `pageSizes` prop requires an array of numbers, so `all` would not be a valid value.

**Comment by joshblack** [comment]
Hi @alisonemiller! 👋 

Thanks so much for taking the time to make this issue. Definitely believe this would be a great addition to `Pagination`, as well as `DataTable`.

If you could follow-up with what you expect the API for `Pagination` to be with these changes in code, that would be great! Will definitely flag this as an enhancement and try to get it added to a sprint 😄 

If you also respond with your Business Unit, Offering name, and any deadlines that can also help us prioritize more effectively to determine when we can implement something like this!
