### ISSUE TITLE
Usage without ejecting from Create React App

### ISSUE THREAD

**Issue by Alex-Mann** [IBM/carbon-components-react#363]
The carbon design system and kit is an awesome library of components. I just wanted to inquire if there was any discussion (internal or external) about supporting this in a non-ejected version of create-react-app.

I realize there would have to be some sort of migration or tooling to go from `.scss` files to using `.css`, but I feel like this would really benefit the community, especially newcomers to react who want to jump into just using React without having to worry about all the tooling involved in the ecosystem.

Maybe `styled-components` is a potential migration option?

**Comment by joshblack** [comment]
Hi @Alex-Mann! 👋  Thanks so much for taking the time to make this issue 😄

We definitely would want to support CRA without having to eject, unfortunately the requirement on sass is something that caused the current example to eject. Since the Carbon Design System's styles need to be library agnostic, targets like `styled-components`, `glamor`, etc. are unfortunately not on the immediate roadmap as they are heavily tied to React (in some capacity).

Would love to hear if you have any ideas/suggestions that could help match our requirements yet still meet your expectations from Carbon when looking to use it in things like CRA 😄

**Comment by Alex-Mann** [comment]
So these are just some very preliminary thoughts and might not be completely applicable, but I'll just throw it out there in case it spurs some thought from anyone else reading this issue.

[This](https://medium.com/styled-components/getting-sassy-with-sass-styled-theme-9a375cfb78e8) was an interesting article I came across regarding extracting `sass` styles and putting them into styled components.

With your current situation, the best approach is probably some kind of generation/build pipeline to make components out of your sass styles, similar to what has been done [here](https://github.com/kossnocorp/decss).

I will do some more thinking about this as well and update this thread as those thoughts come about.

**Comment by joshblack** [comment]
Love all your ideas @Alex-Mann, and definitely feel like our team should try and push on being able to define styles in one language (preferably JS) and then target CSS/SCSS/etc. Would help increase safety of the styles themselves as we can enforce/codify certain standards, and makes our compilations cleaner 😄

**Comment by psachs21** [comment]
Another possibility for css in js frameworks in [emotion](https://emotion.sh/) which actually doesn't tie itself to react but supports much the same syntax (with styled components like support provided via an optional babel plugin). I was looking to start using it on our project (within watson finance) and would love to synchronize with this project, if possible.

**Comment by joshblack** [comment]
Hi @psachs21! Definitely am a big fan of emotion, and the corresponding glamor project. We definitely would welcome any ideas to help support these use-cases, so feel free to propose anything that would help us support this 😄

**Comment by vpicone** [comment]
Is there any reason compiled-components doesn't distribute css? It already has the build command implemented. I'm curious why they don't just have a proper dist folder (something like semantic-ui https://github.com/Semantic-Org/Semantic-UI/tree/master/dist)

**Comment by Alex-Mann** [comment]
Chiming in on this again... looks like create-react-app will be able to support this sometime in the (hopefully near) future.

https://twitter.com/dan_abramov/status/1042075844229963777

**Comment by joshblack** [comment]
Yeah! Very exciting 🎉

**Comment by joshblack** [comment]
Published an article for this! https://medium.com/carbondesign/up-running-with-carbon-react-in-less-than-5-minutes-25d43cca059e

**Comment by joshblack** [comment]
Closing this based on above, feel free to chime-in if we should re-open! 😄
