### ISSUE TITLE
Add async API support for ComboBox

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-components-react#463]
This issue is both for initial API discussions for supporting this, and then for keeping track of the actual implementation of this API.

The problem right now is that `ComboBox` is predicated on have a static list of items. It needs to communicate to consumers one of the two following scenarios that could happen during usage:

- A filtered result returns no results, meaning we might want to fetch more results optimistically
- A user initiates a request to load more items by clicking the "load more options" button on the bottom of the control (as shown in the design spec)

An initial suggestion for the API, then, is to mirror `react-virtualized`'s approach here, and do something similar to the following:

```js
<ComboBox
  {/* additional props */}
  isOptionLoaded={isOptionLoaded}
  loadMoreOptions={loadMoreOptions}
  rowCount={remoteRowCount}
/>
```

Where we introduce the following additional props:

- `isOptionLoaded`: to communicate if a given option index has been fetched from the remote source
- `loadMoreOptions`: is given a `startIndex` and `stopIndex` and should fetch the items from the remote store. This method should return a promise
- `rowCount`: corresponds to the total number of remote options so that the control knows when to initiate requests for more options, or when to display UI elements to communicate to the user that they can load more options

**Comment by psachs21** [comment]
How about just a simpler API, something like:

```ts
getFilteredItems: (filterValue: string) => Promise<Array<object>>
```

At least it's something that fits my mental model of a combobox better. I imagine a combobox as a dropdown that shows a restricted list of items (say, 20) but encourages the user to enter text to search the backend for more specific items.

**Comment by joshblack** [comment]
@psachs21 unfortunately I'm not sure that the default case here is async, as the teams currently using ComboBox are just using it to filter down a longer list that isn't necessarily remote-based.

Having knowledge of the number of expected items also will allow us to generate this element at the bottom of the list:

![screen shot 2018-01-11 at 10 35 38 am](https://user-images.githubusercontent.com/3901764/34835694-2ee79126-f6bb-11e7-958c-2f8433820375.png)

Which should initiate a request for more items.

It seems like there is a mismatch in the UX of the currently designed component and what you're anticipating, potentially? Not saying either way is right/wrong, btw, just trying to understand all the use-cases 😄 

At the very least, I think we need `rowCount`, `optionsCount`, etc to communicate that given a list of items, we either have less than the total number of items, or the expected number of items. The `isOptionLoaded` was going to be used to check if an item at a given spot is loaded or not, and can be used to show a loading indicator for more elements in the list. It also would be used to initiate `loadMoreOptions` which is used to add more items to the given list of items.

**Comment by psachs21** [comment]
I guess what I'm trying to figure out how to solve the following use case:

1. Page loads with ComboBox1 and we automatically fetch the first items (say: [A, B, C, D])
2. User types Z and the UI shows no items (because loaded items doesn't contain Z)

The UI will show the "Load next 50 results" but without showing any items. It seems like bad UX to me, since it's not really showing "next" because there was no initial.

**Comment by joshblack** [comment]
Does that first case I brought up match what you're describing? Specifically:

> A filtered result returns no results, meaning we might want to fetch more results optimistically

**Comment by joshblack** [comment]
cc @tay-aitken @bsonefeld to get your thoughts on the flow for loading results asynchronously 😄  could easily be misinterpreting the design docs!

**Comment by psachs21** [comment]
@joshblack Ah, i misread your first case. That sort of covers it, as long as the "optimisitic" takes into account that it should provide the filter value as an argument. I suppose the `loadMoreOptions` function could be provided the filter value and that would allow me to adjust the API call.

So does that mean rowCount should be the total, unfiltered rowCount?

**Comment by psachs21** [comment]
I just want to avoid the case of: 
1. [A,B,C,D] are loaded
2. Z is searched
3. [E,F,G,H] are loaded (optimistically)
4. [I, J, K, L] are loaded (optimistically)
...
Which can potentially spiral into a lot of wasted async calls.

**Comment by joshblack** [comment]
@psachs21 ideally yes, but I think there are ways we can work around it if that's not possible for a team to get. For example, just setting the `rowCount` to `items.length + 1` until the paging API response doesn't return any more items. 

And totally! I had assumed, `loadMoreOptions(startIndex, stopIndex, internalState)` would be the signature.

For `loadMoreOptions`, you can also choose to just load the rest of the options as well. Would be totally up to the consuming team 😄  I totally see what you mean though in that the index-based solution is awkward when order isn't necessarily important for these items.

**Comment by psachs21** [comment]
@joshblack the more i think about it, the more I see how `rowCount`, in concept, makes sense, though i think we should change it's name to be more specific, maybe `totalItemCount`.

So I like the sig for `loadMoreOptions`, though i'm hesitant to expose the entire internal state as an API (making it difficult to change internal state). It should probably just look like `loadMoreOptions(startIndex, stopIndex, { filterValue })` for now.

**Comment by joshblack** [comment]
Agreed on both counts, @psachs21! I think those are great suggestions 😄
