### ISSUE TITLE
[DataTableToolbar] Table toolbar height shrink when no buttons are provided

### ISSUE THREAD

**Issue by nicoxxie** [IBM/carbon-components-react#598]
Browser: Chrome
Version: "carbon-addons-beta-react": "1.3.2", "carbon-addons-bluemix": "0.2.0",
Component: IAM

We have a table that only has batch action and no add button on the right side.
![screen shot 2018-02-09 at 10 07 41 am](https://user-images.githubusercontent.com/17915105/36037857-97f10d30-0d83-11e8-8296-930c179d0c38.png)

**Comment by joshblack** [comment]
This might require us to update the styles upstream in `carbon-components`, right @marijohannessen?
