### ISSUE TITLE
the Tooltip component not updating position once rendered

### ISSUE THREAD

**Issue by mandie12** [IBM/carbon-components-react#605]
Hi,
Im using the Tooltip component. Once it is rendered first time it takes that position in the screen. If you scroll left or right the tooltip still stays in that position it does not update to be under the icon. I could reproduce it on carbon site by setting the iframe body to width:1000px.

<img width="1433" alt="screen shot 2018-02-13 at 16 37 52" src="https://user-images.githubusercontent.com/5472918/36163534-90bade90-10e1-11e8-99bc-545809700c54.png">

Using version:
“carbon-components”: “^8.10.1",
   “carbon-components-react”: “^5.19.0",
   “carbon-icons”: “^6.3.0",
   “carbon-themes”: “^1.6.0",

I reverted back to version and issue was still there:
"carbon-components-react": "5.17.7"

Thanks

**Comment by asudoh** [comment]
Floating menu puts itself into `<body>`, need to introduce a way to change that. Ref: https://github.com/carbon-design-system/carbon-components-react/pull/574
