### ISSUE TITLE
Tooltip constantly flickers when hovering over triangle pointer

### ISSUE THREAD

**Issue by mandie12** [IBM/carbon-components-react#614]
Tooltip constantly flickers when hovering over triangle pointer
Test on:
http://react.carbondesignsystem.com/?selectedKind=Tooltip&selectedStory=default%20%28bottom%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Scroll mouse from the bottom of the page to the (i) and hover over the triangle the tooltip will keep flickering

**Comment by aledavila** [comment]
Going to close this for now given that we can't find a reliable way to reproduce. Feel free to re-open if bug persists.
