### ISSUE TITLE
Enhancement: ModalWrapper support warning type

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-components-react#640]
## Detailed description
I'd like to show an Warning/Confirmation type dialog with a ModalWrapper, but need to change the class of the Modal Container so I can change the color of the top border to indicate an Warning condition.  I'd like to passthrough any non-specified properties to either the div wrapped around the ModalContainer or the ModalContainer itself so I can add these custom styles.  See below for an example picture.

> Is this issue related to a specific component?
ModalWrapper

> What did you expect to happen? What happened instead? What would you like to see changed?
This is the look and feel I'm going for..
![image](https://user-images.githubusercontent.com/6663002/36546814-f90e88d0-17b1-11e8-94d9-8c934071e813.png)

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
5.23.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
No

## Steps to reproduce the issue
See this sandbox for the kind of property I'd like to pass:
https://codesandbox.io/s/xpq1olqjkp

## Add labels
enhancement

**Comment by joshblack** [comment]
Hi @scottdickerson! 👋  Thanks so much for taking the time to make this issue 😄

This feature request seems perfectly reasonable 👍 will definitely add it to our backlog and try to get it prioritized, in the meantime will gladly accept any PR contributions to support this!

**Comment by tw15egan** [comment]
Since we added `danger button primary` and `tertiary button` in `carbon-components`, we should support the use of them in the React package as well

**Comment by ivanzvonkov** [comment]
@joshblack Would a PR which officially adds the "danger" prop to ModalWrapper resolve this issue?

**Comment by asudoh** [comment]
Hi :wave: @ivanzvonkov it appears that `<ModalWrapper>` passes along `danger` already. Create #1914 to demonstrate that.

**Comment by ivanzvonkov** [comment]
So this issue is resolved? @asudoh

**Comment by asudoh** [comment]
@ivanzvonkov Yes.
