### ISSUE TITLE
Breadcrumb Behavior in IBM Cloud

### ISSUE THREAD

**Issue by depietronick** [IBM/carbon-components-react#657]
## Detailed description

Consistency in the behavior of breadcrumbs has been outlined by IBM Cloud design team.

> Is this issue related to a specific component?

Breadcrumb

> What did you expect to happen? What happened instead? What would you like to see changed?

The current page should be the last item in the interior left navigation. It should not be an active link. Backward navigation guidelines: https://github.ibm.com/Bluemix/console-design-kit/wiki/Back-Navigation

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud console

**Comment by joshblack** [comment]
Hi @depietronick! Going to close this since the issue itself is outdated. Feel free to re-open if this is still an issue!
