### ISSUE TITLE
Allow Table zebra lines to be optional

### ISSUE THREAD

**Issue by nicoxxie** [IBM/carbon-components-react#699]
## Detailed description

> Describe in detail the issue you're having.

Table rows are always in zebra background colors, allow all white backgrounds.

> Is this a feature request (new component, new icon), a bug, or a general issue?

general issue

> Is this issue related to a specific component?

Table

> What did you expect to happen? What happened instead? What would you like to see changed?

'bx--data-table-v2--zebra' class is optional

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

5.29.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud

## Additional information
![screen shot 2018-03-08 at 11 36 42 am](https://user-images.githubusercontent.com/17915105/37166571-052aae5a-22c5-11e8-942d-47fe4b346023.png)

**Comment by joshblack** [comment]
Hi @nicoxxie! Would defer to [this article](http://alistapart.com/article/zebrastripingdoesithelp) which recommends using zebra stripes due to the following rationale:

> **The recommendation**
>
> The results of the three studies conducted to date suggest that the safest option is to shade the alternating, individual rows of your table with a single color. Taking this approach is likely to ensure that:
> * task performance is better, or at least no worse, than with other table styles, and
> * the aesthetic sensibilities and subjective preferences of the majority of your users are catered for.
>
> If zebra striping of this type cannot be done easily, then ruling a line between each row may be the next best option.

**Comment by nicoxxie** [comment]
@joshblack I see your point, bringing up to our designer.

**Comment by bellsworth13** [comment]
@joshblack @alisonjoseph Was a decision made on this? Mh team would also like the zebra rows to be optional. I see that they are currently optional in the `DataTableSkeleton` component but are still not optional on for the Table itself.

**Comment by joshblack** [comment]
Hi @bellsworth13! 👋 Any chance the designers could weigh in based off of the feedback in that article?

**Comment by vsnichols** [comment]
@joshblack @bellsworth13 I believe the zebra stripes used to be optional and were used less frequently than the plan white rows. On the dashboard in particular I feel that they add unnecessary visual complexity, especially now that we have the blue row hover. 

Most importantly when there is blue link text or anything at all lightweight in a dark zebra row, the blue hover makes it dark enough as to be inaccessible. I guess that's something to look into fixing, but I definitely think in general designers should have the option to not have zebra stripes.

**Comment by vsnichols** [comment]
@joshblack Re: the article above - the tables without zebra stripes do have those thin rules between rows that the article mentions

**Comment by joshblack** [comment]
Makes sense, thanks for the explanation @vsnichols! 👏

**Comment by bellsworth13** [comment]
If I made a PR to address these changes, would it be accepted or is there still further discussions to be had?

**Comment by joshblack** [comment]
Go for it @bellsworth13!

**Comment by asudoh** [comment]
#1207 seems to address this problem. Don't hesitate to speak up if anybody sees otherwise - Thanks!
