### ISSUE TITLE
Icon component should have ability to remove title tab inside svg

### ISSUE THREAD

**Issue by chenzhh** [IBM/carbon-components-react#726]
## Detailed description

> Describe in detail the issue you're having.
In some case Icon component should not contain title tag or attribute
Eg: 
![image](https://user-images.githubusercontent.com/12123055/37640676-a9774924-2c51-11e8-956f-847e97925a8c.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?
 feature request
> Is this issue related to a specific component?
Icon -> Tooltip
> What did you expect to happen? What happened instead? What would you like to see changed?
Icon should add a new switch to enable/disable title tag
> What browser are you working in?
Chrome
> What version of the Carbon Design System are you using?
Latest
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Cloud Object storage
Please resolve asap

**Comment by tw15egan** [comment]
I'm pretty sure the `title` tag is needed for `a11y` purposes, but I could be wrong. @carbon-design-system/ui?

**Comment by asudoh** [comment]
Good question @tw15egan! Wondering if `aria-label` or a like work 🤔.

**Comment by chenzhh** [comment]
Icon component has aria-label attribute for a11y purpose.  So title tag is not a must have option. 

If Icon standalone usage have to include a title to popup a tooltip to indicate use the content. At least in some other scenario (like tooltip), we have the ability to turn off the title.

**Comment by joshblack** [comment]
I _think_ that the order of preference for what is read to the screenreader for an `svg` element is:

* `aria-labelledby`
* `aria-label`
* SVG `title`
* `title` attribute

![screen shot 2018-03-21 at 9 43 43 am](https://user-images.githubusercontent.com/3901764/37716378-63aa36fe-2cec-11e8-9bb3-f1ffe9a67392.png)

So `title` is definitely not required, as long as one of the other attributes are specified. Might be worth having a custom prop type for these situations 😮

**Comment by tw15egan** [comment]
I'm okay with removing the `title`, as long as we place a check that ensures that if the `title` is missing, an `aria-label` or `aria-labelledby` must be required

**Comment by joshblack** [comment]
Definitely agreed @tw15egan

**Comment by chenzhh** [comment]
Hey, I just want to confirm when will this issue be fixed and which version of release can see the updates.
