### ISSUE TITLE
a11y: OverflowMenu menuitem role is not contained in group/menu/menubar role

### ISSUE THREAD

**Issue by lilyclyc** [IBM/carbon-components-react#741]
Test it on carbon react storybook for OverflowMenu

An element with WAI-ARIA role menuitem is not contained in or owned by an element with one of the following WAI-ARIA roles: group, menu, menubar. See rule help for remediation guidance.

![image](https://user-images.githubusercontent.com/30255650/37815664-bec5aa68-2eaa-11e8-90a5-b578f0ca36fa.png)

**Comment by joshblack** [comment]
Closed by https://github.com/IBM/carbon-components-react/commit/9d609d2fd0e327d9bce01e4abb2240d4a01becb4
