### ISSUE TITLE
[Docs] Create documentation examples for React Router with common navigational components

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-components-react#795]
Would be great if we could provide documentation around, or examples of, usage of common navigational components with React Router. For example:

- Breadcrumb
- Tabs
- ILN

**Comment by emyarod** [comment]
if examples were to be added to the documentation, React Router would have to then be a dependency of the carbon-components-react project right? would that be alright?

**Comment by joshblack** [comment]
Go for it @alisonemiller! 🎉
