### ISSUE TITLE
Clicking on calendar icon in DatePicker does not bring up the DatePicker

### ISSUE THREAD

**Issue by kglickman** [IBM/carbon-components-react#800]
####Description

If I hover over the calendar icon, the mouse cursor changes to indicate that it is clickable.  However, if I click on it, nothing happens.  Instead, clicking inside the edit box changes brings up the calendar popup.
I thought that there was maybe a problem with my implementation, but the behavior is the same in the storybook for the "single with calendar" variation.

I think that the calendar should only come up when you click on the icon and not when you click on the edit field.  Alternatively, the mouse cursor should not change when hovering over the calendar icon.

> What browser are you working in? **Chrome**

> What version of the Carbon Design System are you using?
		"carbon-components": "8.16.1",
		"carbon-components-react": "5.23.1",
		"carbon-icons": "6.3.1",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
OpenPages

## Steps to reproduce the issue
Try it in the story book for Date Picker - single with calendar

**Comment by joshblack** [comment]
cc @marijohannessen is this expected behavior for the DatePicker?

**Comment by marijohannessen** [comment]
Fixed in #847
