### ISSUE TITLE
Disable code snippet copy/paste

### ISSUE THREAD

**Issue by nicthemighty** [IBM/carbon-components-react#850]
## Detailed description

> Describe in detail the issue you're having.

CodeSnippet does not provide the ability to disable copy/paste button or feedback

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

CodeSnippet

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected to be able to disable the copy button with a disabled attribute on the code snippet. This allows me to show code snippets in the correct formatting, but stops user from copying it.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?
5.36.0

**Comment by joshblack** [comment]
Hi @nicthemighty! 👋 Thanks so much for taking the time to make this issue 🙂

Went ahead and added the `discussion` label to this to bring up at our next backlog grooming session to see if we want to support this use-case. Feel free to weigh-in on this issue with any additional details, like product/offering, that would help make the case for us supporting this pattern for this component!

**Comment by joshblack** [comment]
Going to close this for now. Feel free to re-open if you feel like this is still an important feature request!
