### ISSUE TITLE
TableHeader component's sort icon doesn't receive focus

### ISSUE THREAD

**Issue by showeimer** [IBM/carbon-components-react#854]
## Detailed description

> Describe in detail the issue you're having.

The sort icon on the TableHeader component can't be accessed when tabbing.  Therefore a user who relies on tabbing can't utilize the sort functionality on the tables.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Accessibility bug

> Is this issue related to a specific component?

TableHeader

> What did you expect to happen? What happened instead? What would you like to see changed?

The sort icon on the TableHeaders should be accessible when tabbing.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ICP

## Steps to reproduce the issue

This issue can be seen on the Carbon Storybook

http://react.carbondesignsystem.com/?selectedKind=Table&selectedStory=Simple%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by joshblack** [comment]
Hi @showeimer! 👋 Unfortunately the table you linked is the v1 version of the tables for Carbon. I would look to the DataTable component as the successor to the v1 table that you had linked, which should have the behavior that you noted.

Definitely agree that this is an issue in v1, but unfortunately don't know if we can get a fix prioritized by the core team. Will 100% accept any PRs to fix this issue though!

**Comment by joshblack** [comment]
Closing this since it relies on the v1 behavior. Feel free to re-open if this is still an issue!
