### ISSUE TITLE
DataTable headers prop requires array of strings

### ISSUE THREAD

**Issue by fairclothjm** [IBM/carbon-components-react#878]
## Detailed description

> Describe in detail the issue you're having.

The DataTable headers prop requires an array of strings. I would like to pass a node. Our project requires a header to have a Tooltip.  So our headers array looks like:

```
const myObject = (
  <Tooltip triggerText={t('example')}>
    {t('exampleTooltip')}
  </Tooltip>
);

headers = [
  {
    key: 'myKey',
    header: myObject,
},
// ...
];
```

I am seeing the following error:
```
Warning: Failed prop type: Invalid prop `headers[4].header` of type `object` supplied to `DataTable`, expected `string`.
```

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug/improvement

> Is this issue related to a specific component?

DataTable

> What did you expect to happen? What happened instead? What would you like to see changed?

I would like to pass a node to the headers[i].header prop

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

5.47.0

**Comment by kkomprakash** [comment]
When Tooltip component is passed as headers, then `mouseover` event doesn't work as the entire markup is inside a `button` element. So it should be `div` instead `button` in order to make it work.
