### ISSUE TITLE
The OverFlowMenu doesn't take the horizontal scroll view into account when using a floating menu

### ISSUE THREAD

**Issue by zgrossbart** [IBM/carbon-components-react#911]
Create an OverFlowMenu in a component that is wide enough that you causes a horizontal scroll bar in the window and uses the `floatingMenu` option.  Now scroll the window to the right and select the three dots to show the menu.

At this point the floating menu should be below the three dots, but it will be positioned to the left by the number of pixels the horizontal scroll bar has been scrolled.  Like this:

<img width="715" alt="screen shot 2018-05-22 at 3 25 26 pm" src="https://user-images.githubusercontent.com/664044/40360098-f04559f0-5d92-11e8-9432-98249c303fdc.png">

**Comment by asudoh** [comment]
Thanks @zgrossbart for reporting! The code has [some vertical scrolling support](https://github.com/carbon-design-system/carbon-components-react/blob/2a66ee5/src/internal/FloatingMenu.js#L73), and doing similar for horizontal scrolling is a possibility.

OTOH, the screenshot tells me that the data table is causing the horizontal scrolling. Given horizontal scrolling tends to cause non-ideal user experience, I think you may want to consider hiding some non-important columns if the width of the viewport is small. CC @carbon-design-system/design

**Comment by joshblack** [comment]
Closed by #1117
