### ISSUE TITLE
Carbon-components font misses ellipsis

### ISSUE THREAD

**Issue by dawangdw** [IBM/carbon-components-react#925]
## Detailed description

> Describe in detail the issue you're having.

Carbon-components css `font-family: "ibm-plex-sans",Helvetica Neue,Arial,sans-serif` runs into issue on IE11.

> Is this a feature request (new component, new icon), a bug, or a general issue?

A bug.

> Is this issue related to a specific component?

Nope.

> What did you expect to happen? What happened instead? What would you like to see changed?

`font-family: "ibm-plex-sans",Helvetica Neue,Arial,sans-serif` works well on IE11.

> What browser are you working in?

IE 11.

> What version of the Carbon Design System are you using?

```
    "carbon-components": "^8.18.18",
    "carbon-components-react": "^5.44.0",
```

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
ASAP.

Issue screenshot:
![image](https://user-images.githubusercontent.com/16933250/40540628-630b3fb2-604b-11e8-8028-b0b2169ddebd.png)

**Comment by tw15egan** [comment]
Related: https://github.com/carbon-design-system/carbon-components/issues/665
Related: https://github.com/IBM/plex/pull/160
