### ISSUE TITLE
DatePicker with range - make calendar icon optional

### ISSUE THREAD

**Issue by tonydiaz** [IBM/carbon-components-react#966]
## Detailed description

> Describe in detail the issue you're having.

Requesting a feature to allow users to decide whether or not the **calendar icon** displays when using the DatePicker component. 

<img width="337" alt="screen shot 2018-06-04 at 10 00 31 pm" src="https://user-images.githubusercontent.com/7145340/40950913-ba34aa04-6842-11e8-9a3b-d31ce5c66cdd.png">

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature

> Is this issue related to a specific component?

DatePicker component
> What did you expect to happen? What happened instead? What would you like to see changed?

Would like to have the ability to hide the calendar icon. In our current design for Watson Assistant the calendar icon breaks the design. 
> What browser are you working in?

Chrome
> What version of the Carbon Design System are you using?

v5.50.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Assistant. Q2 deliverables
## Steps to reproduce the issue

Use the DatePicker component with the range and the calendar icon displays without a way to disable/hide it. 
http://react.carbondesignsystem.com/?selectedKind=DatePicker&selectedStory=range%20with%20calendar&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

## Additional information

* Screenshots or code
<img width="337" alt="screen shot 2018-06-04 at 10 00 31 pm" src="https://user-images.githubusercontent.com/7145340/40950999-2a759a44-6843-11e8-9909-714917b7d854.png">

* Notes

**Comment by asudoh** [comment]
Hi @tonydiaz thank you for reporintg! Need to see with the team if we can bake in such option in the main `cabron-components-react` repo. Meanwhile - Would you want to go with a CSS way to hide the calendar icon?

**Comment by tonydiaz** [comment]
@asudoh I guess that would work. Do you mean just overriding the CSS classes?

**Comment by asudoh** [comment]
@tonydiaz Exactly!

**Comment by tonydiaz** [comment]
@asudoh I was able to do that thanks!

**Comment by echarpibm** [comment]
Might be nice to share the CSS solution with others!

**Comment by tonydiaz** [comment]
Sure:
```
.bx--date-picker__icon {
  display: none;
}
```

**Comment by joshblack** [comment]
Going to close this since this seems like it has a solution in user-space. Feel free to re-open if you feel like this should be in core! Will gladly accept PRs implementing this, I believe 😄
