### ISSUE TITLE
DatePicker doesn't work proper on iPad (iOS)

### ISSUE THREAD

**Issue by IOIO72** [IBM/carbon-components-react#968]
On initial page loading I'm getting an error thrown by _flatprickr about the undefined object `calendarContainer.classList` in Safari on iPad. I guess, that the fallback case of flatpickr on iOS isn't considered in the DatePicker implementation.

Some other errors occur by using the DatePicker after this. I think they are caused by the initial state of the DatePicker.

https://github.com/carbon-design-system/carbon-components-react/blob/9097a6afbfc29571aa0e20723e550cfb1487f656/src/components/DatePicker/DatePicker.js#L324

**Comment by joshblack** [comment]
Hi @IOIO72! 👋 Thanks so much for taking the time to report this. To help us debug here, what version of Safari are you trying to run this on? `classList` should be available in modern versions that we have listed in our browser support.

Going to close this for now, feel free to re-open though if what I stated before isn't the case!
