### ISSUE TITLE
TableToolbarSearch: Cannot pass through placeHolderText to Search

### ISSUE THREAD

**Issue by bellsworth13** [IBM/carbon-components-react#999]
## Detailed description

> Describe in detail the issue you're having.

I want to change the placeholder text of the search bar in the DataTable so we can indicate to the user the functionality of this search (which in this case would be to filter tags)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Update the component with a placeHolderText prop just like the regular `Search` component 

> Is this issue related to a specific component?

DataTable > TableToolbarSearch

## Additional information

![screen shot 2018-06-13 at 2 11 22 pm](https://user-images.githubusercontent.com/17937450/41372702-b376ec90-6f13-11e8-87c6-35bea2ab5bf8.png)

<img width="498" alt="screen shot 2018-06-13 at 2 06 01 pm" src="https://user-images.githubusercontent.com/17937450/41372448-f6ec5b28-6f12-11e8-8db6-bccb3d649e5d.png">

`<Search
        light
        className={className}
        {...rest}
        small
        id={id}
        labelText={t('carbon.table.toolbar.search.label')}
        placeHolderText={t('carbon.table.toolbar.search.placeholder')}
        onChange={onChange}
      />`

**Comment by joshblack** [comment]
Hi @bellsworth13! 👋 Thanks for taking the time to make this issue 😄 

This is currently supported through the `translateWithId` prop, but I definitely understand wanting to be able to just supply the prop directly. Will mark this as an enhancement, will definitely accept PRs here!
